### ISSUE TITLE
Serve on port 80, but assume urls start with https

### ISSUE THREAD

**Issue by kachkaev** [bitnami/bitnami-docker-wordpress#101]
Hi guys,

I'm using your image inside the [official helm chart](https://github.com/kubernetes/charts/tree/master/stable/wordpress) and looks like it is not compatible with an external HTTPS reverse-proxy. When wordpress is installed behind an ingress controller, all works fine as long as HTTPS is not used. When HTTPS is enabled by ingress, the styles and the scripts fall apart. The reason is because the reverse proxy terminates HTTPS and then talks to the wordpress container on port 80, but wordpress thinks that it's talking to the _external world_ on port 80 directly.

![bitnami-wordpress-https](https://user-images.githubusercontent.com/608862/28713360-9d5417a0-7386-11e7-82cd-61a745a7a2eb.png)

```
[user]  ---HTTPS-->  [k8s ingress controller + certs]  ---HTTP-->  [bitnami wordpress]
```

Terminating HTTPS by a reverse proxy is a common strategy these days despite that in theory it is possible to link the reverse proxy with the payload using HTTPS too. Internal HTTPS links are poorly supported at the moment from what I know and there is no need for them in simple setups really.

Wordpress thinks its on HTTP because the requests go from port 80, so all the links to resources and other pages start with `http://example.com` instead of `https://example.com`. As a result, the website remains unusable and it's not even possible to login to the admin panel. The forms point to `http://example.com`, so when any data is submitted, the server response is 301 → https :–)

The question is: how to tell wordpress that its base url should be HTTPS://example.com even on port 80? Looks like the domain name is detected correctly by apache despite that it's not explicitly passed to the container via ENV, which gives hope.

It might be also possible to add an option to force HTTPS urls similarly to how this is done in GitLab: there you can define `external_url 'https://example.com'` in the container's config and then place it behind a reverse proxy. GitLab will talk to nginx or traefik without HTTPS, but all pages will render as if there is HTTPS in where we are.

What can you guys suggest? It'd be cool if there was some hacky way to fix things without waiting for a new release. I'll try updating the helm chart once it's clear what to do.

**Comment by chipironcin** [comment]
Hi @kachkaev 
You can try specifying the env variable `WORDPRESS_HOST` to force WordPress to use a specific base URL, where you can use something like `https://example.com`

**Comment by titoc** [comment]
@chipironcin I tried. setting `WORDPRESS_HOST=https://blog.domain.com` , but it doesn't seem to have any effect. The admin panel still shows `http://blog.domain.com`

**Comment by kachkaev** [comment]
I did not try this @titoc, because I was installing wordpress using the [official helm chart](https://github.com/kubernetes/charts/tree/master/stable/wordpress), so modifying yamls was difficult. Instead, I followed @keunwoo's advice instead and it worked: https://github.com/kubernetes/charts/issues/1567#issuecomment-319582737

Given that the trick does not work for you, looks like there is now way of set up a reverse-proxy/HTTPS-enabled wordpress in one command without fiddling with plugins etc. @chipironcin what else could you recommend?

**Comment by chipironcin** [comment]
We are planning on adding some configurable variables to support this use case (something like `FORCE_TLS`.
Will update this thread once it is out and there is a PR.

**Comment by kachkaev** [comment]
Awesome! How about adding `HOST_HEADER_*` env variables as in https://github.com/kubernetes/charts/issues/1567#issuecomment-324394018)?

**Comment by prydonius** [comment]
@chipironcin any updates on this? There is a potential solution in https://github.com/kubernetes/charts/issues/1567#issuecomment-343444918

**Comment by kachkaev** [comment]
ping @chipironcin 😃

**Comment by chipironcin** [comment]
Sorry for not coming back in a while. An internal task was opened back in the days and I have been adding more information to it as potential solutions were appearing. I bumped it again and hopefully we can have a proper solution ready soon.

Will keep you posted, thanks for your interest on this as I think the feature is worth it.

**Comment by Noext** [comment]
any update on this ? got the same issue when running on a rancher/ha-proxy configuration

**Comment by tompizmor** [comment]
Hello @kachkaev, @Noext 

Recently we released WordPress 4.9.2-r1 including a setting in the Apache configuration that should fix this issue. The configuration is `SetEnvIf X-Forwarded-Proto https HTTPS=on`.

**Comment by kachkaev** [comment]
Great to hear that @tompizmor! Does your new configuration takes play automatically or is there a need to pass some environment variable to the container?

It is unlikely that I'll be setting up a new wordpress instance any time soon, but it's good to know that for future.

**Comment by tompizmor** [comment]
Hello @kachkaev,

The new configuration takes play automatically and users that just want to use HTTP won't have any issues as the Apache configuration is conditional to when you use HTTPS to connect.

Some useful links to understand the configuration:
- [SetEnvIf apache directive](https://httpd.apache.org/docs/current/mod/mod_setenvif.html#setenvif)
- [X-Forwarded-Proto attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto)

**Comment by kachkaev** [comment]
Right, thanks for an explanation @tompizmor. So if understand correctly, as long as the reverse-proxy is configured adequately, `X-Forwarded-Proto` header automatically appears in a request to the bitnami container. Apache inside this container passes an env variable `HTTPS=true` to PHP and this is how wordpress decides to use `https` in all links to assets. Switching back to `http` in a following request (for whatever reason) is as easy as not providing `X-Forwarded-Proto` header in it. Nice!
