### ISSUE TITLE
can't run docker-compose.yml

### ISSUE THREAD

**Issue by Fer-Picu** [bitnami/bitnami-docker-wordpress#102]
**Instace docker bitnami/wordpress failed**

**Steps to reproduce the issue:**

1. docker-compose up

**The docker container my_wordpress_1 exit with message standard_init_linux.go:178: exec user process caused "exec format error"**

Docker version 17.03.1-ce, build c6d412e
docker-compose version 1.11.2, build dfed245

**Comment by jotamartos** [comment]
Hi @Fer-Picu,

I'm sorry to hear that. I've just tried to reproduce the issue but I've not been able to do it. I've just cloned the repository and both containers are running for me.

```
               Name                             Command               State                    Ports
----------------------------------------------------------------------------------------------------------------------
bitnamidockerwordpress_mariadb_1     /app-entrypoint.sh /run.sh       Up      3306/tcp
bitnamidockerwordpress_wordpress_1   /app-entrypoint.sh nami st ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
``` 

Could you please let us know more information about the issue?

- Which Operating System are you using? 
- Did you launch any Bitnami WordPress container before running into this issue?
- Did you modify any values in the default docker-compose.yml file?

This link could give you some hints to fix the issue

https://github.com/moby/moby/issues/23865#issuecomment-318189551

They suggest you run the prune command so this is something you can do:

```
git pull --rebase (in case you have the repository, if not, get the latest version of the docker-compose.yml file from Github)
docker-compose down -v && docker-compose pull && docker-compose up --build --force-recreate
```

Regards,
Jota
