### ISSUE TITLE
docker-compose.yml syntax error

### ISSUE THREAD

**Issue by shumoapp** [bitnami/bitnami-docker-wordpress#103]
**Description**

Volumes are not mounting to the host machine, because the volumes declaration is surrounded by quotes. The quotes should be removed, and the relative paths should start with a dot (.). See Compose file version 2 reference here:
https://docs.docker.com/compose/compose-file/compose-file-v2/#volumes-volume_driver
 
- ./mariadb_data:/bitnami
- ./wordpress_data:/bitnami

**Steps to reproduce the issue:**

1. Just follow the instructions for the docker-composer.yml file.
2. Check your folders and you'll see that the host machine does not have mariadb_data and wordpress_data folders. 

**Describe the results you received:**

Instead of mapping the persistent folders to the host machine, docker is mounting the folders to it's own ephemeral volumes.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Also, when the mariadb_data folder is created, the mariadb docker image cannot create content inside it (docker logs prints: Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/mariadb')
Which is strange, considering that the wordpress docker image was able to create folders inside wordpress_data folder. 

And, because of the improper declaration of volumes, WORDPRESS_USERNAME and WORDPRESS_PASSWORD env variables does not make a difference. I suppose the other env vars are not affecting the setup as well. 

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:33 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

- Output of `docker info`:

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 28
Server Version: 17.06.2-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 69
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-129-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.53GiB
Name: tino
ID: G6NA:PQJ3:7TU2:XIRO:ENOH:XYKP:MEJD:URZR:XWWA:GJDS:NK4J:DG6Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by sameersbn** [comment]
@shumoapp thanks for raising this issue and sorry about the confusion you may have had to deal with due to the use of the quotes around the volumes. While the current syntax is valid yaml, we acknowledge that its use can cause confusion among our users and going forward we have decided to drop their use.

Since we're planning on applying this change to all our repo's, it may take a while to get update.

**Comment by garrystevens** [comment]
hmmmm, it seems the repo compose file still contains the quotes, I nearly lost a few days worth of blog creation due to this, it would be good to update the repo compose file.

Aside from that, great repo.

**Comment by juan131** [comment]
Thanks so much for reporting it @garrystevens 
I'll create a PR to fix it
