### ISSUE TITLE
Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module identifier in the options parameter along with the module name

### ISSUE THREAD

**Issue by wanshaoyuan** [bitnami/bitnami-docker-wordpress#105]
I user Rancher version 1.6.11 App Store  install Wordpress,install Wordpress error 
logs:
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module identifier in the options parameter along with the module name

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing apache
Error executing 'postInstallation': Module mod_version is not present in the configuration file, you need to provide a module identifier in the options parameter along with the module name

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com

**Comment by juan131** [comment]
Hi @wanshaoyuan 

I am unable to reproduce your issue, I did not have any problem to create the containers using a simple `docker-compose up` using the latest version. 

Did you modify the Apache Configuration? Did you run a "clean" docker-compose up or did you have any kind of Apache persisted data?

**Comment by wanshaoyuan** [comment]
@

**Comment by wanshaoyuan** [comment]
@juan131  thank you very much！
