### ISSUE TITLE
Using WP-CLI

### ISSUE THREAD

**Issue by bptarpley** [bitnami/bitnami-docker-wordpress#106]
Hey, Bitnami developers!  I've been using the Bitnami Drupal containers and am happy with them, and am now considering porting all of our Wordpress instances to this container.  I have successfully migrated one instance, but now have a question:  How might I install and use WP-CLI on a Bitnami Wordpress instance?

**Comment by chipironcin** [comment]
Hi @bptarpley 
You can see this thread to get an idea on how to use wp-cli with Bitnami Wordpress.
The same commands apply as long as you are running them inside your container:
https://stackoverflow.com/questions/46823879/is-wp-cli-incompatible-with-bitnamis-wordpress-install-on-aws-lightsail

Hope it helps

**Comment by sameersbn** [comment]
@bptarpley can you confirm if the issue was resolved?
