### ISSUE TITLE
Facing issue using bitnami wordpress with wp-directory-box-manager plug-in

### ISSUE THREAD

**Issue by steve-sarkisian** [bitnami/bitnami-docker-wordpress#107]
**Description**

I am testing deploying Wordpress on Docker using Bitnami wordpress image.  I've stood up instance(s) using docker-compose and initially things look OK.  Used all-in-one-migrator plug in to create image from non Docker site, then attempted to import.  Import hangs, and docker outputs the following repetitively:

wordpress_1  | 172.20.0.1 - - [13/Dec/2017:19:29:24 +0000] "GET /wp-admin/admin-ajax.php?action=ai1wm_status&secret_key=8GTj6wU3GaT1&_=1513192715107 HTTP/1.1" 500 1458

**Steps to reproduce the issue:**

1. Create directory for Bitnami wordpress, copy docker-compose.yml into it
2. Run docker-compose up
3. Login to locahost/wp-admin
4. Go to plugins section, activate all-in-one-migration
5. Go to all-in-one migration->import.  Drag in my local backup
6. Import gets through first few steps, on restoring database step, hangs at 97%.  The following can be seen in console: wordpress_1  | 172.20.0.1 - - [13/Dec/2017:19:29:24 +0000] "GET /wp-admin/admin-ajax.php?action=ai1wm_status&secret_key=8GTj6wU3GaT1&_=1513192715107 HTTP/1.1" 500 1458
7. Tried to start over without import, just installed DirectoryBox theme, which depends on wp-directory-box-manager, errors as well

**Describe the results you received:**

Output from each step is listed above.

**Describe the results you expected:**

Expected a successful import

**Additional information you deem important (e.g. issue happens only occasionally):**
Information I get from apache log:

[Wed Dec 13 19:24:56.005233 2017] [:error] [pid 106] [client 172.20.0.1:56278] PHP Fatal error:  Uncaught Error: Call to undefined function wp_create_nonce() in /opt/bitnami/wordpress/wp-includes/functions.php:1470\nStack trace:\n#0 /opt/bitnami/wordpress/wp-admin/includes/file.php(1765): wp_nonce_field('filesystem-cred...', '_fs_nonce', false, true)\n#1 /bitnami/wordpress/wp-content/plugins/wp-directorybox-manager/backend/settings/includes/plugin-options-functions.php(128): request_filesystem_credentials('', 'ftpext', false, false, Array)\n#2 /bitnami/wordpress/wp-content/plugins/wp-directorybox-manager/backend/settings/includes/plugin-options-array.php(7): wp_dp_get_settings_demo('demo.json')\n#3 /bitnami/wordpress/wp-content/plugins/wp-directorybox-manager/wp-directoryplus-manager.php(775): require_once('/bitnami/wordpr...')\n#4 /bitnami/wordpress/wp-content/plugins/wp-directorybox-manager/wp-directoryplus-manager.php(50): wp_dp->includes()\n#5 /bitnami/wordpress/wp-content/plugins/wp-directorybox-manager/wp-directoryplus-manager.php(1764): wp_dp->__construct()\n#6 /opt/bitnami/wordpress/wp-settings.php(305): in /opt/bitnami/wordpress/wp-includes/functions.php on line 1470, referer: http://localhost/wp-admin/admin.php?page=site-migration-import
**Version**

- Output of `docker version`:

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true

- Output of `docker info`:

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 10
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.855GiB
Name: moby
ID: BRXY:VBWZ:VYSD:4Q6T:JCKC:HRY2:OUIT:DY6S:YBEV:BP7L:GYQJ:HRSL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 40
 Goroutines: 66
 System Time: 2017-12-13T19:36:03.341121388Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

- Output of `docker-compose version` (if applicable):

docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker for Mac

**Comment by juan131** [comment]
Hi @steve-sarkisian was unable to reproduce the issue. I could activate the all-in-one-migrator plugin and then I could import successfully a backup previously created on a different WP. See screenshot:

<img width="470" alt="screen shot 2017-12-14 at 10 44 34" src="https://user-images.githubusercontent.com/6740773/33985846-ff74df76-e0bb-11e7-9f48-cf05e9894ed8.png">

Did you have the same plugins installed on the site you created the backup that you have in the containerised WP?

**Comment by steve-sarkisian** [comment]
Hi @juan131,

Think I'm maybe closing in on the issue a bit.  Rather than using all in one migrator, I figured I'd start replicating the theme and plug in installs from original site.  The theme itself requires wp-directoryplus-manager plug in to operate.  It is installing this plug-in that appears to cause errors.

Do you know if anyone else has made this theme/plug-in work? Maybe I should contact the authors of that theme as well?

**Comment by juan131** [comment]
Hi @steve-sarkisian 

I can't tell... We usually solve problems related to the Bitnami containers through this platform.. However, for information regarding the application itself or customization of the content within the application, we highly recommend checking forums and user guides made available by the project behind the application since they know much more than us about how to debug it.

You might get more information at WP Support Forums:
https://wordpress.org/support/

It's also a good idea to contact the themes developers, they'd giver you more hints about where to spot.
