### ISSUE TITLE
Unable to use Advanced Custom Fields

### ISSUE THREAD

**Issue by khylias** [bitnami/bitnami-docker-wordpress#112]
**Description**

I'll use Advanced Custom Fields on my wordpress website using this docker images. But it seems that ACF doesn't work because it return always 404 error on each plugin's file.

**Steps to reproduce the issue:**

1. Launch the docker image with the docker-compose example
2. Connect to admin
3. Install ACF plugin
4. Try to add a new field group for example.

**Describe the results you received:**

**Describe the results you expected:**

I would be happy to use ACF with this docker image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`: 

```
Docker version 17.12.0-ce
```

- Output of `docker info`: I don't have conflict with other working containers.

```
containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 104
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.818GiB
Name: linuxkit-025000000001
ID: STJR:PABA:3GYZ:IJIV:KMSK:LHAD:M7Y3:JPDN:RZHF:KWQW:5NE4:XUBD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 73
 System Time: 2018-02-05T08:41:25.728312612Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3128
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I'm currently using Docker for MAC.

**Comment by xap5xap** [comment]
I managed to fix this problem modifying one function in the plugin's acf.php file:
In the function helpers_get_dir replace the return line "return $dir" with return str_replace("/bitnami/wordpress", "",$dir);

Now, that 404 error should be gone.

**Comment by juan131** [comment]
Hello @xap5xap 

Thanks for sharing this workaround! @khylias could you please try it?

**Comment by khylias** [comment]
Hi @xap5xap , @juan131,

oh god, thanks for this workaround, it works well !
I didn't try with other plugins but I hope we didn't have to edit all the plugin configuration files.

**Comment by xap5xap** [comment]
I had to make the same change to the Custom Post Types plugin. I dont know what is going to happen when these plugins need an upgrade. Maybe the same changes should be deployed again. Perhaps something has to be improved with this docker image.

**Comment by juan131** [comment]
@jotamartos do you think it can be a problem on the configuration?

**Comment by bernardd** [comment]
I was just fighting with this myself today! Thanks for the workaround. It'd be great to know where the "right" place to fix this properly is.

**Comment by jotamartos** [comment]
Hi all, 

We just checked this issue deeply and we found the root cause of the issue. As we create a volume for some WordPress files inside the /bitnami folder, the plugin detects that the plugins folder is not inside the `WP_PLUGIN_DIR` folder. They both are actually the same folder and you can access it using the different paths. This can be easily modified by setting this variable in the WordPress configuration file:

```
...
define( 'WP_PLUGIN_DIR', '/bitnami/wordpress/wp-content/plugins' );

/* That's all, stop editing! Happy blogging. */
...
```

We are going to open a task on our side to modify this configuration in the WordPress container. 

Let us know if that works for you. 

Thank you,
Jota

**Comment by silviofdez** [comment]
We have released a new WordPress revision that already included the configuration @jotamartos talked about. I will mark this case as solved.
