### ISSUE TITLE
Environment variable to change the table prefix

### ISSUE THREAD

**Issue by xap5xap** [bitnami/bitnami-docker-wordpress#113]
Is that a way to change the table prefix? It would be great if the tables are created without the default wp_ prefix. That would give extra protection against automated sql injection attacks.

**Comment by juan131** [comment]
As you can find in the README: https://github.com/bitnami/bitnami-docker-wordpress#environment-variables

You can use the env. variables `WORDPRESS_DATABASE_NAME` and `WORDPRESS_DATABASE_USER` to change the default value so the names of the database and the user are different. However, regarding the tables prefix, there are some plugins that can do that:

https://wordpress.org/plugins/change-table-prefix/

**Comment by xap5xap** [comment]
@juan131 Thanks for your response. However, I am using this docker image in AWS Beanstalk. So whenever you deploy an update for the theme, the image recreates the wp-config file. That means the tables are generated again since the wp_ tables dont exist in the database. We decided to keep the wp_ prefix but that could be something to improve in this great image.

**Comment by juan131** [comment]
The prefix can be changed during the installation process of WordPress. However, we did not implement the logic for modifying this using environment variables as we did for other parameters. 

I think it could be interesting to include this feature, what do you think @jotamartos ?

**Comment by jotamartos** [comment]
Hi @xap5xap,

Thank you for taking the time to share this feedback with us. I'm going to open a task on our side to edit the WordPress configuration so you can set the table prefix value when using this Docker image. We will update the documentation as well. 

I can't provide you with any estimation right now about when this will be available. We will update this issue once everything is ready.

Thanks,
Jota

**Comment by andresbono** [comment]
Hi @xap5xap, we have just updated the container to allow specifying the table prefix that you want to use starting with the [4.9.4-r5](https://github.com/bitnami/bitnami-docker-wordpress/releases/tag/4.9.4-r5) release.

Now you can provide the `WORDPRESS_TABLE_PREFIX` env var. For more information, please check the [README.md: Use an existing database](https://github.com/bitnami/bitnami-docker-wordpress/#user-content-use-an-existing-database).

Thanks for suggesting this!

Regards,
-Andrés B.
