### ISSUE TITLE
Wordpress on Kubernetes - getting real IP

### ISSUE THREAD

**Issue by tomerleib** [bitnami/bitnami-docker-wordpress#117]
Hi, 
I've deployed WordPress on my Kubernetes cluster on top AWS using your helm chart published by ELB. 
I wish to block access to wp-admin for my IP only, however WordPress does not recognize my IP.
The only IPs, that I was able to get are either the private IP of the nodes or the one of the service endpoint.
Is it possible to set x-forwarded-for on your image without using ingress controller or varnish?

**Comment by juan131** [comment]
> however WordPress does not recognize my IP.
> The only IPs, that I was able to get are either the private IP of the nodes or the one of the service endpoint.

The Helm Chart creates a `LoadBalancer` Service by default and it's setting `externalTrafficPolicy` to "Cluster".

```
$ kubectl get svc
NAME                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kubernetes                    ClusterIP      10.96.0.1       <none>        443/TCP                      24m
messy-hummingbird-mariadb     ClusterIP      10.109.118.99   <none>        3306/TCP                     5m
messy-hummingbird-wordpress   LoadBalancer   10.105.24.119   <pending>     80:31085/TCP,443:32293/TCP   5m
```

```
 kubectl get svc messy-hummingbird-wordpress -o yaml | grep externalTrafficPolicy
  externalTrafficPolicy: Cluster
```

Set it to "Local" to preserve the client IP. Then run to check it the command below:

```
kubectl exec -it <WP-POD-ID> cat /opt/bitnami/apache/logs/access_log
```

More information at:

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

**Comment by juan131** [comment]
I created this PR to implement it on the Chart: https://github.com/kubernetes/charts/pull/4273
