### ISSUE TITLE
/opt/bitnami/apps directory does not exist

### ISSUE THREAD

**Issue by bloodcarter** [bitnami/bitnami-docker-wordpress#118]
I am using latest images and docker-compose.yml from master. Everyting works, wordpress starts, but I can not locale wordpress directory. /opt/bitnami/apps does not exist! Instead I have /opt/bitnami/wordpress directory.

**Comment by juan131** [comment]
Hello @bloodcarter 

The structure on the WordPress Docker image is slightly different from the one available in the Bitnami stacks. As you mentioned, WordPress is found under **/opt/bitnami/wordpress**
