### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by mtmsig** [bitnami/bitnami-docker-wordpress#120]
**Description**

I'd like to be able to disable cache so this image can be used as a base image for local development.
There seems to be some page/html caching activated, which makes it that I can't see my changes right away.

**Steps to reproduce the issue:**

1. Mount a theme to /bitnami/wordpress/wp-content/themes
2. edit a php template
3. reload page until visible

**Comment by juan131** [comment]
There's no cache activated by default on this Docker Image. 

As you can check there's no Varnish or PageSpeed configured on the Docker Image. There is no plugin to handle the cache activated by default neither (no W3 Total Cache, nor WP Super Cache, nor Quick Cache).

The problem could be OPCache (which is enabled on the php.ini file).  You can check by running:

```
tail -n 10 /bitnami/php/conf/php.ini
```

You can disable it or restarting apache whenever you change the php code. You can do it by running:

```
nami restart apache
```

**Comment by mtm-sig** [comment]
Thank you. Changing `opcache.enable = 1` to `opcache.enable = 0` did the trick.

An environment variable to turn it on and off would be nice.

**Comment by juan131** [comment]
What do you think @jotamartos @tompizmor ? Is it worth to have an env. variable for this?

**Comment by RomuloVitoi** [comment]
+1 for env. variable

**Comment by tompizmor** [comment]
yes, I think we can easily add an env var to enable/disable the opcache

**Comment by juan131** [comment]
All right! I just created an internal task and included it in our backlog. As the impact of the issue is moderate, there are no immediate plans to work on it. 

Nevertheless, it will be considered for future application versions. We will update this issue as soon as we have more news.

**Comment by rafariossaa** [comment]
Hi,
  We have added a new environment variable to disable opcache when needed.
  Could you give it a try ?

**Comment by smaar** [comment]
Hello @rafariossaa ,
thanks for adding the environment variable. Could you let me know how its called? I cant find it in the doc here yet 
https://github.com/bitnami/bitnami-docker-prestashop#environment-variables

Many Thanks

**Comment by juan131** [comment]
Hi @smaar 

The env. variable is called `PHP_OPCACHE_ENABLED`, see:

- https://github.com/bitnami/bitnami-docker-wordpress#environment-variables

Are you using Prestashop or WordPress?

**Comment by smaar** [comment]
Hi @juan131 
thanks a lot. I am using Prestashop. Sorry I got confused and thought this would also work for Prestashop.

Kind Regards,
Shadi

**Comment by juan131** [comment]
Hi @smaar 

The current PHP settings that can be modified via env. variables are listed in the link below:

- https://github.com/bitnami/bitnami-docker-prestashop#php-configuration

Please open an issue at https://github.com/bitnami/bitnami-docker-prestashop/issues to request OPCache to be added too.

**Comment by darrenbarklie** [comment]
Hi, unfortunately I am unable to get this setting to take effect as intended.

When I copy and bind a local `php.ini` to the container's `/opt/bitnami/php/lib`, I can see the config `opcache.enable = 1` applied, whether I pass in `PHP_ENABLE_OPCACHE=yes` or `PHP_ENABLE_OPCACHE=no` -- the result is the same.

Would appreciate double-checking this.  Many thanks!

**Comment by juan131** [comment]
Hi @darrenbarklie 

Are you setting the `PHP_ENABLE_OPCACHE`  environment variable during the 1st boot container or after the container has already being initialized and there's existing data? Please note that this setting gets ignored in case you're restarting the container.
