### ISSUE TITLE
ERROR ==> The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes

### ISSUE THREAD

**Issue by clinbioinfo** [bitnami/bitnami-docker-wordpress#121]
Hello folks,

Is the following tutorial still relevant?
https://www.howtoforge.com/tutorial/docker-how-to-use-it-in-a-practical-way-part-3/

**I get the following error:**

<pre>
docker run --name=mynotepad -p 80:80 -p 443:443 bitnami/wordpress

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com

ERROR ==> The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
</pre>

I find no solution here:
https://github.com/bitnami/bitnami-docker-wordpress/issues

**Docker info:**

<pre>
docker info
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 19
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.10.0-28-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.857GiB
Name: c3p0
ID: ID7G:ZMDK:2VKT:HCIN:6MMT:7PI5:Z7DV:JJL2:QOFU:PZ3T:MQQ4:3YBO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
</pre>

**My system:**

<pre>
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
</pre>

**Comment by juan131** [comment]
Hi @clinbioinfo that tutorial was not created by Bitnami so you'll need to contact the author.

Regarding the error you found, as you can check on the **README.md** (https://github.com/bitnami/bitnami-docker-wordpress#using-the-docker-command-line), you need to use the env. variable `ALLOW_EMPTY_PASSWORD` when not indicating the `MARIADB_ROOT_PASSWORD`.

You have more information about the env. variables available on the [Configuration section](https://github.com/bitnami/bitnami-docker-wordpress#configuration)
