### ISSUE TITLE
How can I install xdebug?

### ISSUE THREAD

**Issue by chrissound** [bitnami/bitnami-docker-wordpress#122]
I'm using the `bitnami/wordpress:4.7.2-r2` docker image...

**Comment by silviofdez** [comment]
Hi,

you can follow the following approach:

- Log to the container `docker exec -it ... bash`
- Install pear: `install_packages php-pear`
- Install xdebug: `pecl install xdebug`
- Enable xdebug: add `zend_extension="/usr/local/php/modules/xdebug.so" ` to the `php.ini` file

of course you can also add this to the Dockerfile or create a new one `FROM bitnami/wordpress`
