### ISSUE TITLE
Multisite on kubernetes ( GKE )

### ISSUE THREAD

**Issue by BrianAndersen78** [bitnami/bitnami-docker-wordpress#123]
I have deployed WP and MariaDB via helm with kubeapps, and now i would like to change install to multisite. I'm doing the usual routine, and changing wp-config in active container to tricker DB change. 

My problem is that i have to change wordpress-htaccess.conf and wp-content.php in the image. I have created a Dockerfile and use the bitnami/wordpress:latest image and added a simple COPY of the two modified files to my image, and updated yaml on kubernetes. So far all good.

When i boot up a container from the image, my wp-config.php file is correct in my container but nomatter what i try, i cant get the wordpress-htaccess.conf file to work.  

I have tried to copy the file to 
/opt/bitnami/apache/conf/vhosts/htaccess/
/bitnami/apache/conf/vhosts/htaccess/
and a gazillion other things, but when container start op, it seems like the file is manipulated by the bootprocess, so the text in the file is changed, and i can't find any documentation on how to change the file the rigth way.

I dont know if this is a bug, unexpected behavior, or simply just me doing it all wrong.

**Comment by BrianAndersen78** [comment]
Ok, i figured out why the file copy didn't work but it just gave me other problems...

It seems that the installation needs the PV and if i change the files there, it all works. 
I don't want to use a PV i need to be able to scale, so i need to be able to change the apache conf file, without a PV. Anyway to do that?

There is a seriosly problem with running this image at GKE. When a pod restarts, it doesn't free the PV, so the next pod can't mount it... See this error from "describe pod" 

Normal   Scheduled 17m default-scheduler  Successfully assigned default-wp-wordpress-5886b75556-qwzf5 to gke-cluster-3-default-pool-39782ca1-dznz
  
Normal   SuccessfulMountVolume  17m   kubelet, gke-cluster-3-default-pool-39782ca1-dznz  MountVolume.SetUp succeeded for volume "default-token-2bpkc"
  
Warning  FailedAttachVolume     17m (x20 over 17m)  attachdetach  Multi-Attach error for volume "pvc-2b0b8666-3466-11e8-968b-42010a9c003b" Volume is already exclusively attached to one node and can't be attached to another
  
Normal   SuccessfulMountVolume  17m  kubelet, gke-cluster-3-default-pool-39782ca1-dznz  MountVolume.SetUp succeeded for volume "pvc-2b0b8666-3466-11e8-968b-42010a9c003b"
  
Normal   Pulled   17m   kubelet, gke-cluster-3-default-pool-39782ca1-dznz  Container image "bitnami/wordpress:4.9.4-r5" already present on machine
  
Normal   Created  17m  kubelet, gke-cluster-3-default-pool-39782ca1-dznz  Created container
  
Normal   Started 17m kubelet, gke-cluster-3-default-pool-39782ca1-dznz  Started container
  
Warning  Unhealthy 14m (x5 over 14m)   kubelet, gke-cluster-3-default-pool-39782ca1-dznz  Liveness probe failed: Get http://wp4b.dk/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  
Warning  Unhealthy 2m (x72 over 16m)   kubelet, gke-cluster-3-default-pool-39782ca1-dznz  Readiness probe failed: Get http://wp4b.dk/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by juan131** [comment]
Hi @BrianAndersen78 

I think we should continue with this discussion about the Helm Chart configuration and the problems with Persistent Volumes on the Charts repo. Could you please create an issue on that repo describing the problem?

https://github.com/kubernetes/charts

I proceed to close this issue.

**Comment by marcosbc** [comment]
Hi, FYI Multisite support was just added in [`5.7.1-debian-10-r21`](https://github.com/bitnami/bitnami-docker-wordpress#571-debian-10-r21). Please check [Multisite configuration](https://github.com/bitnami/bitnami-docker-wordpress#multisite-configuration) for more info.
