### ISSUE TITLE
WP-CLI missing

### ISSUE THREAD

**Issue by mans0954** [bitnami/bitnami-docker-wordpress#124]
As far as I can see, WP-CLI (i.e. `bin/wp`) is missing from the WordPress nami package and hence from the Docker image. Yet it is included in the Bitnami WordPress Installer and Virtual Machine.

WP-CLI would be useful for scripting customisations (e.g. installing and activating WordPress Themes and Plugins) either in images based upon bitnami/wordpress, or within an init-container.

Please would it be possible to consider either adding it to the bitnami/wordpress image, or providing a companion image with WP-CLI for  init-containers?

Thanks.

Christopher Hoskin

**Comment by juan131** [comment]
Hi @mans0954 

As you mentioned, the **wp-cli** utility is not included on this Docker Image. I also think it can be useful for certain operations. @jotamartos what do you think? Could you we include it on the image?

@tompizmor is there any special reason why it's not included?

It seems we provided instructions to install it in the past: https://github.com/bitnami/bitnami-docker-wordpress/issues/106

**Comment by kyzma84** [comment]
Hello 
I tried this instruction but get problem with wp in bitnami container 
`daemon@testuser-wordpress-7dbb98557-qzh68:/$ wp pligins list --path=/opt/bitnami/wordpress/ --debug
Debug (bootstrap): No readable global config found (0.094s)
Debug (bootstrap): No project config found (0.095s)
Debug (bootstrap): argv: /usr/local/bin/wp pligins list --path=/opt/bitnami/wordpress/ --debug (0.095s)
Debug (bootstrap): ABSPATH defined: /opt/bitnami/wordpress/ (0.095s)
Debug (bootstrap): Begin WordPress load (0.096s)
Debug (bootstrap): wp-config.php path: /bitnami/wordpress/wp-config.php (0.096s)
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 85
PHP Notice:  Undefined index: HTTP_HOST in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 86
PHP Fatal error:  Uncaught Error: Call to undefined function add_filter() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code:102
Stack trace:
#0 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138): eval()
#1 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1100): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(8): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(1138) : eval()'d code on line 102
daemon@testuser-wordpress-7dbb98557-qzh68:/$`

`daemon@testuser-wordpress-7dbb98557-qzh68:/$ wp --info
OS:     Linux 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64
Shell:  /bin/bash
PHP binary:     /opt/bitnami/php/bin/php
PHP version:    7.0.29
php.ini used:   /opt/bitnami/php/lib/php.ini
WP-CLI root dir:        phar://wp-cli.phar
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 1.5.1
daemon@testuser-wordpress-7dbb98557-qzh68:/$`

Maybe i miss something. Could you , please ,help find the way to use wp with bitnami

**Comment by juan131** [comment]
Could you try editing your **/opt/bitnami/wordpress/wp-config.php** so the end of the file looks like the one below?

```
if ( !defined( 'WP_CLI' ) ) {
    // remove x-pingback HTTP header
    add_filter("wp_headers", function($headers) {
        unset($headers["X-Pingback"]);
        return $headers;
    });
    // disable pingbacks
    add_filter( "xmlrpc_methods", function( $methods ) {
        unset( $methods["pingback.ping"] );
        return $methods;
    });
}

if ( defined( 'WP_CLI' ) ) {
     $_SERVER['HTTP_HOST'] = 'localhost';
}
```

That should fix the issue

**Comment by kyzma84** [comment]
Thank you a lot . It's help
But i should rebuild container now

**Comment by juan131** [comment]
Hi @kyzma84 I'm glad it helped you! By default the **wp-config.php** is included in the persisted directory. Therefore, once you edit it, you configuration should be working after rebuilding the container (more info at https://github.com/bitnami/bitnami-docker-wordpress#persisting-your-application)

**Comment by AaronSeibert** [comment]
Has there been any further discussion about including wp-cli in the image? This would be great for a post-install "install a few standard plugins" process as well as all the other benefits of using wp-cli

**Comment by andresbono** [comment]
Hi @AaronSeibert, we are not including `wp-cli` in our container images by default. Based on your feedback and as it looks like an interesting component to support, we are going to evaluate it.

In case it is helpful for you, did you check the #106? There are instructions there to install it on your own.

We will keep this issue open until we have any news.

-Andrés B.

**Comment by andresbono** [comment]
Hi all,

With the latest release of WordPress contaienr we included wp-cli tool :tada: Feel free to start using it and giving us feedback!

I'm closing this issue as the feature request is now included.
