### ISSUE TITLE
must run as root user

### ISSUE THREAD

**Issue by mhrivnak** [bitnami/bitnami-docker-wordpress#126]
**Description**

The image will not run except as the root user. This is highly undesirable from a security perspective.

**Steps to reproduce the issue:**
I reproduced this on OpenShift 3.9 using the stable helm chart and an external database.

1. helm template --name somename -f path/to/values.yaml path/to/chart.tgz > manifest.yml
2. kubectl create -n somenamespace -f manifest.yml

**Describe the results you received:**

The pod would crash quickly with the following message in the log:

```
nami    ERROR Cannot find any module matching the provided specification 'apache'
```

**Describe the results you expected:**

The pod should happily run as non-root.

**Additional information you deem important (e.g. issue happens only occasionally):**

I am able to run it without crashes by adding the `anyuid` security context constraint.

```
oc adm policy add-scc-to-user anyuid -z default
```

In this case, the container runs as root, as seen in this shell session:

```
$ oc exec -it bundle-f1b235a9-wordpress-c7df66957-hptt9 bash
root@bundle-f1b235a9-wordpress-c7df66957-hptt9:/# whoami
root
root@bundle-f1b235a9-wordpress-c7df66957-hptt9:/# ps -Af
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 14:37 ?        00:00:00 tini -- nami start --foreground apache
root        96     1  0 14:38 ?        00:00:01 /opt/bitnami/nami/runtime/node --max_semi_space_size=150 /opt/bitnami/nami/index.js start --foreground apache
root       108     1  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     109   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     110   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     111   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     112   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     113   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     115   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
daemon     122   108  0 14:38 ?        00:00:00 /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf
root       133     0  0 14:41 ?        00:00:00 bash
root       140   133  0 14:41 ?        00:00:00 ps -Af
```

**Version**

- Output of `docker version`:

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-51.git4032bd5.fc27.x86_64
 Go version:      go1.9.4
 Git commit:      7f1fa5c-unsupported
 Built:           Wed Mar 28 13:58:10 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-51.git4032bd5.fc27.x86_64
 Go version:      go1.9.4
 Git commit:      7f1fa5c-unsupported
 Built:           Wed Mar 28 13:58:10 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

- Output of `docker info`:

```
$ docker info
Containers: 229
 Running: 22
 Paused: 0
 Stopped: 207
Images: 2166
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version: 7f1fa5ca88477e7fadca4fe984da2ae3d2208aad (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 7f1fa5ca88477e7fadca4fe984da2ae3d2208aad-dirty (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.15.14-300.fc27.x86_64
Operating System: Fedora 27 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 11.43 GiB
Name: dhcp129-40.rdu.redhat.com
ID: 672G:G3GP:AOOG:6VF7:XXBS:RX3U:PLHB:2XNU:6WF2:TRD3:CDSL:WLOJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mhrivnak
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure), registry.fedoraproject.org (secure), registry.access.redhat.com (secure), docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenShift 3.9 on bare metal.

**Comment by javsalgar** [comment]
Hi,

I am currently working on a non-root version of the Bitnami WordPress container. I cannot give an ETA but will let you know as soon as I have any news about it.

**Comment by djzager** [comment]
@javsalgar I was hoping to make a non-root version of the mongodb container. Following redis as an example I made the changes you can see [here](https://github.com/bitnami/bitnami-docker-mongodb/issues/75#issuecomment-380791051). Not sure there is a means for me to contribute this enhancement. If there is a way, I'm hoping you could point me in the right direction :sunglasses:

**Comment by javsalgar** [comment]
@djzager I responded you in the other ticket ;) Thanks for collaborating

**Comment by beltran-rubo** [comment]
We released a first cut at https://github.com/bitnami/bitnami-docker-wordpress/tree/master/4/rhel-7

**Comment by boboldehampsink** [comment]
I'm seeing the same problem in https://github.com/bitnami/bitnami-docker-prestashop - can you fix it there too?

**Comment by javsalgar** [comment]
Hi, 

It is in our roadmap but I cannot give an ETA. I'm closing this issue, could you create a similar one in bitnami-docker-prestashop? Thanks

**Comment by shwetkprabhat** [comment]
@javsalgar was this ever resolved...

**Comment by javsalgar** [comment]
It was when we had the RHEL version of the WordPress containers. However, as we removed all of the RHEL containers, this issues should be reopened. We will update the ticket when we work on this, however, I'm afraid it may not be in the short term.

**Comment by shwetkprabhat** [comment]
Understood, wordpress being the most used cms and most targated as well, running container as root for public facing site should be a serious security concern...

**Comment by javsalgar** [comment]
Hi,

Just a clarification. Despite the container is being run as root, none of the processes inside the container are being run as root. In root containers, we create non-root users that run these processes (in the case of WordPress, all processes are run by the `daemon` user)

**Comment by shwetkprabhat** [comment]
I don't believe thats accurate but could be wrong, the container is not able to nfs storage class without root permissions...I just tired official wordpress docker container and it works fine, maybe you want to use it till you fix the root user issue. I am using bitnami/mariadb with library/wordpress

**Comment by javsalgar** [comment]
I think I didn't fully understand what you meant. Our container initializes as root (but then spawns the WordPress processes as non-root), so it should be able to change the permissions of the storage it is trying to write. Which is the exact issue you found?

**Comment by shwetkprabhat** [comment]
Looks like while starting the container, its trying to check/fix permissions of certain folders, I am using nfs storage class which dynamically provisions the persistent volume with k8s user permissions, so the container is not able to start unless I change the nfs share to root.

**Comment by javsalgar** [comment]
Because, from what I see, that nfs volume would not allow a `root` user to write or change permissions, right?

**Comment by shwetkprabhat** [comment]
Thats exactly the issue.

**Comment by javsalgar** [comment]
Ok, so once we move it to non-root, then no change of ownership would be necessary. Thanks for explaining :)

**Comment by emiioan** [comment]
I subscribe to this also. I'm trying to deploy you image in AWS from ECR public registry using ECS Fargate with EFS as shared storage for /bitnami/wordpress data volume. Since you changed to start with non-root user 1001, at startup the containers fails with permission denied because user 1001 doesn't probably have mount permissions. 

I switched to a older version of your build, bitnami/wordpress:5.3.2-debian-10-r30 and since here you start the container with root user, all works fine. Now, looking at rest of the closed issues, I notices only workarounds for Helm chart making use of security context and side container solution, but it my case, ECS is a AWS managed service, where I can provide just the image and there is no other possibility to start as root. 

The alternative would be to maintain my own image in private registry but I would really don't want to do that. Using that 5.3.2 version is to old also and having issues installing some of the wordpress plugins. Is there any other solution/workaround for this problem? Can we have a release with root user for latest WP version?

**Comment by airmonitor** [comment]
"WORDPRESS_RESET_DATA_PERMISSIONS": "yes" do the trick for me in AWS with EFS

**Comment by emiioan** [comment]
@airmonitor, thanks for reply, just added "WORDPRESS_RESET_DATA_PERMISSIONS": "yes" to env variables but same issue.

**Comment by airmonitor** [comment]
I forgot to add that you need to use access points in AWS EFS with below permissions

`{
    "AccessPoints": [
        {
            "ClientToken": "SharedFSAccessPoint279B0BF6-EU4K0tQndXVb",
            "FileSystemId": "fs-d087da88",
            "PosixUser": {
                "Uid": 1001,
                "Gid": 0,
                "SecondaryGids": []
            },
            "RootDirectory": {
                "Path": "/user",
                "CreationInfo": {
                    "OwnerUid": 1001,
                    "OwnerGid": 0,
                    "Permissions": "0755"
                }
            },
            "LifeCycleState": "available"
        }
    ]
}
`

**Comment by emiioan** [comment]
@airmonitor, it worked with efs access point! You can't imagine how grateful I am, thank you so much for your time and help! 
I will leave here the configuration made for ECS Fargate maybe it will help someone. I'm provisioning the setup using Pulumi so I will leave here typescript code with the EFS configuration and ECS task definition configuration:

```
// EFS AccessPoint
    const efs_accesspoint = new aws.efs.AccessPoint("wordpressefs", {
        fileSystemId: efs_wordpress.id,
        posixUser: {
            uid: 1001,
            gid: 0
        },
        rootDirectory: {
            path: "/user",
            creationInfo: {
                ownerUid: 1001,
                ownerGid: 0,
                permissions: "0775"
            }
        },
        tags: {
            "Name": "wordpress"
        }
    }) 
```

```
// ECS Fargate task definition

const ecs_task_definition = new awsx.ecs.FargateTaskDefinition("wordpress", {
        cpu: "2048",
        memory: "4096",
        taskRole: fargateRole,
        family: "wordpress",
        container: {
            image: "public.ecr.aws/bitnami/wordpress:latest",
            portMappings: [{
                containerPort: 8080,
                hostPort: 8080,
                protocol: "tcp"
            }],
            environment: [
                {
                    "name": "MARIADB_HOST",
                    "value": AuroraRDS.endpoint
                },
                {
                    "name": "MARIADB_ROOT_PASSWORD",
                    "value": "aaaaaa"
                },
                {
                    "name": "MARIADB_ROOT_USER",
                    "value": "aaaaaa"
                },
                {
                    "name": "MYSQL_CLIENT_CREATE_DATABASE_NAME",
                    "value": "aaaaaa"
                },
                {
                    "name": "MYSQL_CLIENT_CREATE_DATABASE_PASSWORD",
                    "value": "aaaaaa"
                },
                {
                    "name": "MYSQL_CLIENT_CREATE_DATABASE_USER",
                    "value": "aaaaaa"
                },
                {
                    "name": "WORDPRESS_DATABASE_NAME",
                    "value": "aaaaaa"
                },
                {
                    "name": "WORDPRESS_DATABASE_PASSWORD",
                    "value": "aaaaaa"
                },
                {
                    "name": "WORDPRESS_DATABASE_USER",
                    "value": "aaaaaa"
                },
                {
                    "name": "WORDPRESS_RESET_DATA_PERMISSIONS",
                    "value": "yes"
                }
            ],
            mountPoints: [{
                containerPath: "/bitnami/wordpress",
                sourceVolume: "efswordpress"
            }]
        },
        volumes: [{
            name: "efswordpress",
            efsVolumeConfiguration: {
                fileSystemId: efs_wordpress.id,
                rootDirectory: "/user",
                authorizationConfig: {
                    accessPointId: efs_accesspoint.id,
                    iam: "ENABLED"
                },
                transitEncryption: "ENABLED"
            },
        }]
    }, { dependsOn: ecsCluster });

```

**Comment by dani8art** [comment]
Hi! Thanks for the feedback and the solution to this problem! Great to hear that worked! 

Please, don't hesitate to contact us if you find any other issues!

**Comment by marcosbc** [comment]
Closing as non-root support was added some time ago in [`5.3.2-debian-10-r30`](https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30)
