### ISSUE TITLE
Issue With OpenShift

### ISSUE THREAD

**Issue by mattfarina** [bitnami/bitnami-docker-wordpress#127]
**Description**

When I tried to install the wordpress chart, which I think uses the image here, in openshift origin 3.9 I got an error that reads:

```
nami    ERROR Cannot find any module matching the provided specification 'apache'
```

**Steps to reproduce the issue:**

1. Setup openshift 3.9 (I used minishift)
2. Use `helm install stable/wordpress` to start it up
3. Read the logs to the wordpress pod that didn't come up properly

**Comment by prydonius** [comment]
Did some digging on this one and the non-root support is in the works but not yet supported. Some changes need to happen in the Dockerfile for that to work (and I expect they will happen in the coming days).

The cryptic error you're getting is because the nami tool doesn't have permission to look into the package state because it's running as a non-root user but the packages were installed as root.

cc @javsalgar who's working on the non-root updates for this.

**Comment by javsalgar** [comment]
We still have some concerns in fully converting bitnami-docker-wordpress to non-root. We are discussing the best approach to do so. Once we have more information, I will update this ticket.

**Comment by beltran-rubo** [comment]
We published a first cut at https://github.com/bitnami/bitnami-docker-wordpress/tree/master/4/rhel-7

**Comment by akarasev** [comment]
@prydonius @javsalgar do you have any update for the issue?

What directories should have non-root access (perhaps I'll be able to chown them by myself)?

**Comment by Quentin-M** [comment]
Hi,

Following up on this issue, is there any way currently to get a non-root container that's not RHEL (as this image is not published publicly)?

**Comment by Quentin-M** [comment]
Hi @javsalgar,

Following up on this issue, is there any way currently to get a non-root container that's not RHEL (as this image is not published publicly)?

> We still have some concerns in fully converting bitnami-docker-wordpress to non-root. We are discussing the best approach to do so. Once we have more information, I will update this ticket.

What are the concerns exactly? Both RHEL and Debian images look quite similar to me, besides the `run.sh` script, ports and `ENV BITNAMI_PKG_CHMOD, BITNAMI_PKG_EXTRA_DIRS`

Running Wordpress (or any PHP code for that matter) as root in Kubernetes is a massive security concern. [Userns](https://github.com/kubernetes/features/issues/127) is not implemented on Kubernetes, and won't be for several other months, which means that any root containers technically have root access on the hosts themselves. Escapes are frequent and easy to find.

**Comment by sdodsley** [comment]
Any ETA on the non-root version of the container. 
I like to use WP as a cool demo of the portability of apps across native kubernetes and OpenShift, but that isn't possible now without hacking - which is not what we are trying to show

**Comment by juan131** [comment]
Hi @sdodsley 

There are no immediate plans to work on it. Nevertheless, it will be considered for future container versions.

In the meantime you can create you own non-root version for WP Debian.

 - Apply this patch:

```
diff --git a/4/debian-9/Dockerfile b/4/debian-9/Dockerfile
index 9e41886..6ddbba6 100644
--- a/4/debian-9/Dockerfile
+++ b/4/debian-9/Dockerfile
@@ -1,6 +1,10 @@
 FROM bitnami/minideb-extras:stretch-r116
 LABEL maintainer "Bitnami <containers@bitnami.com>"

+ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
+    BITNAMI_PKG_EXTRA_DIRS="/bitnami/apache/conf /opt/bitnami/apache/tmp /opt/bitnami/apache/conf" \
+    HOME="/"
+
 # Install required system packages and dependencies
 RUN install_packages libbz2-1.0 libc6 libcomerr2 libcurl3 libexpat1 libffi6 libfreetype6 libgcc1 libgcrypt20 libgmp10 libgnutls30 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu57 libidn11 libidn2-0 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblzma5 libmcrypt4 libncurses5 libnettle6 libnghttp2-14 libp11-kit0 libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.0.2 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5 libtinfo5 libunistring0 libxml2 libxslt1.1 zlib1g
 RUN bitnami-pkg unpack apache-2.4.34-1 --checksum 35ab4cfd39577d1e7c5f6ef815ff27940add60ba498f7db7e558085de57b9ee3
@@ -11,8 +15,8 @@ RUN bitnami-pkg unpack wordpress-4.9.8-1 --checksum dd981c299d076a1f7208100fc08f

 COPY rootfs /
 ENV ALLOW_EMPTY_PASSWORD="no" \
-    APACHE_HTTPS_PORT_NUMBER="443" \
-    APACHE_HTTP_PORT_NUMBER="80" \
+    APACHE_HTTPS_PORT_NUMBER="8443" \
+    APACHE_HTTP_PORT_NUMBER="8080" \
     BITNAMI_APP_NAME="wordpress" \
     BITNAMI_IMAGE_VERSION="4.9.8-debian-9-r13" \
     MARIADB_HOST="mariadb" \
@@ -37,14 +41,15 @@ ENV ALLOW_EMPTY_PASSWORD="no" \
     WORDPRESS_EMAIL="user@example.com" \
     WORDPRESS_FIRST_NAME="FirstName" \
     WORDPRESS_HOST="" \
-    WORDPRESS_HTTPS_PORT="443" \
-    WORDPRESS_HTTP_PORT="80" \
+    WORDPRESS_HTTPS_PORT="8443" \
+    WORDPRESS_HTTP_PORT="8080" \
     WORDPRESS_LAST_NAME="LastName" \
     WORDPRESS_PASSWORD="bitnami" \
     WORDPRESS_TABLE_PREFIX="wp_" \
     WORDPRESS_USERNAME="user"

-EXPOSE 80 443
+EXPOSE 8080 8443

+USER 1001
 ENTRYPOINT [ "/app-entrypoint.sh" ]
-CMD [ "nami", "start", "--foreground", "apache" ]
+CMD ["/run.sh"]
diff --git a/4/debian-9/docker-compose.yml b/4/debian-9/docker-compose.yml
index 0a9d231..a7140e3 100644
--- a/4/debian-9/docker-compose.yml
+++ b/4/debian-9/docker-compose.yml
@@ -11,8 +11,8 @@ services:
   wordpress:
     image: 'bitnami/wordpress:4'
     ports:
-      - '80:80'
-      - '443:443'
+      - '80:8080'
+      - '443:8443'
     volumes:
       - 'wordpress_data:/bitnami'
     depends_on:
diff --git a/4/debian-9/rootfs/app-entrypoint.sh b/4/debian-9/rootfs/app-entrypoint.sh
index d38318e..bea4606 100755
--- a/4/debian-9/rootfs/app-entrypoint.sh
+++ b/4/debian-9/rootfs/app-entrypoint.sh
@@ -5,7 +5,7 @@

 print_welcome_page

-if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
+if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/run.sh" ]]; then
   . /init.sh
   nami_initialize apache php mysql-client wordpress
   info "Starting wordpress... "
diff --git a/4/debian-9/rootfs/run.sh b/4/debian-9/rootfs/run.sh
new file mode 100755
index 0000000..d701dfe
--- /dev/null
+++ b/4/debian-9/rootfs/run.sh
@@ -0,0 +1,10 @@
+#!/bin/bash
+. /opt/bitnami/base/functions
+. /opt/bitnami/base/helpers
+
+DAEMON=httpd
+EXEC=$(which $DAEMON)
+ARGS="-f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND"
+
+info "Starting ${DAEMON}..."
+exec ${EXEC} ${ARGS}
```

 - Build your own non-root version for WP Debian

```
cd 4/debian-9/
docker build . -t bitnami/wordpress:4
docker-compose up -d
```

We will update this issue as soon as we have more news.

**Comment by marcosbc** [comment]
Closing as non-root support was added some time ago in [`5.3.2-debian-10-r30`](https://github.com/bitnami/bitnami-docker-wordpress#532-debian-10-r30)
