### ISSUE TITLE
Apache mod_expires mod_ext_filter

### ISSUE THREAD

**Issue by sahin** [bitnami/bitnami-docker-wordpress#130]
A lot of wordpress sites that are using bitnami also install W3 Total Cache or other caching plugins.

It will be super great to enable mod_expires and mod_ext_filter to bitnami docker which is pretty basic needed 2 mods for apache.

**Comment by juan131** [comment]
Hi @sahin 

As you can check both modules are included on the Docker Image:

```
ls /opt/bitnami/apache/modules/mod_expires.so
ls /opt/bitnami/apache/modules/mod_ext_filter.so
```

Therefore, you can simply enable them by uncommenting the lines on the **/opt/bitnami/apache/conf/httpd.conf** and restarting Apache:

```
sed -i -e 's/#LoadModule expires_module/LoadModule expires_module/g' /opt/bitnami/apache/conf/httpd.conf
sed -i -e 's/#LoadModule ext_filter_module/LoadModule ext_filter_module/g' /opt/bitnami/apache/conf/httpd.conf
nami restart apache
```

**Comment by sahin** [comment]
thx
