### ISSUE TITLE
memory_limit setting

### ISSUE THREAD

**Issue by sahin** [bitnami/bitnami-docker-wordpress#131]
We love this bitnami docker. and use it a lot.

I am not sure how many people need to upgrade memory_limit to higher. nearly every wordpress site we have we need to upgrade. 

WordPress Memory Limit: 40M, memory_limit should be at least 96MB.   Increasing memory allocated to PHP.

This repo users are installing this docker mostly in their own servers so it might mean that they want a higher performance wordpress

It will be great to have a settings for docker to increase memory_limit

**Comment by juan131** [comment]
If you install the [WP php-info plugin](https://wordpress.org/plugins/wordpress-php-info) and activate it on your WP site. You'd notice that by default PHP `memory_limit` is set to 256M on this Docker Image. Could you please take a look?

**Comment by HDebeuf** [comment]
You can input your own php.ini file in order to edit the Memory limit. 
This on is located at `/opt/bitnami/php/conf/php.ini`

So, you create your own Dockerfile based on the bitnami/wordpress image and add a `COPY` from your own file pointing to `/opt/bitnami/php/conf/php.ini`.

**Comment by juan131** [comment]
As @HDebeuf mentioned you can overwrite the default **php.ini** and place your own one.

You could also modify the **entrypoint** so it's dynamically set using some kind of env. variable or flag.

**Comment by sahin** [comment]
this is for memory limit in the wordpress not in php

**Comment by juan131** [comment]
Hi @sahin 

In that case you can edit the **/bitnami/wordpress/wp-config.php** configuration file and set  **WP_MEMORY_LIMIT** with the appropriate value.

**Comment by hadifarnoud** [comment]
I think I have the same issue (running wordpress in k8s) with memory. I cannot upload files larger than 1MB.

there is no way to edit or use custom wp-config.php

**Comment by juan131** [comment]
> running wordpress in k8s

Are you using the Helm chart to run WordPress on K8s (https://github.com/helm/charts/blob/master/stable/wordpress)?

> there is no way to edit or use custom wp-config.php

You can edit it once you deployed WordPress but it's not the best approach for sure. As I see there's two ways to make it easier:

- A) We implement a way to append custom configuration to **wp-config.php**.
- B) We implement a specific env. variable to configure the **WP_MEMORY_LIMIT** setting.

@javsalgar @tompizmor what do you think? I guess we should support the "scenario A" sooner or later.

**Comment by hadifarnoud** [comment]
@juan131 

> Are you using the Helm chart to run WordPress on K8s
Yes, I do.

> You can edit it once you deployed WordPress but it's not the best approach for sure
that could be a good temp option for now. How would I do that?

I think option A is more powerful but less prone to errors. Having both options would be perfect as option B is an easier and cleaner way of handling more common issues.

**Comment by juan131** [comment]
@hadifarnoud B is cleaner but I think the list of current supported env. variables is growing too much. See: https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-9/rootfs/wordpress-inputs.json

I'd like to hear the opinion from @tompizmor and @javsalgar

**Comment by stefangweichinger** [comment]
Would someone be so kind to post a working example for a php.ini modification with a docker-compose.yml? 

I am trying to increase upload filesize as mentioned in 

https://help.servmask.com/2018/10/27/how-to-increase-maximum-upload-file-size-in-wordpress/

and have no success so far. thanks ...

**Comment by juan131** [comment]
Hi @stefangweichinger 

How did you solved it? 
Did you create a custom image? Are you manually editing the `wp-config.php` after deploying the solution?

**Comment by stefangweichinger** [comment]
I followed hint 4. on the mentioned URL (installed and used plugin).
Right now I have to add fonts to the container ... another issue, though ;-)

**Comment by juan131** [comment]
Hi @stefangweichinger 

> I followed hint 4. on the mentioned URL (installed and used plugin).

Oh great! I'm glad you solved it with the plugin.

> Right now I have to add fonts to the container ... another issue, though ;-)

Could you open a different issue for that? Just to avoid mixing different topics under the same thread.

**Comment by stefangweichinger** [comment]
> Could you open a different issue for that? Just to avoid mixing different topics under the same thread.

sure, will do

**Comment by polRk** [comment]
You use simple wp-config for all env variables and all defines

```php
foreach ($_ENV as $key => $value) {
	$capitalized = strtoupper($key);
	if (!defined($capitalized)) {
		define($capitalized, $value);
	}
}
```

**Comment by juan131** [comment]
Thanks for the tip @polRk !! It can be a good trip to support every config setting as env var.

**Comment by hadifarnoud** [comment]
would be awesome to have `WP_CACHE` in https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/wordpress-inputs.json too

there are so many popular config variables missing there

**Comment by juan131** [comment]
Hi @hadifarnoud 

Could you give a try using the **WORDPRESS_EXTRA_WP_CONFIG_CONTENT** environment variable? Whatever content you add on that environment variable will be appended to the **wp-config.php**.

**Comment by hadifarnoud** [comment]
Thanks, that’ll do

**Comment by AdnanHodzic** [comment]
@juan131 could you please provide an example on how we can use `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` to set `WP_MEMORY_LIMIT` when installing this chart by passing it as part of `--set extraEnvVars` parameter? 

As no matter which combination and option I go for it fails, thanks

**Comment by juan131** [comment]
Hi @AdnanHodzic 

I guess that you are referring to the [Bitnami WordPress chart](https://github.com/helm/charts/tree/master/stable/wordpress), rigth? Just in case other users that are not familiar with the chart read your answer and want to learn more about it.


Regarding your issue, I think you need to play with the `big_image_size_threshold` property to avoid the warning you're facing. More info at:

- https://developer.wordpress.org/reference/hooks/big_image_size_threshold/

**Comment by AdnanHodzic** [comment]
Hey @juan131 

> I guess that you are referring to the [Bitnami WordPress chart](https://github.com/helm/charts/tree/master/stable/wordpress), rigth? Just in case other users that are not familiar with the chart read your answer and want to learn more about it.

Yes, this is the chart I was referring to.

> Regarding your issue, I think you need to play with the `big_image_size_threshold` property to avoid the warning you're facing. More info at:
> 
> * https://developer.wordpress.org/reference/hooks/big_image_size_threshold/

Looks promising, is there any way to feed `add_filter( 'big_image_size_threshold', '__return_false' );` as part of Bitnami Wordpress chart parameters?

**Comment by juan131** [comment]
Hi @AdnanHodzic 

> Do you know what could be done to resolve this issue?

How big your image is? 

> Also, is there any way to pass add_filter( 'big_image_size_threshold', '__return_false' ); as part of Bitnami Wordpress chart parameters?

This is a very specific configuration parameter and we don't support to customize automatically any other file rather than the `wp-config.php` file.

I'm afraid that you'll have to manually apply this kind of changes. As a workaround, you can also use the `customPostInitScripts` parameter to include any custom shell script you want to execute after WordPress is initialized.

**Comment by AdnanHodzic** [comment]
> > Do you know what could be done to resolve this issue?
> 
> How big your image is?

4.3MB, 3840x1600. 

> This is a very specific configuration parameter and we don't support to customize automatically any other file rather than the `wp-config.php` file.
> 
> I'm afraid that you'll have to manually apply this kind of changes. As a workaround, you can also use the `customPostInitScripts` parameter to include any custom shell script you want to execute after WordPress is initialized.

Thanks, I'll look into it. First I want to make it work and then I'll evaluate all options on how to apply it automatically.

**Comment by juan131** [comment]
Hi @AdnanHodzic 

I was unable to reproduce the issue installing the chart using the values.yaml below, and uploading a 40MB (I used [this one](https://effigis.com/wp-content/uploads/2015/02/Airbus_Pleiades_50cm_8bit_RGB_Yogyakarta.jpg)) image to WP Media Library.


```
wordpressExtraConfigContent: |
  @ini_set( 'post_max_size', '128M');
  @ini_set( 'memory_limit', '256M' );
  @ini_set( 'max_execution_time', '300' );
  @ini_set( 'max_input_time', '300' );
  define( 'WP_MEMORY_LIMIT', '512M' );
```

Could you please specify (step by step) how to reproduce the issue through WP UI?

**Comment by AdnanHodzic** [comment]
@juan131, I fixed the problem by adding `nginx.ingress.kubernetes.io/proxy-body-size: 40m` to my ingress annotations section.

Now I can upload any size of image I want, thank you for your assistance, much appreciated! :beers:

**Comment by juan131** [comment]
That's great @AdnanHodzic 🎉  !! Thanks so much for sharing that solution, I'm sure it'll be also helpful for other users that configure the PHP settings properly in WordPress but they're exposing it through Ingress with the same result.

**Comment by marcosbc** [comment]
Hi all, we now support `PHP_MEMORY_LIMIT` environment variable. Refer to [PHP configuration](https://github.com/bitnami/bitnami-docker-wordpress#php-configuration) section in the README for more info.

**Comment by thanhtoan1196** [comment]
@marcosbc what about `WP Memory Limit`?

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/16433547/154838766-82d6858a-5edb-4b23-bda1-de93e1c50222.png">

**Comment by marcosbc** [comment]
Hi @thanhtoan1196, that is because of the `WP_MEMORY_LIMIT` option. You can set it to a different value in your wp-config.php file. You can check your current limit in Tools > Site Health > Info > WordPress Constants.

> NOTE: It must be set to a value in Megabytes. E.g. 1024M is a valid value but 1G may not work.
