### ISSUE TITLE
Need your help

### ISSUE THREAD

**Issue by beautyonly** [bitnami/bitnami-docker-wordpress#134]
HI Hello

I am very happy to have access to your wordpress docker container and I am very honored to be able to use it

But I have a few questions if your side can help me

1, the theme I can specify in the directory / 4 / Dockerfile configuration document using my pre-made templates and plug-ins,

2. Can I configure the TDK information for the site in the /4/Dockerfile configuration file? Such as: keywords
, description, etc.

3, I can configure the corresponding field in the /4/Dockerfile configuration and configure
Corresponding TDK information, such as: keywords, description

4, using your docker container can support the establishment of a large number of sites

thank

**Comment by juan131** [comment]
Hi @beautyonly 

I don't understand very well what are your concerns about the templates and plugins. Are you trying to migrate an already existing WP site to a WP running on Docker using this image?

As it's described on the (#configuration)[https://github.com/bitnami/bitnami-docker-wordpress#configuration] section of the README.md file, you can configure WP using env. variables on this Docker Image, please take a look to it.

> using your docker container can support the establishment of a large number of sites?

In order to use this Docker image on production, we recommend to run it on top of Kubernetes. This way you can have a system that allows to scale your site accordingly. You can find more information in the links below:

https://github.com/bitnami/charts/tree/master/upstreamed/wordpress
https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by beautyonly** [comment]
HI @juan131

It is a great honor to be able to talk to you

Yes, I tested the environment and I debugged a wp program because I used the wordpress program to build a lot of independent sites.

Because I have a very large number of domain names, more than 1,000 domain names

So I want to control the site's name, column, keyword, description, and other related information through configuration.

So I need to be able to quickly build a script, otherwise this is not a person's job, I hope to get your support and help.

As described in the (#Configuration)[https://github.com/bitnami/bitnami-docker-wordpress#configuration] section of the README.md file, you can configure WP using env. This Docker Image variable, OK I will read it carefully


In order to use this Docker image in production, we recommend running it on Kubernetes. This way you can have a system that allows you to expand your website accordingly. You can find more information at the following link:

Https://github.com/bitnami/charts/tree/master/upstreamed/wordpress
Https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

Is there a tutorial for me to refer to?

thank you very much

**Comment by juan131** [comment]
Hello @beautyonly 

> Because I have a very large number of domain names, more than 1,000 domain names
> So I want to control the site's name, column, keyword, description, and other related information through configuration.
>  So I need to be able to quickly build a script, otherwise this is not a person's job, I hope to get your support and help.

Please correct me if I'm wrong but you want to migrate already existing WP sites (more than 1000 sites) to containers using this Docker Image. 

To do so, you need to build a script that automates the process of creating a WP container and migrate a WP site to that container. Then you'll use that script to create a container per site so you migrate everything to a containerised environment.

Is that what you're looking for?

> Is there a tutorial for me to refer to?

Do you mean about how to create use WordPress containers on Kubernetes? Please find out the following docs that will be very useful for you:

https://docs.bitnami.com/kubernetes/get-started-kubernetes/
https://docs.bitnami.com/kubernetes/how-to/deploy-php-application-kubernetes-helm/
