### ISSUE TITLE
Kubernetes pod unable to run due to pid issue

### ISSUE THREAD

**Issue by tomerleib** [bitnami/bitnami-docker-wordpress#138]
**Description**
My K8S cluster had an unforseen issue which caused the cluster to be restarted. When I've checked the services, I could see that the only service which is failing to start is bitnami-wordpress.

**Describe the results you received:**

`nami    INFO  Initializing apache`
`apache  INFO  ==> Reconfiguring PID file location...`
`nami    INFO  apache successfully initialized`
`nami    INFO  Initializing php`
`nami    INFO  php successfully initialized`
`nami    INFO  Initializing mysql-client`
`nami    INFO  mysql-client successfully initialized`
`nami    INFO  Initializing wordpress`
`wordpre INFO  WordPress has been already initialized, restoring...`
`mysql-c INFO  Trying to connect to MySQL server`
`mysql-c INFO  Found MySQL server listening at ignoble-crocodile-mariadb:3306`
`mysql-c INFO  MySQL server listening and working at ignoble-crocodile-mariadb:3306`
`wordpre INFO  Upgrading WordPress Database ...`
`wordpre INFO `
`wordpre INFO ########################################################################`
`wordpre INFO   Installation parameters for wordpress:`
`wordpre INFO     Persisted data and properties have been restored.`
`wordpre INFO     Any input specified will not take effect.`
`wordpre INFO   This installation requires no credentials.`
`wordpre INFO  ########################################################################`
`wordpre INFO `
`nami    INFO  wordpress successfully initialized`
`INFO  ==> Starting wordpress... `
`nami    ERROR Unable to start com.bitnami.apache: Cannot find pid file '/opt/bitnami/apache/tmp/httpd.pid'.`

**Describe the results you expected:**

Apache service will run

**Version**
Bitnami official helm chart
Docker image for bitnami wordpress tested 4.9.5, 4.9.6, 4.9.7
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS

**Comment by juan131** [comment]
Hi @tomerleib 

- Did you modify any of the parameters available on the Helm chart? For instance, did you enable persistence for WordPress or did you use an `emptyDir`?
- What version of the chart are you using?  
- Could you modify the WordPress deployment so you add the env. variable **NAMI_DEBUG** as described below? That will increase the logs so we can identify the issue.

```
    ...
    spec:
      containers:
      - env:
        - name: NAMI_DEBUG
          value: --log-level=trace8
      ...
```

**Comment by tomerleib** [comment]
Hi @juan131 ,
I'm using chart version 0.8.8 with persistence (EFS) for the three mountpoints:
* /bitnami/apache
* /bitnami/wordpress
* /bitnami/php

I was able to solve my issue and successfully start Apache only after I've removed the persistence of /bitnami/apache

**Comment by juan131** [comment]
Hi @tomerleib 

I'm glad you were able to solve the issue. I guess the there was a misconfiguration on Apache persisted configuration and, therefore, there was an error when starting it. When it complains about being unable to find the PID files means that the server could not be started for any reason.

I proceed to close this issue as solved. If you have any other questions, please do not hesitate to reopen it.
