### ISSUE TITLE
Can't specify MySQL SSL connection parameters

### ISSUE THREAD

**Issue by spinside** [bitnami/bitnami-docker-wordpress#141]
**Description**

It is not possible to specify the SSL connection parameters.
If a MySQL server requires a secure connection it is not possible to set the certificate and you will get an error:
```
ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.
```
**Steps to reproduce the issue:**

Run the docker image and specify a remote database that requires SSL

**Describe the results you received:**

```
 ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.
```

**Describe the results you expected:**

An option to specify the SSL parameters of MySQL and succesfully connect to a database

**Additional information you deem important (e.g. issue happens only occasionally):**

Container log:
```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
apache  INFO  ==> Reconfiguring PID file location...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at *redacted*:3306
mysql-c ERROR [canConnect] Connection with '*redacted*' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '*redacted*' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '*redacted*' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '*redacted*' user is unsuccessful
mysql-c ERROR [canConnect] Connection with '*redacted*' user is unsuccessful
Error executing 'postInstallation': Cannot connect to MySQL server:
MySQL command failed to run. Error:
 ERROR 9002 (28000): SSL connection is required. Please specify SSL options and retry.
```
**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Azure Kubernetes Service

Extra question: I would like to help with this issue but I can't find the code for Nami Wordpress. Where is it?

**Comment by javsalgar** [comment]
Hi,

This feature is not enabled by default (we believe that, with the rise of Kubernetes, this kind of configuration would make more sense outside the container). In any case, it is possible to mount your own my.cnf configuration file in `/opt/bitnami/mysql/conf`. There you could set the SSL settings (probably you may need to mount a SSL certificate as well).

**Comment by spinside** [comment]
Thank you for pointing me in the right direction. I added the following to the ```my.cnf``` file in ```/opt/bitnami/mysql/conf``` :
```
[mysql]
ssl=1
```
This works, the mysql connection check is now succesfull.
After that I had to edit my wp-config.php and needed to add the following flag to set-up a secure connection from Wordpress.
```
define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
```

Maybe this is something that could be added to the documentation?

**Comment by spinside** [comment]
Okay, everything works this if you have already setup Wordpress before. If you try rolling this out for a new deployment there is a problem. The ```wp-config.php ``` does not exist before the initialisation and I can't initialise because I can't connect to the database via Wordpress. Is it possible to let Wordpress use SSL for the database connection during initialisation?

**Comment by javsalgar** [comment]
Hi,

I'm not 100% sure, but what you could do is mounting your own wp-config.php in `/opt/bitnami/wordpress/wp-config.php`. Could you try that?

**Comment by spinside** [comment]
Hi,

Thank you for your answer. But I think I've come to a point that I need to customise/hack too much of the image to make use of it (for now). I've decided to build my own image. I will keep following the development of the Bitnami Wordpress image with interest but for now I don't see the added value as it is not transparent and customisable enough. 

If I where to make the change you suggested I believe the environment variables wont work anymore because I would need to hardcode them in to the wp-config.php that I would be mounting.

**Comment by dc232** [comment]
Hi, I'm having the same problem with the WordPress Kubernetes helm chart there doesn't seem to be any way to specify to use an SSL connection in values-production or values files, was wondering whats the best way forward?

**Comment by javsalgar** [comment]
Hi,

I believe that you could make it work like this:

  - First you would need to create a secret with the Database CA that you will use
  - Once you have it, you would need to add it to the deployment using the `extraVolumes` and `extraVolumeMounts` values.
  - Once this is configured, you would need to use the `extraEnv` value to set the `WORDPRESS_DATABASE_SSL_CA_FILE` variable pointing to the CA secret that you mounted using `extraVolumes` and `extraVolumeMounts`. 

Could you check if this works for you?
