### ISSUE TITLE
WordPress failed to start: Cannot define multiple Listeners on the same IP:port

### ISSUE THREAD

**Issue by dukedhx** [bitnami/bitnami-docker-wordpress#146]
**Description**

wordpress_1  | wordpre INFO 
wordpress_1  | nami    INFO  wordpress successfully initialized
wordpress_1  | INFO  ==> Starting wordpress... 
wordpress_1  | AH00526: Syntax error on line 25 of /opt/bitnami/apache/conf/bitnami/bitnami.conf:
wordpress_1  | Cannot define multiple Listeners on the same IP:port
showcase_wordpress_1 exited with code 1

**Steps to reproduce the issue:**

1. Start the service using default composer file from DockerHub
2. mariadb starts up fine
3. wordpress fails with error above

**Version**
Docker version 18.06.0-ce, build 0ffa825
Image Tags:
"bitnami/mariadb:latest"
"bitnami/wordpress:latest"

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Mac OSX 10.13

**Comment by andresbono** [comment]
Hi @dukedhx, we cannot reproduce the issue. To know which specific version of the Docker image you are using, could you execute the following command and paste the result here?

```bash
docker image inspect bitnami/wordpress --format '{{ .RepoDigests }}'
```

**Comment by dukedhx** [comment]
It’s 4.9.8-ol-7 but never mind just went on to use the official image and it worked well.
