### ISSUE TITLE
Maria DB Error

### ISSUE THREAD

**Issue by swiftini** [bitnami/bitnami-docker-wordpress#15]
installed using docker compose and Maria DB seems to have shut down due to the following error:

mariadb_1    | Error executing 'postInstallation': File '/opt/bitnami/mariadb/tmp/mysqld.pid' does not exists
testbitnamiwp_mariadb_1 exited with code 1

**Comment by sameersbn** [comment]
closing this issue since is was discussed at bitnami/bitnami-docker-mariadb#50
