### ISSUE TITLE
Pod scale error with already existing External Database

### ISSUE THREAD

**Issue by sudir** [bitnami/bitnami-docker-wordpress#154]
**Scaling pod wont re-connect to already existing external database**

**Deploy the bitnami/wordpress on k8s**

1. Use helm to deploy:
<pre>
helm install stable/wordpress \
    --set mariadb.enabled=false,externalDatabase.host=myexternalhost,externalDatabase.user=myuser,externalDatabase.password=mypassword,externalDatabase.database=mydatabase,externalDatabase.port=3306</pre>

2.Kill running pod to force scale

**What happens?**
The pod scales and recreates itself, watching logs on the pod shows that it attempts to re-populate and/or re-create certain columns in the wp_options table. Since using an external DB from already populated deployment, certain column fields already exist causing the pod to error out with the following exception:
<pre>
 ERROR 1062 (23000) at line 1: Duplicate entry 'mail_from' for key 'option_name'
</pre> 
This is happening at the time it starts populating smtp configuration data.

**What I think the fix should address?**
Currently as developed, the helms chart works for production ready, scalable instances; however, if you are using an external database it does not. The fix should address the container image and allow for the database creation of certain tables and/or columns to ignore creating values when values are already present to enable true scalability for external db users. This essentially would allow wordpress to scale in a pod that dies leaving an already functional external database up and running to re-connect to that same database and smoothly scale the front-end pod by ignoring values already populated thus persisting the installation.

**Comment by juan131** [comment]
Hi @sudir 

You need to use an NFS Volume provisioner with **RWX** volumes in order to replicate WP pods. In the issue below we discussed about the proper solution to do so:

https://github.com/bitnami/charts/issues/908

You can also find an interesting blog post describing this process in the link below:

https://engineering.bitnami.com/articles/scaling-wordpress-in-kubernetes.html

**Comment by sudir** [comment]
Thanks for the fast response; however, can you expound on this better? My pod “does” scale without any NFS and my issue isn’t a storage related one it’s a Image one related to Usjng an external DB. The issue is when it scales it tries to recreate database tables that are already created when using an external DB, how does adding an NFS or any storage related provisioner solve that when the only thing sitting in a pod/container are the static we files, should be plug and play to an external dB right?

**Comment by juan131** [comment]
> The issue is when it scales it tries to recreate database tables that are already created when using an external DB, how does adding an NFS or any storage related provisioner solve that when the only problem I’m having is DB related?

I'd try to explain the whole process.

When WordPress is initialised, it creates a flag in the directory `/bitnami/wordpress`, that flag indicate that it's been initialised. That directory is a **mountPoint** for volumes that are requested as **PVC**. 

When using **NFS** and **RWX** volumes, the directory is shared with other pods when scaling Wordpress. Therefore, when WordPress detects the flag, it considers itself already initialised and it skips the database population. 
If you don't use NFS, a new PV (which is empty) will be created and the 2nd pod doesn't recognise that WP has been initialised before.

Does it make sense?

**Comment by sudir** [comment]
Thank you for such an excellent explanation, this makes clear sense, Id still rewire this to not have creating a PVC as a dependency if it were my choice though, Wordpress can scale without a PVC/NFS volume and the logic should be there to accommodate it but I understand how this is constructed now.
Thanks again for such a professional way of handling this Juan, you can close this issue.

**Comment by juan131** [comment]
Hi @sudir 

I'm glad the explanation helped you! I proceed to closed the issue.
Please do not hesitate to reopen the issue if you require further assistance.
