### ISSUE TITLE
Feature request: option to choose Wordpress language

### ISSUE THREAD

**Issue by andrevtg** [bitnami/bitnami-docker-wordpress#156]
An option to choose WP language (as in a normal WP installation). It would be great from here (plain docker image) to the helm chart. :)

**Comment by javsalgar** [comment]
Hi,

Thanks for the suggestion! We will consider adding this feature in future releases. However, as it is not a critical feature, I am afraid we cannot guarantee an ETA. We will update this thread if we add the feature.

**Comment by marcosbc** [comment]
Hi all, we now support init scripts which you can mount to `/docker-entrypoint-init.d` and perform any post-installation actions. Refer to [`post-init.sh`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh) for more info.

In particular, you could use the `wp` CLI tool to change the language in an init script.
