### ISSUE TITLE
.

### ISSUE THREAD

**Issue by joseurbanogonzalez** [bitnami/bitnami-docker-wordpress#158]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment]
Hi @joseurbanogonzalez 

It seems you opened an empty issue. Could you please complete the required information?

**Comment by joseurbanogonzalez** [comment]
I'm sorry. It has been a mistake. I'm sorry for the incoveniences..
