### ISSUE TITLE
Move container to other machine

### ISSUE THREAD

**Issue by gabriIes** [bitnami/bitnami-docker-wordpress#159]
I have installed the image to docker, it works perfectly. The problem comes when I want to take this container to other machine. 
First I create  images from the two containers mariadb and wordpress with docker commit
Second I save the image to my usb memory with docker save
Third I take them to the new computer and I load them with docker load
But I can not run the wordpress, I have checked via bash in the new mariadb container and the wordpress database does not appear.
Does anybody know how to export and import my wordpress, it will allow me to work at home and at work with the same project.
Thanks

- Output of `docker version`:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.1
 Git commit:        e68fc7a
 Built:             Fri Jan 25 14:33:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       e68fc7a
  Built:            Thu Jan 24 10:49:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false

- Output of `docker info`:
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-45-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.749GiB
Name: profesor-H61H2-I3
ID: Z2MK:AZGF:CIB6:JYVP:XAML:EP47:WPGA:C3H2:VQSE:ICU5:NX5U:OZGA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

- Output of `docker-compose version` (if applicable):
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

I think that the correct process would be just moving the volumes from one machine to the other. I don't think that commiting a new image would work correctly with the persisitence. How are your volumes configured?

This should help:

https://docs.docker.com/v17.03/engine/tutorials/dockervolumes/#backup-restore-or-migrate-data-volumes

**Comment by gabriIes** [comment]
Thanks so much,  I'll try to move to volumes.
