### ISSUE TITLE
How do you set the password?

### ISSUE THREAD

**Issue by xermus** [bitnami/bitnami-docker-wordpress#161]
I don't know how to login into Wordpress.

When I use:

```
      - MARIADB_ROOT_PASSWORD=testpw
      - MARIADB_PASSWORD=testpw
      - WORDPRESS_DATABASE_PASSWORD=testpw
      - ALLOW_EMPTY_PASSWORD=no
```

in the "environment" section (docker-compose.yml) for BOTH mariadb and wordpress, I can never login to WordPress on the /wp-login.php page using the user "bn_wordpress" and "testpw".

What am I doing wrong?

PS: I have always cleared the mounted volumes before trying out things.

**Comment by rafariossaa** [comment]
Hi @xermus,
  Could you the parameters you have set with this [link](https://github.com/bitnami/bitnami-docker-wordpress#user-content-configuration) ?
  The parameter for the user and password are WORDPRESS_USERNAME and WORDPRESS_PASSWORD.

Best regards,
Rafael Rios Saavedra
