### ISSUE TITLE
SSL issue for wordpress site

### ISSUE THREAD

**Issue by sysdevopsCC** [bitnami/bitnami-docker-wordpress#162]
**Description**
Hello, 
We are trying to apply SSL for the WordPress site in kubernetes, but we are getting many errors for "mixed content".
It is working with IP address but not with site name.

**Steps to reproduce the issue:**

1.create yml file to deploy the wordpress by using docker image
yml file steps: 
> Install maria db
> install bitnami wordpress
> created persistent volume for DB

**Describe the results you received:**
Recieved mixed content error when we use sitename. But we got the workable site when we use IP. 
(Refer the attached images)

**Describe the results you expected:**
wordpress website with SSL applied.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have tried to fix this issue by using below steps
> 1. We have installed SSL plugin.
> 2. Installed find and replace plugin in the admin panel.
> 3. Edited WP-config.php file.

**Version**

> bitnami/wordpress:latest

- Output of `docker version`:
>  18.09.3, build 774a1f4

- Output of `docker info`:
> Containers: 25
>  Running: 20
>  Paused: 0
>  Stopped: 5
> Images: 6
> Server Version: 18.09.3
> Storage Driver: overlay2
>  Backing Filesystem: xfs
>  Supports d_type: true
>  Native Overlay Diff: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins:
>  Volume: local
>  Network: bridge host macvlan null overlay
>  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
> Swarm: inactive
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
> runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
> init version: fec3683
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 3.10.0-862.2.3.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 3.701GiB
> Name: wordpress-node
> ID: NITV:5RVF:3QMI:6UV2:QNRC:QON6:MYNZ:ZPU7:ZHL6:5IJT:ZXCN:4OPE
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Labels:
> Experimental: false
> Insecure Registries:
>  142.93.40.203:8086
>  127.0.0.0/8
> Live Restore Enabled: false
> Product License: Community Engine

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
![screenshot from 2019-03-06 20-32-08](https://user-images.githubusercontent.com/43531630/53890792-e4b1e000-404e-11e9-86c6-ce7ca1fd5a25.png)

![screenshot from 2019-03-06 20-19-47](https://user-images.githubusercontent.com/43531630/53890184-bb448480-404d-11e9-9cd0-5462f2093466.png)

**Comment by javsalgar** [comment]
Hi,

Have you tried using the WordPress Helm chart? Could you confirm that the issue also occurs there?

https://github.com/helm/charts/tree/master/stable/wordpress
