### ISSUE TITLE
Bitnami directory

### ISSUE THREAD

**Issue by firehawk12** [bitnami/bitnami-docker-wordpress#163]
I apologize if this is a rudimentary question, but I am trying to run trying to find the bitnami directory in order to run some of the basic scripts like these:
sudo /opt/bitnami/ctlscript.sh stop
or 
sudo /opt/bitnami/letsencrypt/scripts/generate-certificate.sh

Where would I find the directory?  My /opt only has a "containerd" directory.

Thank you.

Edit: or is there another way to do the let's encrypt process when using the docker image?  I haven't been able to find any documentation otherwise.

**Comment by tompizmor** [comment]
Hi @firehawk12,

The Wordpress docker image is different from the installer or single vms. The wordpress directory is `/opt/bitnami/wordpress` but you won't find any `ctlscript.sh` or `generate-certificate.sh` there.

> Edit: or is there another way to do the let's encrypt process when using the docker image? I haven't been able to find any documentation otherwise.

Right now there is no automated way to manage the let's encrypt process for the wordpress container.
