### ISSUE TITLE
# Re-generate all thumbnails that have IDs between 1000 and 2000. $ seq 1000 2000 | xargs wp media regenerate

### ISSUE THREAD

**Issue by dhavalk1807** [bitnami/bitnami-docker-wordpress#166]
# Re-generate all thumbnails that have IDs between 1000 and 2000. 
$ seq 1000 2000 | xargs wp media regenerate

Error : Error: 'seq' is not a registered wp command. See 'wp help' for available commands.

**Comment by andresbono** [comment]
Hi @dhavalk1807, it looks like you want to regenerate media images with ids from `1000` to `2000`. If so, you are using the correct command.

Can you tell us how are you executing it?

For example, if you open a shell in the container (with `docker exec ... bash`), you should be able to execute the following command:

```
seq 1000 2000 | xargs wp --allow-root media regenerate
```
