### ISSUE TITLE
Disable Bitnami from installing Wordpress plugins

### ISSUE THREAD

**Issue by brown-a2** [bitnami/bitnami-docker-wordpress#169]
**Description**

When using Helm with this Bitnami image, is it possible to disable or stop Bitnami from preinstalling it's Wordpress plugins?

**Describe the results you expected:**

I have built a custom image, I am using this Bitnami image as the base. I have my own plugins I install using Composer so I would prefer to have a clean install with no preinstalled plugins. 

How would I do this or is it possible?

**Comment by alemorcuq** [comment]
Hi @brown-a2,

You can safely remove all the files under `/opt/bitnami/wordpress/wp-content/plugins` safely. As an example, this `Dockerfile` provides a Wordpress image without plugins using Bitnami's as a base:

```docker

**Comment by brown-a2** [comment]
Hi Alejandro,

Thanks for your reply, worked perfectly. 

Best
Adam

**Comment by Franz333** [comment]
Hi,
Would be awsome to have an environment variable that allows/prevents the installation of those "default plugins".
In this way, we would not need to have a custom image with wp-cli commands in app-entrypoint.sh to remove them.
We could just use the default bitnami image and get started right away.

**Comment by alemorcuq** [comment]
Hi, @Franz333.

You can mount some scripts to the `/docker-entrypoint-init.d` directory and they will be executed during the first initialization of the container. This way, you can remove the plugins without the need to create a custom image. For example, you could mount a file like this:

```
$ cat remove-scripts.sh
echo "Removing WordPress plugins..."
rm -rf /opt/bitnami/wordpress/wp-content/plugins/*
```

And it will remove the plugins when deploying WordPress only for the first time.

**Comment by Franz333** [comment]
Hi @alemorcuq,
Thanks for your help.
I am already mounting a .sql script to be able to use a database dump and adding another mounted script to `/docker-entrypoint-init.d` creates an error: `ERROR: Duplicate mount points`

**Comment by alemorcuq** [comment]
You can put all your scripts in the same folder and mount the folder to `/docker-entrypoint-init.d`.

**Comment by Franz333** [comment]
I tried that.. my .sql is used but the script does not seem to be ran.. plugins are still there

**Comment by marcosbc** [comment]
Hi @Franz333, the logic for executing init scripts supports sub-folders, meaning you could mount your SQL scripts in one folder and SH scripts in another one.

Another thing to note is that **init scripts will only be executed once**, so if the SQL scripts were already executed, the SH scripts will not be run. Therefore you'd have to re-initialize. However, when you re-initialize (with empty volumes), you should see that all scripts are executed.
