### ISSUE TITLE
/opt/bitnami/apps is sporadically renamed to /opt/bitnami/apps.bak during startup

### ISSUE THREAD

**Issue by evgf** [bitnami/bitnami-docker-wordpress#17]
Hello everyone,

after upgrading to a new verson of the docker daemon (1.11.2), we started to sporadically experience the following issue during startup:
The /opt/bitnami/apps directory gets renamed to /opt/bitnami/apps.bak
In some situations, an empty  /opt/bitnami/apps directory is created.
Although we use exactly the same images, the problem appears in ~30% of all cases.

Can you give me any idea about the investigation direction?

Thank you in advance,

Evgeny

**Comment by prydonius** [comment]
@evgf sorry for the really late response, I think we missed this. Are you still seeing this issue?

**Comment by prydonius** [comment]
Closing this issue for now, @evgf feel free to reopen if you are still experiencing this issue.
