### ISSUE TITLE
 Incorrect message when SMTP_PROTOCOL not set 

### ISSUE THREAD

**Issue by ncsibra** [bitnami/bitnami-docker-wordpress#171]
When I specified the SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD env variables, during nami initialization I got this error:
`Error executing 'postInstallation': You should specify username, password, host, port for SMTP configuration`
All was set correctly, so I enabled NAMI_DEBUG and checked where it dies, it was the `/root/.nami/components/com.bitnami.wordpress/helpers.js` file, line 156, the problem is, that the code checks the smtpProtocol for emptiness too, not just the host, port username, password, but the error message does not mention the protocol, which is very misleading.
```js

$app.helpers.configureSMTP = function(databaseHandler) {
  const smtpProperties = [$app.smtpUser, $app.smtpPassword, $app.smtpHost, $app.smtpPort, $app.smtpProtocol];
  if (!smtpProperties.some(_.isEmpty)) {
    $app.info('Configuring SMTP...');
    databaseHandler.database(databaseHandler.connection.name).insert(`${$app.tablePrefix}options`, [
      [null, 'mail_from', $app.smtpUser, 'yes'],
      [null, 'mail_from_name', $app.smtpUsername, 'yes'],
      [null, 'mailer', 'smtp', 'yes'],
      [null, 'mail_set_return_path', '', 'yes'],
      [null, 'smtp_host', $app.smtpHost, 'yes'],
      [null, 'smtp_port', $app.smtpPort, 'yes'],
      [null, 'smtp_ssl', $app.smtpProtocol, 'yes'],
      [null, 'smtp_auth', 'true', 'yes'],
      [null, 'smtp_user', $app.smtpUser, 'yes'],
      [null, 'smtp_pass', $app.smtpPassword, 'yes'],
    ]);
    databaseHandler.database(databaseHandler.connection.name).set(
      `${$app.tablePrefix}options`,
      'option_value',
      php.execute('', '-r "echo(serialize([\'wp-mail-smtp/wp_mail_smtp.php\']));"'),
      {where: {option_name: 'active_plugins'}}
    );
  } else if (!smtpProperties.every(_.isEmpty)) {
    throw new Error('You should specify username, password, host, port for SMTP configuration');
  }
};
```

Probably it's not the right repository to create this issue, but I was unable to find where the nami package repository, issue tracker.

**Comment by andresbono** [comment]
Thanks for reporting this issue @ncsibra.

You are right, the message is misleading. We will fix it and we'll do a new release of the container.

Just to confirm with you, once you set the protocol, is everything working fine for you?

---

> Probably it's not the right repository to create this issue, but I was unable to find where the nami package repository, issue tracker.

It is fine to report the issue in this repository, we don't have the nami packages logic published on GitHub.

**Comment by ncsibra** [comment]
Yes, it worked correctly after setting the protocol.
Honestly I used the wordpress chart and that readme does not contain the "none" option for the protocol, so it was double misleading, but finally figured it out. :)

**Comment by andresbono** [comment]
Hi @ncsibra, we have updated the [README.md](https://github.com/helm/charts/pull/13644/files) of the chart and the message reported by the nami package.

We are closing the issue, but let us know if you have more feedback.

Thanks!
