### ISSUE TITLE
container keep crashing when using nfs volume

### ISSUE THREAD

**Issue by mkrierQape** [bitnami/bitnami-docker-wordpress#175]
**Description**

I'm on a Rancher environnement, i manage multiple host and multiple bitmani wordpress, all are configured with rancher-nfs driver for volumes.

i notice that when a wordpress is not deployed on the same host as his volume, apache in the wordpress container keep crashing ( sometime after 2 minutes, sometime after 20 minutes of uptime )

**Steps to reproduce the issue:**

1. Configure rancher-nfs plugin in rancher on Host "A"
2. Add wordpress stack with rancher catalog, with rancher-nfs driver 
3. Launch stack on host "B"
4. Wordpress container will keep crash 

**Describe the results you received:**

> [Fri May 17 14:51:43.932519 2019] [mpm_prefork:notice] [pid 120] AH00169: caught SIGTERM, shutting down

**Describe the results you expected:**

not crashing

**Additional information you deem important (e.g. issue happens only occasionally):**

it only crashing when volume is not on the same host, i have some wordpress where volume and container are on the same host, there is no problem

**Version**

- Output of `docker version`:

```
docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

All my servers are the same, Ubuntu  18 with docker 18 and Rancher 1.6.27

it is possible to have more logs on apache error ?

**Comment by miguelaeh** [comment]
Hi @mkrierQape ,
could you set the environment variable `NAMI_LOG_LEVEL=trace8` to increase the verbosity of logs?

**Comment by mkrierQape** [comment]
Hello, thx for you help

here is a full log from a restart container : https://pastebin.com/aWP3byfk

**Comment by miguelaeh** [comment]
It seems you did some request to the server before crashing, right?
Could you specify what did you do before the crash?
I think using Rancher should not affect to the container itself, could you check if the node is out of resources in the crash time?
