### ISSUE TITLE
Wordpress ERROR 2059 (HY000): Plugin caching_sha2_password could not be loaded: 

### ISSUE THREAD

**Issue by Air-Git** [bitnami/bitnami-docker-wordpress#177]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Air-Git** [comment]
I am using the Bitnami Azure Container Instance for Wordpress. When the Wordpress container starts, it fails with the above error. This is because the MySQL container uses the newer SHA2 password authentication, which the MySQL connector in the Wordpress container does not support.
The solution should be to: connect to the MySQL container; change the user account to use mysql_native_authentication. However, when I try that, I get an error.
Syntax to change the user account: ALTER USER 'bn_wordpress'@'localhost' IDENTIFIED WITH mysql_native_password.
Error: ERROR 1396 (HY000): Operation ALTER USER failed for 'bn_wordpress'@'localhost'.
Any ideas on the right way to do this?

**Comment by andresbono** [comment]
Hi @Air-Git, what is the specific version of the MySQL container that you are using? You can check it by executing:

```
docker exec -it YOUR_MYSQL_CONTAINER bash -c 'env | grep BITNAMI_IMAGE_VERSION'
```

With that information, we will try to reproduce the issue and give a solution to you.

**Comment by Air-Git** [comment]
I am using "latest": BITNAMI_IMAGE_VERSION=8.0.16-debian-9-r23

**Comment by Air-Git** [comment]
Changed the account.  Steps are:
1) Connect to the container using bash (from within the Azure portal). Highlight the container and, in the dialog box below, select Connect.
2) At the console, log on as Root, with "`mysql -u root -h localhost -p;`". Password is blank, just press Enter.
3) Enter the command: "`ALTER USER 'bn_wordpress'@'%' IDENTIFIED WITH mysql_native_password;`".
You can confirm the authentication method of the user account before and after with: "`select user, host, plugin, authentication_string from mysql.user;`"

Now the error is: MySQL command failed to run. Error: 
 ERROR 1862 (HY000): Your password has expired. To log in you must change it using a client that supports expired passwords.

Reset the user password with: `ALTER USER 'bn_wordpress'@'%' IDENTIFIED BY ''`;

And the Wordpress container is able to authenticate. Could probably do both those SQL commands in one:  `ALTER USER 'bn_wordpress'@'%' IDENTIFIED WITH mysql_native_password BY ''`;

Once you know what the solution is, it is fairly obvious if you have a syntax error.

**Comment by andresbono** [comment]
Hi @Air-Git, we where able to reproduce the issue, thanks for the detailed information.

We will work on a solution to this issue.

Thanks for reporting it!

**Comment by javsalgar** [comment]
Hi,

Please check this comment

https://github.com/bitnami/bitnami-docker-wordpress/issues/214#issuecomment-588172399

**Comment by marcosbc** [comment]
Closing this issue as it is not happening in new versions anymore.
