### ISSUE TITLE
Feature request: Add libapache2-mod-rpaf support

### ISSUE THREAD

**Issue by benhus** [bitnami/bitnami-docker-wordpress#178]
I am running the container behind a nginx proxy and Apache is not picking up the forwarded IP headers to show the original caller IP address.

Details about this you can find in this article:
https://www.daveperrett.com/articles/2009/08/10/passing-ips-to-apache-with-nginx-proxy/

1. Install jwilder/nginx-proxy:latest
2. Add vhost with redirect rule:
proxy_pass http://bitnami-wordpress:80;
proxy_pass_request_headers      on;

3. access the wordpress site and see the logfiles:
172.27.0.3 - - [12/Jun/2019:05:28:16 +0000] "GET /wp-login.php HTTP/1.1" 200 1312

**Describe the results you received:**

Local IP address is used:
172.27.0.3 - - [12/Jun/2019:05:28:16 +0000] "GET /wp-login.php HTTP/1.1" 200 1312

**Describe the results you expected:**

IP address from the original caller 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-51-generic
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.82GiB
Name: tqg-prod-01
ID: WH3R:7FGE:EZ5Y:APEQ:IIEL:B4UT:4ZXC:4G2S:EXQL:3BFG:HX7S:VPAH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.0g  2 Nov 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by benhus** [comment]
Hi guys,

I have just checked that you can manage to use also the remoteip module which is already provided with you package.

So it would be great if you can provide a parameter option to enable that feature.

The code I have added to make it work is in enabling the module by removing the comment tag:
LoadModule remoteip_module modules/mod_remoteip.so
and adding the configuration:
<IfModule remoteip_module>
  RemoteIPHeader X-Forwarded-For
  RemoteIPTrustedProxy 127.0.0.1
</IfModule>

would be great if you can have this added.

Thank you in advance
Kind regards,
Ben

**Comment by andresbono** [comment]
Hi @benhus,

Thanks for submitting this issue. We will revisit the Apache configuration behind a proxy and we will check if we can include some improvements.

In the meantime, your solution is working as expected, right?

**Comment by benhus** [comment]
Hi @andresbono,

yes in the meantime the solution is working. It's just a bit annoying to redo this tasks for every update of the image and every new instance I am creating. Do have an idea when a fix might be ready?

Thank you in advance
Kind regards,
Ben

**Comment by andresbono** [comment]
Hi @benhus, this issue is still in our backlog and I can't tell you an estimation of the time it will take to be ready. We will keep you updated with any updates we have.

**Comment by keslerm** [comment]
Just in case someone else like me stumbles on this via search here is my two cents on how to do this via the helm chart, I created a custom config map entry and used the helm charts extra volumes/mounts to mount it inside the /opt/bitnami/apache/conf/vhosts directory to get auto loaded

One thing to note is to make sure you understand the difference between RemoteIPInternalProxy and RemoteIPTrustedProxy

Configmap:

```yaml
apiVersion: v1
data:
  real_ip.conf: |-
    LoadModule remoteip_module modules/mod_remoteip.so
    RemoteIPHeader X-Forwarded-For
    RemoteIPInternalProxy 10.42.0.0/16
    LogFormat "%a %l %u %t \"%r\" %>s %b" common
kind: ConfigMap
metadata:
  name: custom-config
```

Helm values stuff:
```yaml
extraVolumeMounts:
  - name: custom-config
    subPath: real_ip.conf
    mountPath: /opt/bitnami/apache/conf/vhosts/real_ip.conf

extraVolumes:
  - name: custom-config
    configMap:
      name: custom-config
```

**Comment by rafariossaa** [comment]
Hi @keslerm,
  Thanks for sharing your changes.

**Comment by marcosbc** [comment]
Hi all, note that it is now possible to extend this image and make Apache changes at build time to enable/disable certain modules.

If you do not want to extend the image, note that you can also do it at runtime via init scripts, which you can mount to `/docker-entrypoint-init.d` and perform any post-installation actions. Refer to [`post-init.sh`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh) for more info.
