### ISSUE TITLE
Error in wp-config.php file while restarting pod

### ISSUE THREAD

**Issue by momon** [bitnami/bitnami-docker-wordpress#180]
I have a pretty odd situation across several deployments while others (and new ones) are working without issues.

The ones with issues are giving me this error:

```
textPayload:  "Error executing 'postInstallation': PHP Notice:  Undefined index: HTTP_HOST in /bitnami/wordpress/wp-config.php on line 90
"  
```

This is on GKE.  inspecting the file it appears that wp-config.php is not complete (when compared to other live websites) and it is missing the DB parameters.  Here is the full reference of the build from the log:

```
E 2019-07-05T18:38:12.336224194Z [0m[1mWelcome to the Bitnami wordpress container[0m
E 2019-07-05T18:38:12.336229090Z [0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-wordpress[0m
E 2019-07-05T18:38:12.336234022Z [0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-wordpress/issues[0m
E 2019-07-05T18:38:12.336237673Z [0m
I 2019-07-05T18:38:15.282309557Z nami    INFO  Initializing apache
I 2019-07-05T18:38:15.341679988Z nami    INFO  apache successfully initialized
I 2019-07-05T18:38:18.132225972Z nami    INFO  Initializing php
I 2019-07-05T18:38:18.169468837Z nami    INFO  php successfully initialized
I 2019-07-05T18:38:21.066019612Z nami    INFO  Initializing mysql-client
I 2019-07-05T18:38:21.115363595Z mysql-c INFO  Trying to connect to MySQL server
I 2019-07-05T18:38:21.117771115Z mysql-c INFO  Found MySQL server listening at mysql-sqlproxy-gcloud-sqlproxy.sqlproxy:3306
I 2019-07-05T18:38:21.148760516Z mysql-c INFO  MySQL server listening and working at mysql-sqlproxy-gcloud-sqlproxy.sqlproxy:3306
I 2019-07-05T18:38:21.178621769Z mysql-c INFO  ==> Found database dtb-fp-112-wp-dok42. Skipping database creation...
I 2019-07-05T18:38:21.179106832Z nami    INFO  mysql-client successfully initialized
I 2019-07-05T18:38:24.698919546Z nami    INFO  Initializing wordpress
I 2019-07-05T18:38:36.079448151Z wordpre INFO  WordPress has been already initialized, restoring...
I 2019-07-05T18:38:36.812451128Z mysql-c INFO  Trying to connect to MySQL server
I 2019-07-05T18:38:36.820733131Z mysql-c INFO  Found MySQL server listening at mysql-sqlproxy-gcloud-sqlproxy.sqlproxy:3306
I 2019-07-05T18:38:36.853653121Z mysql-c INFO  MySQL server listening and working at mysql-sqlproxy-gcloud-sqlproxy.sqlproxy:3306
I 2019-07-05T18:38:36.854253915Z wordpre INFO  Upgrading WordPress Database ...
E 2019-07-05T18:38:37.276642374Z Error executing 'postInstallation': PHP Notice:  Undefined index: HTTP_HOST in /bitnami/wordpress/wp-config.php on line 90
E 2019-07-05T18:38:37.276666760Z PHP Notice:  Undefined index: HTTP_HOST in /bitnami/wordpress/wp-config.php on line 91
E 2019-07-05T18:38:37.276680033Z 
```

This appears to cause the pod to exit and keeps on an endless restart that always stops at the same error (above).

This was a working website.  I am unsure how to actually troubleshoot this one and get the website working again.

Creating new websites (and other that were live alongside this one) has been working correctly.

Looking further, that wp-config.php file on the pod that throws the error looks like this:

```
<?php
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define( 'DB_NAME', 'database_name_here' );

/** MySQL database username */
define( 'DB_USER', 'username_here' );

/** MySQL database password */
define( 'DB_PASSWORD', 'password_here' );

/** MySQL hostname */
define( 'DB_HOST', 'localhost' );

/** Database Charset to use in creating database tables. */
define( 'DB_CHARSET', 'utf8' );

/** The Database Collate type. Don't change this if in doubt. */
define( 'DB_COLLATE', '' );

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define( 'AUTH_KEY',         'put your unique phrase here' );
define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
define( 'NONCE_KEY',        'put your unique phrase here' );
define( 'AUTH_SALT',        'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
define( 'NONCE_SALT',       'put your unique phrase here' );

/**#@-*/

/**
* WordPress Database Table prefix.
*
* You can have multiple installations in one database if you give each
* a unique prefix. Only numbers, letters, and underscores please!
*/
$table_prefix = 'wp_';

/**
* For developers: WordPress debugging mode.
*
* Change this to true to enable the display of notices during development.
* It is strongly recommended that plugin and theme developers use WP_DEBUG
* in their development environments.
*
* For information on other constants that can be used for debugging,
* visit the Codex.
*
* @link https://codex.wordpress.org/Debugging_in_WordPress
*/
define( 'WP_DEBUG', false );

/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
       define( 'ABSPATH', dirname( __FILE__ ) . '/' );
}

/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );
```

This looks to me like a placeholder file rather than an actual wp-config file since it doesn't even have the actual mysql information that should be there.

Compared to one of my live websites, it seems to also be missing this portion (past line 90)

```
define('FS_METHOD', 'direct');

define('WP_TEMP_DIR', '/opt/bitnami/wordpress/tmp/');

if ( !defined( 'WP_CLI' ) ) {
//  Disable pingback.ping xmlrpc method to prevent WordPress from participating in DDoS attacks
//  More info at: https://wiki.bitnami.com/Applications/Bitnami_WordPress#XMLRPC_and_Pingback

// remove x-pingback HTTP header
add_filter("wp_headers", function($headers) {
            unset($headers["X-Pingback"]);
            return $headers;
           });
// disable pingbacks
add_filter( "xmlrpc_methods", function( $methods ) {
             unset( $methods["pingback.ping"] );
             return $methods;
           });
}
```

So my best guess here is that something is causing the install script to fail midway and results in an error, stopping the container and causing the endless restart loop.

Any clues?

**Comment by marcosbc** [comment]
Hi @momon, the Bitnami WordPress container persists content files in `/bitnami/wordpress/` (`wp-content` and `wp-config.php`). When you see `WordPress has been already initialized, restoring...` it means it is copying the data files from the volume.

In any case, try adding the content below to your `wp-config.php` file inside your volume, including the contents you mention were missing:

```
if ( defined( 'WP_CLI' ) ) {'
  $_SERVER['HTTP_HOST'] = '127.0.0.1';
}
```

**Comment by momon** [comment]
@marcosbc much appreciate the response.  What's the ideal way of manually editing that file?  I had a hard time just getting the data from it since the container is constantly restarting, it is only alive for just a few seconds and then it restarts (because of the script failure).

How would I go about manually fixing these containers when this happens? (I have several deployments that have the exact same symptom).

More importantly, going back to my original question, adding those lines alone wont do since the file itself looks like a placeholder (it does not have the actual database info in it).

**Comment by marcosbc** [comment]
If you mention the file does not include the database setup, it means something has happened and for some reason it has been reset to the default values. It is really strange as our logic does not contemplate that. There must have been an issue mounting the volume or something similar, causing this to happen.

In that case I would recommend to try a different approach by creating a new deployment that [uses an existing database](https://github.com/bitnami/bitnami-docker-wordpress#use-an-existing-database), and removing the old deployment (but not its database!).

Your wp-content and wp-config.php changes will be missing, but you will have access to your data.

Please let us know if you reproduce this issue again. Any logs for the initialization before, during (the first time it happens) and after the bug will be really helpful for fixing this issue.

**Comment by momon** [comment]
@marcosbc correct.  I provided examples above of what I am seeing and the error from the log also (all in original comment).  In the brief time the container is up (before it exits) I can see the PVC being loaded without issues as I can LS files in it (specifically plugins) that are not installed by default.  The only way those would show is if it loaded the PVC for this deployment.

If I understand what you are asking me to do, you want me to create a new deployment (on a new PVC) that assumes an existing DB but not an existing PVC.  I could do that, but I would rather get a backup of the data in the PVC instead and re-deploy.

Is there any way for me to keep the container alive despite the error or troubleshoot the error so the container does not restart?

Happy to provide any info, I did share the logs above, I know they may not be entirely helpful but that's all there seems to be in it and I am pretty sure the PVC (at least loading it) isn't the issue since I can LS the files in it that would only be present if it was loading.

**Comment by marcosbc** [comment]
If wp-config.php is not persisted properly, it probably means the same for the wp-content directory, and these files are the only ones that get persisted between runs (apart from the database data, of course).

You could check in case there is any custom data in wp-content (like the way you checked wp-config.php file contents), but if not, it means any data inside have been lost.

If you do find any custom content, you could modify the "command"/"cmd" for the container in order to be able to enter it afterwards via "kubectl exec":

- Change the "command"/"cmd" in one of the following ways:
  - Helm: [Update the deployment](https://dzone.com/articles/create-install-upgrade-rollback-a-helm-chart-part) and change the command to something like "tail -f /dev/null". You must remove the readiness checks and update the chart version.
  - Raw kubernetes: Edit the deployment with "kubectl edit deployment mydeployment" and change the "command"/"cmd" and remove readiness checks.
- Enter the WordPress container via "kubectl exec" and retrieve any data.

Hope it helps!

**Comment by momon** [comment]
I appreciate the help @marcosbc I was able to resolve the issue.  Seems a bit confusing (based on the error log) but it turned out to be a custom plugin that was throwing a PHP error.  Simply forcing that plugin to delete BEFORE the wordpress initialization scripts solved it immediately.

I say this was confusing because if you look at the error log, the first sign of an error is coming from the wp-config file (and not a plugin) but that plugin being the one customization I had done to the deployment is what lead me to testing that.

So turns out it is not precisely a bitnami error but a result of a custom plugin that was broken despite what the error message above may suggest.  That still seems a bit odd to me but surely one to keep track of.

**Comment by marcosbc** [comment]
That's great to hear. We will keep that in mind for future cases where we see this error. In the end you didn't lose any data in wp-config.php or wp-content right? Thank you!

**Comment by momon** [comment]
Correct. I can confirm no data was lost.  Everything was there once the deployment was able to finish successfully (after removing the broken plugin).  The entire issue was just out of a PHP error on one of the plugins that appeared to break processing of the initialization script, thus resulting in the container constantly restarting.
