### ISSUE TITLE
Adding custom fonts

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-wordpress#183]
We need 3 woff-files inside the container, at /opt/bitnami/wordpress/wp-includes/fonts

Manually done with:

```
docker cp TheSans_LT_300i.woff 4580dfffabf7:/opt/bitnami/wordpress/wp-includes/fonts
[..]
docker exec -it www_ds_com_wordpress_1  /bin/bash
# inside : chown bitnami:daemon /opt/bitnami/wordpress/wp-includes/fonts/TheSans*.woff
```

works

Now I want to define that within my docker-compose.yml if possible (to make it more persistent).

Tried:

```
volumes:
      - wordpress_data:/bitnami
      - ./fonts:/opt/bitnami/wordpress/wp-includes/fonts
```

didn't work

Do I need another persistent volume here and copy the files once in there?

pls advise.

**Comment by miguelaeh** [comment]
Hi @stefangweichinger ,
I have tried to replicate your issue, but in my case I can mount the files properly. Could you describe the error you are obtaining please? You should be able to mount the files you want in any path using docker-compose.

**Comment by stefangweichinger** [comment]
@miguelaeh  : I totally crashed my stack today and had to recreate ;-) seems as if the fonts are mounted/mapped now correctly. Although this seems to "remove"/hide the default fonts in that directory (which came from your image). No issue for me so far, just mentioning.

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue (even in this way). If you have any other questions, please do not hesitate to let us know
