### ISSUE TITLE
Unable to use Elementor

### ISSUE THREAD

**Issue by adtenn** [bitnami/bitnami-docker-wordpress#186]
**Description**

I am trying to use Elementor with this Docker image, but I'm unable to open the editor. Instead I receive the following error message:

> Your site's .htaccess file appears to be missing. File path: /opt/bitnami/wordpress/.htaccess

**Steps to reproduce the issue:**

1. Install Elementor
2. Create a new Page
3. Attempt to edit that page with Elementor

**Describe the results you received:**
Error dialog with the following:

> Your site's .htaccess file appears to be missing. File path: /opt/bitnami/wordpress/.htaccess

**Describe the results you expected:**

The editor to load correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

The plugin only cares about the file existing, not the contents of it. Using `kubectl exec` to `touch /opt/bitnami/wordpress/.htaccess` solves the issue, but this isn't persisted on reboot.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
`docker.io/bitnami/wordpress:5.2.1-debian-9-r9` running in GKE.

**Comment by andresbono** [comment]
Hi @adtennant, to improve the performance of Apache we configure it to ignore `.htaccess` files and the contents of that file are written to `/opt/bitnami/apache/conf/vhosts/htaccess/wordpress-htaccess.conf`.

As you mention, Elementor should be doing some check and it fails if the `.htaccess` doesn't exist, even if that one is not being used.

Modifying the WordPress container is not easy at this moment and there is another issue open for that, check #173.

Maybe what you can do to workaround this is to create an empty config map and mount it as a volume in `/opt/bitnami/wordpress/.htaccess`.

**Comment by dnauck** [comment]
Elementor provided a new update yesterday that fixed this issue.
