### ISSUE TITLE
How do I get access to the wordpress folders

### ISSUE THREAD

**Issue by aw3some-dev** [bitnami/bitnami-docker-wordpress#188]
**Description**

How do I get access to the wordpress folders

**Steps to reproduce the issue:**

I tried mounting a host directory as a data volume for the wordpress container so I could get access to the wordpress files but I don't think that's how it works. 

`docker run -d --name wordpress -p 4000:80 -e ALLOW_EMPTY_PASSWORD=yes -e WORDPRESS_DATABASE_USER=bn_wordpress -e WORDPRESS_DATABASE_NAME=bitnami_wordpress --net wordpress-tier --volume c:/bitnami_wordpress_persist:/bitnami bitnami/wordpress:latest
`

**Describe the results you received:**
I instead got an empty directory 

**Describe the results you expected:**
 I expected that I would see the wordpress files in the indicated directory.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.1, build 74b1e89
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 27
  Running: 3
  Paused: 0
  Stopped: 24
 Images: 32
 Server Version: 19.03.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.952GiB
 Name: docker-desktop
 ID: ABYF:WE4R:6K7D:KXIE:WNE4:Y2L3:4XZV:JOVJ:WXRP:XA5H:OEUP:ZYZE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 52
  Goroutines: 65
  System Time: 2019-08-20T09:06:50.4140744Z
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
Not using docker-compose
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
OS - Windows 10 build 1903
Using Docker Desktop

**Comment by juan131** [comment]
Hi @aw3some-dev 

Are you using the **docker-compose.yaml** available in the repo to deploy WP+MariaDB? If that's the case you can browse the WP files as shown below:

```console
$ docker-compose up -d
$ docker-compose exec wordpress bash
# cd /opt/bitnami/wordpress
```

**Comment by aw3some-dev** [comment]
Hey, @juan131 
I'm following the manual approach i.e. I'm not using docker-compose (even though I know its a better and much easier approach). I'm looking for the alternative using the docker engine without compose.

**Comment by aw3some-dev** [comment]
**Update:**
When I run 
`docker run -d --name wordpress -p 4000:80 -e ALLOW_EMPTY_PASSWORD=yes -e WORDPRESS_DATABASE_USER=bn_wordpress -e WORDPRESS_DATABASE_NAME=bitnami_wordpress --net wordpress-tier --volume c:/bitnami_wordpress_persist:/bitnami bitnami/wordpress:latest`. 

The wordpress folder is populated with a wp-content directory and a wp-config.php file. I'd like to get access to all the WP files. What I'm really trying to do is import a wordpress site that I developed on another machine using duplicator. So I need access to the WP directory so I can place the installer.php file in there and navigate to it with the url: `localhost:4000/installer.php`

**Comment by aw3some-dev** [comment]
**Update:**

I've been able to access the WP files using the command
`docker container exec -it <container-id> bash`

Note: Replace `<container-id>` with your own container id
Afterwards navigate to the worpress folder, in my case I used:

`cd opt/bitnami/wordpress`

You should see all the wordpress directories and files there.

**Comment by jkhaui** [comment]
> Hi @aw3some-dev
> 
> Are you using the **docker-compose.yaml** available in the repo to deploy WP+MariaDB? If that's the case you can browse the WP files as shown below:
> 
> ```
> $ docker-compose up -d
> $ docker-compose exec wordpress bash
> # cd /opt/bitnami/wordpress
> ```

Wow, after hours of searching this actually solved my problem: how to access the file system of a Bitnami WordPress container. Pretty amazed this isn't shown prominently in Bitnami's documentation, IMO it seems like it would be a very common issue but without an obvious solution (especially for people not used to Docker)

**Comment by carrodher** [comment]
Thanks for the suggestion, I just created an internal task to add a line in the container READMEs specifying where the application files appear

**Comment by rizkysyazuli** [comment]
@aw3some-dev i'm also looking into migrating an existing WP website using [Duplicator](https://wordpress.org/plugins/duplicator/) (free).

So what did you do? Did u dump the installation files into `/opt/bitnami/wordpress`?

**Comment by admarmaz** [comment]
> @aw3some-dev i'm also looking into migrating an existing WP website using [Duplicator](https://wordpress.org/plugins/duplicator/) (free).
> 
> So what did you do? Did u dump the installation files into `/opt/bitnami/wordpress`?

Yes sir, trying the same here. Let me know if you found the solution
