### ISSUE TITLE
What option to use to enable SSL connection to external database?

### ISSUE THREAD

**Issue by skumar4120** [bitnami/bitnami-docker-wordpress#189]
Is there an option to use to enable SSL connection to external database? Currenlty bitnami wordpress docker image is not letting me connect to external dabase MySQL which SSL enabled with the following error.
```
mysql-c INFO  Trying to connect to MySQL server
wordpress_1  | mysql-c INFO  Found MySQL server listening at luke-demo-xxxx-mysql-rds-development.cxdi9qpyxrqv.us-XXXx
```
Run docker-compose up from home directory where docker-compose file is present.

**Describe the results you expected:**Successful connection to MySQL dB.

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
It seems the database is using password and you didn't provide the password to Wordpress. 
Did you set the `WORDPRESS_DATABASE_PASSWORD` en var to connect with MySQL?

**Comment by skumar4120** [comment]
I am providigng the password explictly nad yes I did set the WORDPRESS_DATABASE_PASSWORD.

version: "3"
services:
  wordpress:
    image: repo.forge.lmig.com/docker/gs/devops/dockerwordpress_2:${bambooBuildNumber}
    ports:
      - '8099:80'
    environment:
      - MARIADB_HOST=dockerwordpress-mysql-rds-test.cxdi9qpyxrqv.us-east-1.rds.amazonaws.com
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=${userId}
      - WORDPRESS_DATABASE_PASSWORD=${password}
      - WORDPRESS_DATABASE_NAME=gs_mysql_standard
      - ALLOW_EMPTY_PASSWORD=no
    networks:
      - ucp-hrm
    deploy:
      replicas: 1
      labels: 
        - com.docker.ucp.access.label=gs-caas
        - com.docker.ucp.mesh.http.8099=external_route=http://dockerwordpress,internal_port=80

networks:
  ucp-hrm:
    external:
      name: ucp-hrm

**Comment by skumar4120** [comment]
is there an option to establish SSL connection between the database and docker container in the compose file through parameter setting?

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
I can see the image your are using is not the bitnami image, did you modified it? or just copy? 
Did you try to set the password instead of use a variable `${password}` ?

> is there an option to establish SSL connection between the database and docker container in the compose file through parameter setting?

All the env vars available are [here](https://github.com/bitnami/bitnami-docker-wordpress#environment-variables).
You can test the connection by exec into the container:
```
$ docker-compose exec wordpress bash
```

As it is a root container you can perform as many actions as you want to test the connection.

**Comment by skumar4120** [comment]
I used the Bitnami image and built upon it by extending it. I am passing it through the pipeline the password and hence using like this. But it works when I use plain text password which is not allowed in production. Hence using the password like this which is passed correctly as I see in logs. 

I don’t see a environment variable to set the connection between docker container and database as SSL. Do you know how to make this as SSL connection between container and database?

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
I can see in the code the option exists but it is not was not exposed to an env var, thanks for reporting, I am updating it and it should be released in a few hours.
You should see [here](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-9/rootfs/wordpress-inputs.json) the env var `WORDPRESS_DATABASE_SSL_CA_FILE` when it will be released.

**Comment by miguelaeh** [comment]
As you can see [here](https://github.com/bitnami/bitnami-docker-wordpress/blob/8d8cd8e2a5bfe3bbead858d19b1810aa726f7af2/5/debian-9/rootfs/wordpress-inputs.json#L5) it has been already released.

**Comment by skumar4120** [comment]
Does the value of this environment variable take the file name or file location? I have a pem file for certificates and is there a default location to copy this file to?

**Comment by skumar4120** [comment]
Another related question, is there a way I can pass the password field through a personal script I have in my project. Instead of specifying it in the docker-compose file?

**Comment by skumar4120** [comment]
I passed in the SSL CA file like - WORDPRESS_DATABASE_SSL_CA_FILE=rds-ca-2015-us-east-1.pem and added the file to the current directory. Getting errror ERROR 2026 (HY000): SSL connection error: No such file or directory.

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
The env var receives a file path and there isn't a default path, for example see the following docker-compose I tested:
```
   1 version: '2'
    2 services:
    3   mariadb:
    4     image: 'bitnami/mariadb:10.3'
    5     volumes:
    6       - 'mariadb_data:/bitnami'
    7     environment:
    8       - MARIADB_USER=bn_wordpress
    9       - MARIADB_DATABASE=bitnami_wordpress
   10       - ALLOW_EMPTY_PASSWORD=yes
   11       - WORDPRESS_DATABASE_SSL_CA_FILE=/bitnami/cert.pem
   12   wordpress:
   13     image: 'bitnami/wordpress:5'
   14     ports:
   15       - '80:80'
   16       - '443:443'
   17     volumes:
   18       - 'wordpress_data:/bitnami'
   19       - './cert.pem:/bitnami/cert.pem'
   20     depends_on:
   21       - mariadb
   22     environment:
   23       - MARIADB_HOST=mariadb
   24       - MARIADB_PORT_NUMBER=3306
   25       - WORDPRESS_DATABASE_USER=bn_wordpress
   26       - WORDPRESS_DATABASE_NAME=bitnami_wordpress
   27       - ALLOW_EMPTY_PASSWORD=yes
   28
   29 volumes:
   30   mariadb_data:
   31     driver: local
   32   wordpress_data:
   33     driver: local
```

**Comment by skumar4120** [comment]
I am using an external MySQL database and hence can I copy the file cert.pem to the container in volumes like  './cert.pem:/bitnami/cert.pem' and use the environment variable in wordpress block of the docker compose file like - WORDPRESS_DATABASE_SSL_CA_FILE=/bitnami/cert.pem to get it working for external MySQL databse? Please confirm. If not please give an example for using the WORDPRESS_DATABASE_SSL_CA_FILE env variable with an external databse connection. Thanks.

**Comment by skumar4120** [comment]
I copied the .pem file to the tmp folder in a bash script like cp rds-ca-2015-us-east-1.pem /tmp and used it in docker compose file   and getting error {"line":" ERROR 1146 (42S02) at line 1: Table 'gs_mysql_standard.wp_usermeta' doesn't exist","source":"stderr","tag":"repo.forge.lmig.com/docker/gs/devops/dockerwordpress_2:60@sha256:9f84c114a9a8a3e76cb6d2e893a4ad704ab2cb2865753249c22323cb58369c92/test_wordpress_2_wordpress.1.c1y71e01vsv35ve3amy7p8vee/2756705f82fb"}
wordpress:
    image: xxxx
    ports:
      - '8099:80'
    environment:
      - MARIADB_HOST=xxxx
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=${userId}
      - WORDPRESS_DATABASE_PASSWORD=${password}
      - WORDPRESS_DATABASE_NAME=gs_mysql_standard
      - ALLOW_EMPTY_PASSWORD=no
      - WORDPRESS_DATABASE_SSL_CA_FILE=/tmp/rds-ca-2015-us-east-1.pem

**Comment by miguelaeh** [comment]
> can I copy the file cert.pem to the container in volumes like './cert.pem:/bitnami/cert.pem' and use the environment variable in Wordpress block of the docker compose file like - WORDPRESS_DATABASE_SSL_CA_FILE=/bitnami/cert.pem to get it working for external MySQL databse?

Yes, in the docker-compose WordPress and MariaDB are separate services, docker-compose help to deploy them as containers but they remain separate services.

> Table 'gs_mysql_standard.wp_usermeta' doesn't exist",

That is probably a problem with your MySQL configuration, maybe the table is corrupt, the MYSQL datadir has improper permissions, etc. 
Also have in mind that your configuration for WordPress needs the database to exists, if you want the database to be created by WordPress please use [this](https://github.com/bitnami/bitnami-docker-wordpress#create-a-database-for-wordpress-using-mysql-client) configuration.

**Comment by skumar4120** [comment]
Yes it was access user id issue and fixed it with right permissions. Now facing the given error.Bitnami application container is up for a little bit and then shuts down due to this error.{"line":"[Tue Sep 17 18:12:16.740123 2019] [mpm_prefork:notice] [pid 99] AH00169: caught SIGTERM, shutting down","source":"stderr","tag":"repo.forge.lmig.com/docker/gs/devops/dockerwordpress_2:62@sha256:cdf6590a6c0c4729ab5f275ea6550d3619c9fda806c374dc082ee295b4a57f7e/test_wordpress_2_wordpress.1.6lgenj4jl0smwnmorm60r0fr6/2f7a054a8481"}

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
Could you provide more information about that error? That line is now enough to us to see what could be happening.

**Comment by skumar4120** [comment]
I deploy the application which uses the bitnami base image and I was abe to log into the application immediately after deploy. However after few hours when I try to access the wordpress application deployed earlier, i am getting this error and do not hav any other error in the logs.

**Comment by miguelaeh** [comment]
That error is normally related to a bad SSL certificate. Be sure your certificates are generated for your Apache server correctly.

**Comment by skumar4120** [comment]
in the link https://community.bitnami.com/t/my-amazon-ec2-instance-with-bitnami-wordpress-get-those-errors/58925/2 bitnami says "This is just a warning message because the SSL certificate has a different hostname than the one set in the Apache's configuration.". this is just the warning and the main error is caught SIGTERM, shutting down","source":"stderr". I have created a ticket with bitnami at their supprt https://community.bitnami.com/t/sigterm-error-on-running-container/71018

**Comment by skumar4120** [comment]
can I increase the verbosity of logging in the application by modifying any of the env vars?

**Comment by miguelaeh** [comment]
yes, you can set
`NAMI_LOG_LEVEL=trace8`

**Comment by skumar4120** [comment]
Thanks. in the docker compose file I set this?

**Comment by miguelaeh** [comment]
Right. Just put it at the `environment` section.

**Comment by skumar4120** [comment]
I want to hide the password WORDPRESS_DATABASE_PASSWORD in the docker secrets section and do not want to specify it explicitly in the docker compose file like we do now. This is causing the security violation in my organization. is there a way to do that in bitnami?

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
That is not supported by default. To use with docker secrets you will need to modify the init scripts to set the value `WORDPRESS_DATABASE_PASSWORD` to the content of the secret that will be stored at `/run/secrets` directory. Also your node should be part of a swarm to create the docker secret.
A simpler way to avoid hard code the password in the `docker-compose.yml` file would be use an environment variable populated from your node to the docker-compose in this way:
```
environment:
  - "WORDPRESS_DATABASE_PASSWORD:${MY_ENV_VAR}"
```
You can get more info about that [here](https://docs.docker.com/compose/environment-variables/).

**Comment by skumar4120** [comment]
How do I restart the apache/httpd server in bitnami container?what command is ued?

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
The Apache server is initialized with: 
```console
$ /opt/bitnami/apache/bin/httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND
```
To restart the server, you can just restart the container as the configuration will be stored into a volume, so when you restart the container Apache is initialized again with the previous configuration.

**Comment by skumar4120** [comment]
I have a new relic agent installd on the container and would like to restart the Apache server without restarting the container in order to test the new relic monitring. If I restart the container I have to reinsatll the agent and then restart the Apahce server agin in order for it to send the traffic.

**Comment by skumar4120** [comment]
does "nami restart apache" restart the Apache server without restarting the container?

**Comment by skumar4120** [comment]
what is the  web server's root directory location?

**Comment by miguelaeh** [comment]
Hi @skumar4120 ,
> does "nami restart apache" restart the Apache server without restarting the container?

Yes, nami restart will restart the Apache server without stopping the container.

>what is the web server's root directory location? 

All the components application directories are under `/opt/bitnami`, for example, for php go to `/opt/bitnami/php`

**Comment by skumar4120** [comment]
when I go to the landing page of the bitnami wordpress application, using /index.html is redirecting to helloworld page and I am not seeing  "It works" message in the index.html. I added a php.html page at opt/bitnami/apache/htdocs directory and expecting it to dispaly on the browser. but I dont see  that new page either named php.html and getting page not found error. Could you please help to create a new page on the apache web server at opt/bitnami/apache/htdocs and get that page in the web browser?
