### ISSUE TITLE
Docker secrets don't work for setting the values of wordpress database user and password

### ISSUE THREAD

**Issue by RationalAnimal** [bitnami/bitnami-docker-wordpress#194]
**Steps to reproduce the issue:**

in the docker compose file add the lines (in the environment section):
      WORDPRESS_DATABASE_USER_FILE: "/run/secrets/user"
      WORDPRESS_DATABASE_PASSWORD_FILE: "/run/secrets/password"
Verify that the secrets actually exist (they do - files are in /run/secrets and the contents are correct)
run docker-compose up
Get this error:
The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.

**Describe the results you received:**

WORDPRESS_DATABASE_PASSWORD is not set

**Describe the results you expected:**

WORDPRESS_DATABASE_PASSWORD would have been set by the WORDPRESS_DATABASE_PASSWORD_FILE using the docker secrets file.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by RationalAnimal** [comment]
in the docker compose file add the lines (in the environment section):
      WORDPRESS_DATABASE_USER_FILE: "/run/secrets/user."
      WORDPRESS_DATABASE_PASSWORD_FILE: "/run/secrets/password"
Verify that the secrets actually exist (they do)
run docker-compose up
Get this error:
The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.

**Comment by rafariossaa** [comment]
Hi @RationalAnimal,
  The env vars you can set are in the [configuration](https://github.com/bitnami/bitnami-docker-wordpress#user-content-configuration) section of the readme.
  To use docker secrets, please take a look to [docker documentation](https://docs.docker.com/engine/swarm/secrets/), the maybe you find useful the mysql example.

**Comment by RationalAnimal** [comment]
Hi @rafariossaa 
I HAVE read the docker documentation, specifically the MySQL section where they show how to use MYSQL_PASSWORD_FILE and MYSQL_ROOT_PASSWORD_FILE and other xxx_FILE options. These are implemented in the base wordpress image, but NOT in the bitnami/wordpress image.  That is the whole point of this issue. In order to use docker secrets properly (i.e. to NOT expose them as env variables which can be seen by 'console'-ing into a container and not using them in plain text, etc) xxx_FILE options need to be implemented. It appears that in the bitnami/wordpress they are NOT. Please re-read the issue before commenting.

**Comment by RationalAnimal** [comment]
To clarify further, I am trying to use the docker-compose.yaml approach because this is used in an enterprise CI/CD pipeline. Secrets management is extremely important here. The only workaround I can see is wrapping the startup script and declaring local env vars, but it's hacky. Bitnami simply should implement xxx_FILE options for anything that may be passed in as secrets.

**Comment by rafariossaa** [comment]
Hi @RationalAnimal, 
  We use secrets in our charts, but not in our containers.
  I will escalate your suggestion.

Thanks,
