### ISSUE TITLE
define('FS_METHOD', 'direct') needs to be above last comment

### ISSUE THREAD

**Issue by sbiniok** [bitnami/bitnami-docker-wordpress#196]
The statement for FS_METHOD needs to be above

`/* That's all, stop editing! Happy publishing. */

/** Absolute path to the WordPress directory. */
if ( ! defined( 'ABSPATH' ) ) {
	...
}
/** Sets up WordPress vars and included files. */
require_once( ABSPATH . 'wp-settings.php' );`

Otherwise it wont work.

**Comment by rafariossaa** [comment]
Hi @sbiniok ,
  Thanks for noticing it.
  We are working to fix this in a new release.
  I will come back to you as soon as it is released.

**Comment by rafariossaa** [comment]
Hi @sbiniok ,
  We have made a new release fixing this.
  Could you give it a try ?
