### ISSUE TITLE
Unable to show php logs

### ISSUE THREAD

**Issue by Nittarab** [bitnami/bitnami-docker-wordpress#197]
**Description**

I'm looking for the php logs, in the `/bitnami/php/config/php.ini` the file end with this line:
`error_log = /log/myCustomLog.log`
But I don't find this folder.

I also check with `php -i | grep 'log'` and I got this: `error_log => /log/myCustomLog.log => /log/myCustomLog.log
`

**Version**

image version: wordpress-4.9.8-9
- The output of `docker version`:

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
helm chart, Kubernetes

**Comment by tompizmor** [comment]
Hi @Nittarab,

I guess you have mounted your custom php.ini, right? By default, the error_log is not set in the wordpress container.

In any case, I am not sure if php will write any log at all as it is not running as a service (php-fpm is not configured)

**Comment by Nittarab** [comment]
Hi @tompizmor thanks for the response. So how can I get the php logs? 🙃

**Comment by Nittarab** [comment]
I also tried to execute:
`nami execute php log` 
I got `""`

**Comment by sameersbn** [comment]
@Nittarab Wordpress is served by Apache which uses the `mod_php` module to parse the PHP files. In this configuration all apache logs are written out to the stdout of the container. You can also find the apache log file at container path `/opt/bitnami/apache/logs`. If there are any PHP errors, I believe they would be logged in `/opt/bitnami/apache/logs/error_log`
