### ISSUE TITLE
daemon is no longer able to use wp (wp-cli)

### ISSUE THREAD

**Issue by momon** [bitnami/bitnami-docker-wordpress#201]
It appears something changed here recently as my init script (which uses this image as a base) is now broken on some wp commands because daemon is no longer allowed to run wp commands.  Here is the output when you try to run it as root and as daemon:

As root (it works):
```
momon@DESKTOP-DA4IGK9:~$ kubectl exec pod -c wordpress -- wp help
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under.

If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.

If you'd like to continue as root, please run this again, adding this flag:  --allow-root

If you'd like to run it as the user that this site is under, you can run the following to become the respective user:

    sudo -u USER -i -- wp <command>


command terminated with exit code 1
```

As daemon (it does not work):

```
momon@DESKTOP-DA4IGK9:~$ kubectl exec pod  -c wordpress -- sudo -u daemon -i -- wp help
This account is currently not available.
command terminated with exit code 1
```

This is how the readme says we "should" be using it (which also does not work):

```
momon@DESKTOP-DA4IGK9:~$ kubectl exec pod -c wordpress -- sudo -u daemon -- wp help
sudo: wp: command not found
command terminated with exit code 1
```

It also seems like the user bitnami which used to be the one all files would be created under no longer exists since this chown command I had at the end of my script is also complaining about bitnami user no longer existing:

```
INFO  ==> Setup placeholder file used to identify first install...
INFO  ==> Setup placeholder file completed
INFO  ==> Setup Special permissions on needed files
chown: invalid user: 'bitnami:daemon'
```

I am unclear if this was intentional or introduced as part of the recent change from minideb-extras to minideb on the dockerfile.

**Comment by juan131** [comment]
Hi @momon 

Thanks for reporting this issue! As you mentioned it's related to some changes we did in the base image used to build every docker image (`minideb-extras` -> `minideb`) since we're removing "intermediate" images.

We already fixed and we released a new version of the container addressing this issue (**5.3.2-r24**). As you can check in the link below, a new layer (that was present on minideb-extras`) was added:

- Link: https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-9/Dockerfile
- New layer added:

```Dockerfile
RUN useradd -ms /bin/bash bitnami && \
    mkdir -p /opt/bitnami && chown bitnami:bitnami /opt/bitnami && \
    sed -i -e 's/\s*Defaults\s*secure_path\s*=/# Defaults secure_path=/' /etc/sudoers && \
    echo 'bitnami ALL=NOPASSWD: ALL' >> /etc/sudoers
```

**Comment by momon** [comment]
Sorry for the late follow up.  I have now undone my adjustments to work around the bug and can confirm the latest image is working as expected.

Thank you for the prompt attention to this issue.

Cheers
