### ISSUE TITLE
Helm install WordPress in Kubernetes - multiple unresolved W3 Total Cache errors 

### ISSUE THREAD

**Issue by lance-hardy** [bitnami/bitnami-docker-wordpress#203]
Bitnami support requested I post this issue here:

I have found no way to correct this.

I helm install stable/wordpress with some custom values in a Kubernetes Cluster. I then do a backup restore from a production WordPress EC2 instance using All-in-One WP Migration. The backup restore is flawless.

On the W3 Total Cache Dashboard there are the following messages:

/opt/bitnami/wordpress/wp-content is write-able. When finished installing the plugin, change the permissions back to the default: chmod 755 /opt/bitnami/wordpress/wp-content. Permissions are currently 775

- FTP credentials don't allow to write to file /opt/bitnami/wordpress/wp-config.php

- W3 Total Cache Error: Files and directories could not be automatically created to complete the installation.
Please execute commands manually (and when reviewing required changes:)
Edit file /opt/bitnami/wordpress/wp-config.php and add next lines:
/** Enable W3 Total Cache */
define('WP_CACHE', true); // Added by W3 Total Cache

- The required directives for fancy permalinks could not be detected, please confirm they are available: Creating and editing

I have found no information anywhere that addresses how to allow required customization of core files in a kubernetes WordPress deployment (despite the supposed ability to use a custom .htaccess file in the helm chart).

If W3 Total Cache is simply not a workable caching solution for this type of deployment, does bitnami suggest or support any others?

**Comment by marcosbc** [comment]
Hi @lance-hardy, note that the permissions for `wp-content` and `wp-config.php` are set to 775 and 640 respectively, for security purposes.

Find our notes below:

>* FTP credentials don't allow to write to file /opt/bitnami/wordpress/wp-config.php
>* W3 Total Cache Error: Files and directories could not be automatically created to complete the installation.
>    Please execute commands manually (and when reviewing required changes:)
>    Edit file /opt/bitnami/wordpress/wp-config.php and add next lines:
>    /** Enable W3 Total Cache */
>    define('WP_CACHE', true); // Added by W3 Total Cache


If you enabled a plugin such as W3 Total Cache and it requires to write to `wp-config.php`, you should either configure your container image with that changes, or change the permissions for that file.

Since the current permissions are set for security-related reasons, you should ideally instead manually add the configuration. To do this, create a custom container image with a Dockerfile similar to the one below:

```
FROM bitnami/wordpress:5

# Add W3 Total Cache required changes
RUN sed -ri "s|(/\* That's all, stop editing)|/\*\* Enable W3 Total Cache \*/\ndefine('WP_CACHE', true); // Added by W3 Total Cache\n\1|" /opt/bitnami/wordpress/wp-config.php
```

Then, publish the container image and change the WordPress image used by your Kubernetes cluster. I.e. in the Helm chart, with `--set image.repository=yourusername/wordpress --image.tag=sometagname`.

Alternatively, if creating a new image is not an option for you, you could mount a file with the below contents to the WordPress container at `/post-init.sh` and achieve the same result:

```
#!/bin/bash

# Add W3 Total Cache required changes
sed -ri "s|(/\* That's all, stop editing)|/\*\* Enable W3 Total Cache \*/\ndefine('WP_CACHE', true); // Added by W3 Total Cache\n\1|" /opt/bitnami/wordpress/wp-config.php
```

>The required directives for fancy permalinks could not be detected, please confirm they are available: Creating and editing

In principle you would ignore this message, and ensure the required directives are added to your custom mounted `.htaccess` to `/opt/bitnami/apache/vhosts/htaccess/`. That is because Bitnami solutions load the Htaccess file at server startup, allowing for an improved performance and higher security, as the file cannot be altered without permissions.

Hope this resolves your questions!

**Comment by lance-hardy** [comment]
Hello @marcosbc - thank you for this information, very useful. We opted for your first suggestion and made a custom container file.  We revised our helm chart to point to this image:

`image:
  registry: docker.io
  repository: apptoto/wordpress
  tag: "latest"

  pullPolicy: Always

  pullSecrets:
    - regcred`

Curious if you have any insights as to why a helm install now produces docker image pull errors. We successfully deploy other private charts using the regcred secret. I'm curious if there are other areas of the wordpress chart that need modification - deployment.yaml perhaps? I've looked into the error noted from the failed wordpress pod but various suggestions (including creating the regcred secret in the namespace WP is being deployed to) haven't fixed the issue. 

Thank you, your second suggestion is definitely on deck!

`  Normal   Scheduled  36s                default-scheduler                       Successfully assigned testing/wordpress-test-56958b7d57-svw5j to ip-192-168-59-78.ec2.internal
  Normal   Pulled     35s                kubelet, ip-192-168-59-78.ec2.internal  Container image "docker.io/bitnami/apache-exporter:0.7.0-debian-10-r0" already present on machine
  Normal   Created    35s                kubelet, ip-192-168-59-78.ec2.internal  Created container metrics
  Normal   Started    35s                kubelet, ip-192-168-59-78.ec2.internal  Started container metrics
  Normal   Pulling    23s (x2 over 35s)  kubelet, ip-192-168-59-78.ec2.internal  Pulling image "docker.io/apptoto/wordpress:latest"
  Warning  Failed     23s (x2 over 35s)  kubelet, ip-192-168-59-78.ec2.internal  Failed to pull image "docker.io/apptoto/wordpress:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for apptoto/wordpress, repository does not exist or may require 'docker login'
  Warning  Failed     23s (x2 over 35s)  kubelet, ip-192-168-59-78.ec2.internal  Error: ErrImagePull
  Normal   BackOff    11s (x3 over 35s)  kubelet, ip-192-168-59-78.ec2.internal  Back-off pulling image "docker.io/apptoto/wordpress:latest"
  Warning  Failed     11s (x3 over 35s)  kubelet, ip-192-168-59-78.ec2.internal  Error: ImagePullBackOff`

**Comment by marcosbc** [comment]
Hi @lance-hardy, I would say that it is because your pull secrets are wrong. Did you follow this guide for configuring the pull secrets? https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#create-a-secret-by-providing-credentials-on-the-command-line

**Comment by samgabrail** [comment]
hi @marcosbc thanks for your explanation here. I followed your instructions and re-built the container and called it: `samgabrail/wordpress:5`
when I run the container separately I can see the added `define('WP_CACHE', true);` line. However, when I run the helm chart, that line is not there. Not sure how it gets overwritten.
