### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yunkkyaa** [bitnami/bitnami-docker-wordpress#206]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
Hi, it seems this PR/Issue was created by mistake (also #205, #206, #207, #208 and #209). I am closing it due to its lack of content.
