### ISSUE TITLE
Unable to Mount Azure Premium Storage in Bitnami Wordpress Image

### ISSUE THREAD

**Issue by salingilbert** [bitnami/bitnami-docker-wordpress#213]
We are unable to Mount Azure Premium Storage in Bitnami Wordpress Image.

Below is the error that we see 

Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress'

Any thoughts/help is appreciated.

**Comment by miguelaeh** [comment]
Hi @salingilbert ,
Could you provide more information? How are you deploying the image? How are you mounting the volume?

**Comment by salingilbert** [comment]
Thank you for the quick response.
We are deploying the Bitnami Wordpress image as a container on App Services in Azure. 
We are trying to tying to mount a File System premium storage as Azure Storage Mount , in the path /bitnami
When we try to do this, we are getting the below error.
Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/wordpress'

**Comment by miguelaeh** [comment]
Hi @salingilbert ,
The Wordpress image is a root container so I would check to things. First, check if Azure is using a different user to deploy the image. And second, which are the mounted volume permissions.
