### ISSUE TITLE
Example of using composer.json?

### ISSUE THREAD

**Issue by mikoskinen** [bitnami/bitnami-docker-wordpress#215]
Thanks for the very well working image.

We're thinking of starting to use composer to handle the installation of the required Wordpress plugins. I wonder if there happens to be an example somewhere where this container is extended to contain a composer.json -file which takes care of the plugins/themes on startup?

The composer itself seems to be already installed in this image so it's just a matter of somehow running it.

Thank you in advance.

**Comment by andresbono** [comment]
Hi @mikoskinen, sorry but we didn't try to use composer to automate plugins/themes installation before.

Maybe you want to take a look at https://github.com/bitnami/bitnami-docker-wordpress#wp-cli-tool, it could be useful for your purpose. With the WP-CLI you should be able to install plugins and themes.

**Comment by mikoskinen** [comment]
Thanks for the quick reply. We ended up using WP-CLI and things seem to be running quite smoothly.

**Comment by andresbono** [comment]
That's great to hear, @mikoskinen!!
