### ISSUE TITLE
Allow setting extraWPConfigContent for nami from env

### ISSUE THREAD

**Issue by Arno500** [bitnami/bitnami-docker-wordpress#220]
**Description**

As in the `nami.json` file of the WP package:
```
"extraWPConfigContent":         {
            "description": "Extra content to add to wp-config.php",
            "default": ""
        },
```

But this entry is not in `/wordpress-inputs.json`, so it basically not accessible when seeding a WordPress website to the container.
As said in the main.js script of the package, I need it for W3 Total Cache and other things like disabling code editor:
```
// Add extra content to wp-config.php at the beginning (required by W3 Total Cache)
    if ($app.extraWPConfigContent) {
      $app.info('Appending extra configuration to wp-config.php');
      $file.append(confFile, $app.extraWPConfigContent, {atNewLine: true});
    }
```

Modifying the file directly in the volume should not be an option, we're building images containing our entire website excepted the uploads. This would break the purpose of a stateless image.

**Describe the results you expected:**

I want to be able to set an option in the WordPress Helm chart to add options to the `wp-config.yml` (via env or ConfigMap)
Thus, adding an env variable to the Docker container would be nice I think.

**Comment by andresbono** [comment]
Hi @Arno500, did you try by modifying [wordpress-inputs.json](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/wordpress-inputs.json) and rebuilding the image?

I think it would be good to add a configurable env-var for the `extraWPConfigContent` input, but in the meantime, you can just modify the `wordpress-inputs.json` file and let us know if it works for you.

**Comment by andresbono** [comment]
Hi @Arno500, the next release of the container will include a new environment variable `WORDPRESS_EXTRA_WP_CONFIG_CONTENT` that you might find useful.

**Comment by Arno500** [comment]
(sorry I did not have the time to test this. But thanks !)
