### ISSUE TITLE
Why add WP_PLUGIN_DIR to the config if the symlink is enough ?

### ISSUE THREAD

**Issue by Arno500** [bitnami/bitnami-docker-wordpress#221]
**Description**

When initializing the WP app with nami, the directive `WP_PLUGIN_DIR` is added to `wp-config.php` pointing to `thePersistDir + /wp-content/plugins` (in helpers.js):
```
$file.substitute(
    confFile,
    '/* That\'s all, stop editing! Happy publishing. */',
    `define('WP_PLUGIN_DIR', '${$app.persistDir}' . '/wp-content/plugins');\n`
    + '/* That\'s all, stop editing! Happy publishing. */\n'
  );
```
It should not be needed since nami already create a symlink to the wp-content folder (thus containing the plugins).
As said in my previous issue (#220), this prevents me from adding my plugins in `/opt/bitnami/wordpress/wp-content/plugins` to preseed my image, since WP will be forced to search them in `/bitnami/wordpress/wp-content/plugins`.

**Describe the results you expected:**

That the install script doesn't add this (I think?) uneeded line breaking some configurations.

**Comment by andresbono** [comment]
Hi @Arno500, look at https://github.com/bitnami/bitnami-docker-wordpress/issues/112. That's the reason why we are adding the `WP_PLUGIN_DIR` variable.

In any case, why can't you preseed the image with new plugins by placing them in `/opt/bitnami/wordpress/wp-content/plugins`?

What is the issue that you are finding?

**Comment by Arno500** [comment]
Oh yeah, I see now.

What I was trying to do was just seed our plugins by placing them in `/opt/bitnami/wordpress/wp-content/plugins`.
But the thing is, the installer will only copy them once to the volume. Any future addition or update (in our repo) will not be propagated.
Basically, we want to have the "cleanest  WP image", with only the uploads persisted. We update our plugins manually and we create our own themes.
I could sed into the /.nami/registry.json file to replace the persisted folders, but since the plugin folder is burried into the generated wp-config.php in the volume, we're stuck. Or we can add another sed, but this is too much of a "workaround".

**Comment by andresbono** [comment]
Hi @Arno500, are you creating a new container image every time you want to update the plugins?

Can you share the Dockerfile you are using?

**Comment by Arno500** [comment]
```
FROM bitnami/wordpress:5.2.2

## Initial Setup

ENV WORDPRESS_SKIP_INSTALL=yes
ENV WORDPRESS_SCHEME=https
ENV APACHE_HTTP_PORT_NUMBER=8080
ENV APACHE_HTTPS_PORT_NUMBER=8443

# Persist only what we want (!!! IMPORTANT !!! -> a conflict can happen with the folder that will be copied if not updated)
RUN sed -i 's/wp-content/wp-content\/uploads/g' /root/.nami/components/com.bitnami.wordpress/nami.json && sed -i 's/wp-content/wp-content\/uploads/g' /root/.nami/registry.json
RUN rm -rf /opt/bitnami/wordpress/wp-content/themes/* && rm -rf /opt/bitnami/wordpress/wp-content/plugins/*

RUN sed -i "s/\`define('WP_PLUGIN_DIR', '\${\$app.persistDir}' . '\/wp-content\/plugins');\\\n\`/''/" /root/.nami/components/com.bitnami.wordpress/helpers.js

# We want our rewrites before WordPress ones, so we need to adapt Apache config
RUN sed -i '/if htAccessOverrideNone/,/if/d' /root/.nami/components/com.bitnami.wordpress/templates/wordpress-https-vhost.conf.tpl && sed -i '/if htAccessOverrideNone/,/if/d' /root/.nami/components/com.bitnami.wordpress/templates/wordpress-vhost.conf.tpl
RUN sed -i '/DirectoryIndex index.html index.php/ a {{#if htAccessOverrideNone }}\nAllowOverride None\nInclude "{{htAccessConfLocation}}"\n{{/if}}' /root/.nami/components/com.bitnami.wordpress/templates/wordpress-https-vhost.conf.tpl && sed -i '/DirectoryIndex index.html index.php/ a {{#if htAccessOverrideNone }}\nAllowOverride None\nInclude "{{htAccessConfLocation}}"\n{{/if}}' /root/.nami/components/com.bitnami.wordpress/templates/wordpress-vhost.conf.tpl

# Copy things we want to keep static in the container
COPY ./public/wp-content/themes/ /opt/bitnami/wordpress/wp-content/themes/
COPY ./public/wp-content/mu-plugins/ /opt/bitnami/wordpress/wp-content/mu-plugins/
COPY ./public/wp-content/plugins/ /opt/bitnami/wordpress/wp-content/plugins/
COPY ./public/wp-content/languages/*.json /opt/bitnami/wordpress/wp-content/languages/
COPY ./deploy/prod/wordpress-htaccess.conf /opt/bitnami/wordpress/wordpress-htaccess.conf
```
Here is our Dockerfile. We use it along the Helm chart you provide for Wordpress by specifiying our image.

And yes, each time we update something (be it Wordpress, any plugin or our theme), we rebuild the image and upgrade via the chart.

**Comment by andresbono** [comment]
Hi @Arno500, we have been checking it, and we didn't find any easier workaround than the one you already did. Note that your use case is very particular and we don't want to make changes to the container image that would break it for other scenarios.

I hope you understand!

**Comment by Arno500** [comment]
Yes of course!
Breaking an image for everyone only to make it working for one person is not a good solution.
It's so annoying that WordPress needs so much workaround for everything...
