### ISSUE TITLE
Issue with loopback and REST API

### ISSUE THREAD

**Issue by PeteEdley-EdleyIT** [bitnami/bitnami-docker-wordpress#222]
**Description**

**Steps to reproduce the issue:**

1. Fresh install using 
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml
$ docker-compose up

2. Login and run site health

**Describe the results you received:**

The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

The REST API request failed due to an error.
Error: [] cURL error 6: Could not resolve host: blog.test1.local

Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: [] cURL error 6: Could not resolve host: blog.test1.local
**Describe the results you expected:**

to pass these tests
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:
Client: Docker Engine - Community
 Version:           19.03.7
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        7141c199a2
 Built:             Wed Mar  4 01:21:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.7
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       7141c199a2
  Built:            Wed Mar  4 01:19:56 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
(paste your output here)
```

- Output of `docker info`:
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.7
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.18-surface
 Operating System: Ubuntu 19.10
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.687GiB
 Name: peter-Surface-Pro-3
 ID: QUPJ:37AE:B5IE:25RF:DUGB:QE7L:BM6N:IOZ5:DL3N:YPJX:Y6X4:KDKC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```docker-compose version 1.21.0, build unknown
docker-py version: 3.4.1
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by PeteEdley-EdleyIT** [comment]
OK so got past this issue by adding
extra_hosts:
  - 'blog.test1.local:127.0.0.1'

to my docker-compose file.  But this now gives me the errors.

The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.

The REST API request failed due to an error.
Error: [] cURL error 28: Connection timed out after 10001 milliseconds

Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.

The loopback request to your site failed, this means features relying on them are not currently working as expected.
Error: [] cURL error 28: Connection timed out after 10001 milliseconds

**Comment by andresbono** [comment]
Hi @PeteEdley-EdleyIT, can you access to http://blog.test1.local/wp-json? Can you also do `curl localhost:8080/wp-json` inside the container?

Note that Apache is actually listening to the port 8080, while the docker-compose is making a redirection of the port from 80 to 8080 port:

https://github.com/bitnami/bitnami-docker-wordpress/blob/71cb0efc57d6500377a24939e19087240d537d7e/5/debian-10/docker-compose.yml#L14

The health checks that WordPress does are referring to port 80 but executing them inside the container. That's the post probable reason of the error messages. Those warnings shouldn't be an issue.

**Comment by PeteEdley-EdleyIT** [comment]
> can you access to http://blog.test1.local/wp-json? 

- **Yes this works**

> Can you also do `curl localhost:8080/wp-json` inside the container?

**This also works**

> Note that Apache is actually listening to the port 8080, while the docker-compose is making a redirection of the port from 80 to 8080 port:
> 
> The health checks that WordPress do are referring to port 80 but executing them inside the container. That's the post probable reason of the error messages. 

**It looks like this is correct**

> Those warnings shouldn't be an issue.

Unfortunately for me they are as I am trying to use [Oxygen Builder](https://oxygenbuilder.com/) which works 99% except for one feature that uses curl to the api and therefore isn't working.  So I guess my options are to build my own docker image based on bitnami but change apache to listen on port 80.

**Comment by PeteEdley-EdleyIT** [comment]
OK for further investigation I thought I would try the same on the basic official [wpdocker image](https://hub.docker.com/_/wordpress/) which does run on port 80 inside the image,  I get the same issue so looks like this is something else.

Will keep looking and report back here if i get it sorted.  In the meantime happy for any other suggestions.

**Comment by andresbono** [comment]
Thanks, @PeteEdley-EdleyIT.

**Comment by bd8392** [comment]
Is this resolved now? And if yes...how?

**Comment by andresbono** [comment]
Hi @bd8392, what is your specific issue?

**Comment by bd8392** [comment]
Hi =) I'm sorry it was related to my iptables...they where blocking port 80 and 443 on the host. This leads that wordpress coud'nt curl it's own apiand complained about it in website-health. These rules resolved it:
```
iptables -A INPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate ESTABLISHED -j ACCEPT

**Comment by andresbono** [comment]
Great! Thanks for sharing your solution!
