### ISSUE TITLE
Wierd permission Error on bitnami file (NOT EPERM kubesec Error)

### ISSUE THREAD

**Issue by secoldPrivate** [bitnami/bitnami-docker-wordpress#223]
The image I'm using is: bitnami/wordpress:5.3.2-debian-10-r29

When the container spins up and wordpress is 'ready'... I get an error 500.
Looking at the logs in:

/opt/bitnami/apache/logs/error_logs

I see this:

PHP Warning: require_once(/bitnami/wordpress/wp-config.php): failed to open stream: Permission denied in /opt/bitnami/wordpress/wp-load.php on line 37

PHP Fatal error: require_once(): Failed opening required '/opt/bitnami/wordpress/wp-config.php' (include_path='.:/opt/bitnami/php/lib/php') in /opt/bitnami/wordpress/wp-load.php on line 37

basically, the file wp-config.php in /opt/bitnami/wordpress/wp-config.php, doesn't have permissions.

Looking at the permissions:
-rw-rw-r-- 1 bitnami daemon 2898 Jan 24 17:22 wp-config.php

daemon already owns the file!

Besides what why is this file even being used? My wordpress install is in /bitnami/wordpress (NOT /opt/bitnami/wordpress)

If I do this:
chown -R bitnami:daemon /bitnami/wordpress

Now it works!
However if the container dies and restarts, it 500s again and this needs to be repeated.

What's going on here?

I didn't know /opt/bitnami/wordpress even existed until I got this 500 error, and went looking for the apache logs. I imported this wordpress website from a shared hosted website, and moved the wordpress files over manually to a volume and mounted that volume at /bitnami/wordpress

The website when it works renders the content from /bitnami/wordpress, and that works well so it is using those files

Why do I need to chown the files in the volume every time they are mounted, ortherwise it 500s?

**Comment by rafariossaa** [comment]
Hi,
  This is what I did:
- Create a dir data and set the permissions
```
$ mkdir data
$ chmod 777 data
```
- In the docker-compose.yaml add the directory created as wordpress volume:
```
...
  wordpress:
    image: 'bitnami/wordpress:5'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './data:/bitnami/wordpress'
...
```
- Start the container

You will have the wordpress files in `data` directory, there you can work normally but the files must belong to `1001:root`, so if you create new files and directories take this into consideration. If you already have an user is ID 1001 you will see that username instead.

```
$ ls -l data
total 8
-r--r----- 1 1001 root 3839 Mar 12 10:25 wp-config.php
drwxr-xr-x 4 1001 root 4096 Mar 12 10:25 wp-content
```

Regarding the `/opt/bitnami/wordpress/wp-config.php` file, if you get into the container, you can see that is a symlink to `/bitnami/wodpress/wp-config.php`.

```
wordpress@7015c5712d0a:/$ ls -lh /opt/bitnami/wordpress/
...
-rw-rw-r--  1 root      root 2.3K Jan 24 17:22 wp-comments-post.php
-rw-rw-r--  1 root      root 2.9K Jan 24 17:22 wp-config-sample.php
lrwxrwxrwx  1 wordpress root   32 Mar 12 10:12 wp-config.php -> /bitnami/wordpress/wp-config.php
lrwxrwxrwx  1 wordpress root   29 Mar 12 10:12 wp-content -> /bitnami/wordpress/wp-content
...
```

Could  you try this approach ?
