### ISSUE TITLE
Use $_ENV for definitions loading in wp-config.php

### ISSUE THREAD

**Issue by polRk** [bitnami/bitnami-docker-wordpress#224]
Can i add this code in **wp-config.php** ? 

```php
foreach ($_ENV as $key => $value) {
	$capitalized = strtoupper($key);
	if (!defined($capitalized)) {
		define($capitalized, $value);
	}
}
```

**Comment by polRk** [comment]
I want to add plugin https://github.com/humanmade/S3-Uploads. I need modify wp-config.php

**Comment by juan131** [comment]
Hi @polRk 

Thanks so much for the suggestion!

I'm closing this issue as a duplicate of https://github.com/bitnami/bitnami-docker-wordpress/issues/167
