### ISSUE TITLE
Add variable WORDPRESS_SKIP_ INIT_CONTENT

### ISSUE THREAD

**Issue by polRk** [bitnami/bitnami-docker-wordpress#225]
Do not install anything in wp-content folder. It useful feature in CI/CD. if your themes and plugins storage in github, you do not needed install garbage. Load only my files. In kubernetes, it means to skip prepareDataToPersist step.

**Comment by polRk** [comment]
REF https://github.com/bitnami/charts/issues/2050

**Comment by miguelaeh** [comment]
Hi @polRk ,
Thank you very much for sharing your use case, we already answered in the other thread so let's use only one to avoid duplications.
Regards.

**Comment by polRk** [comment]
Yep
