### ISSUE TITLE
Unable to change WP_SITEURL or WP_HOME without disabling site

### ISSUE THREAD

**Issue by rwalsh3711** [bitnami/bitnami-docker-wordpress#227]
**Description**

I'm pulling my hair out trying to figure out how to fix the URL on my deployed site.  I'm running the Wordpress image as described on a home-hosted Linux system.  I have a domain registered with GoDaddy that points back just fine.  

I've tried every option I came across for adjusting the URL but the result is always the same...no response from the site either internally or externally.

I've currently got my main site, monti100mileclub.com, up and running but you'll see that going to the site results in a public IP in the URL.  I've set up a test site to work with, test.monti100mileclub.com, to fiddle with.  Currently, the only changes made after bringing the site up was to modify the define lines in wp-config.php like this:

```
define('WP_SITEURL', 'http://test.monti100mileclub.com');
define('WP_HOME', 'http://test.monti100mileclub.com');
```

After making this modification I run a "docker-compose restart".

This was the most popular instruction that I found, however it doesn't work for me.  The site was responsive prior to the change, but not after.  Please advise!

**Steps to reproduce the issue:**

1. Start up wordpress per instructions (curl the docker-compose.yml and run docker-compose up -d)
2. Open a terminal to the wordpress container and modify wp-config.php with the correct WP_SITEURL and WP_HOME definitions.
3. Restart the containers with "docker-compose restart"

**Describe the results you received:**

The site is no long responsive either internally or externally.

**Describe the results you expected:**

The site is responsive externally using the linked domain name.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 4
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.4.3.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.5GiB
 Name: centos-lab.localhost
 ID: UUKI:AGEN:EILT:NV7I:MRWV:EX5Y:H3JC:NOJA:FWIQ:OF4V:PMMV:2MUC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: rwalsh3711
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.0.2k-fips  26 Jan 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Physical server running CentOS Linux release 7.7.1908 (Core)

**Comment by rafariossaa** [comment]
Hi @rwalsh3711 ,
   If you are starting the compose, changing the file and then restarting the compose the changes should be kept.
  You should be changing the file `/bitnami/wordpress/wp-config.php` as `/bitnami/wordpress` is preserved across restarts. 
   Are you changing this file ?

**Comment by rwalsh3711** [comment]
> Hi @rwalsh3711 ,
> If you are starting the compose, changing the file and then restarting the compose the changes should be kept.
> You should be changing the file `/bitnami/wordpress/wp-config.php` as `/bitnami/wordpress` is preserved across restarts.
> Are you changing this file ?

Hi @rafariossaa,

Yes, that is the file that I'm changing and I've confirmed that the modifications remained after restarting the contianers.

**Comment by rafariossaa** [comment]
Hi @rwalsh3711,
  What do you mean by "the site is not responsive" ? Are you able to reach the site but you are not able to browse across the site or you are not able to reach the main page?
  If the configuration in wordpress is right, we need to test it botton-up to try to see what is happening at different points. Maybe it is not a wordpress level.
  Also have into account that maybe you need to change data in the database as you are changing the site name. 
  But let's try this first, from the host you are running docker-compose:  `curl http://localhost/` . 
  What do you obtain ? You should get the main page or a redirection.
  Then try: `curl http://test.monti100mileclub.com`
  Also, in the wordpress logs you should see the requests made.
