### ISSUE TITLE
How do I control access by IP on apache?

### ISSUE THREAD

**Issue by kenta-watanabe-5098** [bitnami/bitnami-docker-wordpress#228]
**Description**

How to control access by IP on Bitnami container.

**Steps to reproduce the issue:**

1. [First Step]
Add this script to /opt/bitnami/apache/conf/httpd.conf
<Directory "/opt/bitnami/wordpress/">
    Require ip 127.0.xxx.xxx
    Require ip 127.0.xxx.xxx
    Require ip 127.0.xxx.xxx
</Directory>

2. [Second Step]
apache restart.
sudo /etc/init.d/bitnami restart apache

3. [and so on...]
I tried to access the URL from these IP.

**Describe the results you received:**

It doesn't work.

Access from these IP will be dinied.

**Additional environment details (AWS):**

I don't know what's wrong about this.

**Comment by dani8art** [comment]
Hi @kenta-watanabe-5098 could you try to follow any of these approaches https://github.com/bitnami/bitnami-docker-apache#configuration?

**Comment by kenta-watanabe-5098** [comment]
Hi @dani8art 
I'll try to this. thank you!
