### ISSUE TITLE
Unable to use install_packages

### ISSUE THREAD

**Issue by momon** [bitnami/bitnami-docker-wordpress#230]
Hello, I started having this issue about a month ago (with the 5.4.0 update).

I am pulling the image onto my custom dockerfile using:

```
FROM bitnami/wordpress:5.4.0
LABEL maintainer "Bitnami <containers@bitnami.com>"
```

And right after I install a few packages of my own for my development environment like so:

```
RUN install_packages unzip nano vim
```

But has been failing to build and it stops here:

```
Step 3/10 : RUN install_packages unzip nano vim
---> Running in 5d50680e65ca
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
apt failed, retrying
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
apt failed, retrying
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
Removing intermediate container 5d50680e65ca
The command '/bin/sh -c install_packages unzip nano vim' returned a non-zero code: 100
```

So I noticed that with 5.4.0 you added unzip already and thought that was the issue.  So I removed it from my command like so:

```
RUN install_packages nano vim
```

But this also fails:

```
Step 3/10 : RUN install_packages nano vim
---> Running in 6d07c4d3b021
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
apt failed, retrying
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
apt failed, retrying
[91mE: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)
[0m
Removing intermediate container 6d07c4d3b021
The command '/bin/sh -c install_packages nano vim' returned a non-zero code: 100
```

So I decided to go with apt-get instead and changed my command to:

```
RUN apt-get install nano vim -y --force-yes -qq
```

But I now get:

```
Step 3/10 : RUN apt-get install nano vim -y --force-yes -qq
---> Running in 13328a029715
[91mW: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
[0m
Removing intermediate container 13328a029715
The command '/bin/sh -c apt-get install nano vim -y --force-yes -qq' returned a non-zero code: 100
```

I ended up having to remove the line to install additional packages which I need on my application to get a successful build.

So I am a bit confused on why install_packages (which was working fine before) now has stopped working, am I using it incorrectly? what would be the correct way to install additional packages on my custom dockerfile?

Thanks!

**Comment by momon** [comment]
Ok, that last error message pointed me to a permission issue, so I've just changed my commands to use sudo and this seems to make a difference but I am now stuck on a different error:

```
Step 3/10 : RUN sudo install_packages nano vim
---> Running in cadc27686d3d
[91msudo: you do not exist in the passwd database
[0m
Removing intermediate container cadc27686d3d
The command '/bin/sh -c sudo install_packages nano vim' returned a non-zero code: 1
```

So I am guessing there are permission related issues here in executing subsequent commands on my dockerfile.

Would appreciate any pointers.

Thanks!

**Comment by momon** [comment]
Ok, I figured it out.  Checking at the readme I noticed this was added a couple of days ago:

https://github.com/bitnami/bitnami-docker-wordpress#why-use-a-non-root-container

And reading through that seemed to be what happened to me.  The short answer for anyone with a similar issue is that you need to now define the root user after you use the base image like so:

```
FROM bitnami/wordpress:5.4.0
LABEL maintainer "Bitnami <containers@bitnami.com>"
USER root
```

This brings me into a bit of a concern though, reading through your documents, using these root containers isn't ideal, but I do not see any other way to get custom packages installed using the base if root user isn't specified, so would appreciate any advise in case there is a different or more secure way to achieve this.

Thanks!

**Comment by juan131** [comment]
Exactly @momon !! The WP image was moved to a "non-root" approach recently, and it's non-root by default. Therefore, you need to apply the suggested workaround to perform privileged actions when customizing the image (see https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image):

```
FROM bitnami/wordpress
LABEL maintainer "Bitnami <containers@bitnami.com>"

## Install 'vim'
USER 0 # Required to perform privileged actions
RUN install_packages vim
USER 1001 # Revert to the original non-root user
```

In other words, you have to use the user `0` to perform privileged actions, and then restore the default user if you want to keep WP a "non-root" container.

**Comment by momon** [comment]
Much appreciate the confirmation.  I was able to sort things out, it was considerably more complex than just switching users because our script assumes root and that is part of the entry-point of our app but I just temporarily switched back to the root environment until I can figure out a different way of handling these tasks.

Thanks again!

**Comment by juan131** [comment]
You're welcome @momon ! Please do not hesitate to let us know if you require further help.

**Comment by jazzman809** [comment]
> Exactly @momon !! The WP image was moved to a "non-root" approach recently, and it's non-root by default. Therefore, you need to apply the suggested workaround to perform privileged actions when customizing the image (see https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image):
> 
> ```
> FROM bitnami/wordpress
> LABEL maintainer "Bitnami <containers@bitnami.com>"
> 
> ## Install 'vim'
> USER 0 # Required to perform privileged actions
> RUN install_packages vim
> USER 1001 # Revert to the original non-root user
> ```
> 
> In other words, you have to use the user `0` to perform privileged actions, and then restore the default user if you want to keep WP a "non-root" container.
____________
I know this is old but I keep getting stuck at the point below, even when using USER 0, after the label or before any RUN in the dockerfile. I even tried building the image without adding anything extra, just USER 0. I'm on a Windows 10 machine if that makes a difference. I don't have much use for the default plugins the image comes with, so I'm trying to add my own plugins from my computer, not plugins that are available online for public download. Error below:

 ---> Running in a568dde74c60
/bin/sh: 1: install_packages: not found
The command '/bin/sh -c install_packages ca-certificates curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps sudo tar unzip zlib1g' returned a non-zero code: 127

**Comment by momon** [comment]
> > Exactly @momon !! The WP image was moved to a "non-root" approach recently, and it's non-root by default. Therefore, you need to apply the suggested workaround to perform privileged actions when customizing the image (see https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image):
> > ```
> > FROM bitnami/wordpress
> > LABEL maintainer "Bitnami <containers@bitnami.com>"
> > 
> > ## Install 'vim'
> > USER 0 # Required to perform privileged actions
> > RUN install_packages vim
> > USER 1001 # Revert to the original non-root user
> > ```
> > 
> > 
> > In other words, you have to use the user `0` to perform privileged actions, and then restore the default user if you want to keep WP a "non-root" container.
> 
> I know this is old but I keep getting stuck at the point below, even when using USER 0, after the label or before any RUN in the dockerfile. I even tried building the image without adding anything extra, just USER 0. I'm on a Windows 10 machine if that makes a difference. I don't have much use for the default plugins the image comes with, so I'm trying to add my own plugins from my computer, not plugins that are available online for public download. Error below:
> 
> ---> Running in a568dde74c60
> /bin/sh: 1: install_packages: not found
> The command '/bin/sh -c install_packages ca-certificates curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps sudo tar unzip zlib1g' returned a non-zero code: 127

I had similar issues so I am sure I can help.  Most if not all of them were related to either bad permissions or the script itself lacking the executable bit (this is particularly relevant in windows) or I had the wrong ending line on the files.

The first issue you can address easily by explicitly specifying before the script runs in the dockerfile the correct permissions it should have (the right user).

The executable bit also has several ways around, but the easiest would also be to setup the right executable permissions (+x) right before the script starts.

The end of file or last line issue will depend on your working environment, depending on which IDE app you are using you will find an option for it.  It is essentially how the EOF is identified, there are different settings for windows and Linux.  Make sure you are using the LINUX EOF format (google can also help with this).

I'm 99% sure either fixing all 3 or one of these 3 is your issue as it was for me, so give it a whirl and let me know.

Cheers

**Comment by juan131** [comment]
Thanks so much for sharing your insights @momon  !! I'm sure they'll be very helpful for other users.

**Comment by Sfaraaah** [comment]
I’m having a lot of issues in that area too I need help

**Comment by juan131** [comment]
Hi @Sfaraaah 

Could you please more information about your issue? How can we reproduce it? Please share as much information as possible so we can understand it properly.

**Comment by jazzman809** [comment]
> Thanks so much for sharing your insights @momon !! I'm sure they'll be very helpful for other users.
> 
> > I even tried building the image without adding anything extra, just USER 0.
> 
> At which point did you add that user? Could you share your Dockerfile @jazzman809?

Sorry for the delay. The issue was with the permissions on Windows. I switched to my Mac then used USER 0 and was able to build the image with no errors. Thanks.

**Comment by juan131** [comment]
Hi @jazzman809 

You should be able to use both user 0, and any other arbitrary user in your Mac. It's true though, that it could be problematic on Windows environments, specially when building your custom image instead of reusing the exiting one.

**Comment by jazzman809** [comment]
> Hi @jazzman809
> 
> You should be able to use both user 0, and any other arbitrary user in your Mac. It's true though, that it could be problematic on Windows environments, specially when building your custom image instead of reusing the exiting one.

Hi @juan131 ,

See below for my Dockerfile. Notice how I added USER 0 after the LABEL and added my commands at the bottom. It wasn't working on a Windows environment but it built fine on Mac:

FROM docker.io/bitnami/minideb:buster
LABEL maintainer "Bitnami <containers@bitnami.com>"
USER 0
ENV BITNAMI_PKG_CHMOD="-R g+rwX" \
    HOME="/" \
    PATH="/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/apache/bin:/opt/bitnami/wp-cli/bin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/opt/bitnami/nami/bin:$PATH"

COPY prebuildfs /
# Install required system packages and dependencies
RUN install_packages ca-certificates curl gzip libaudit1 libbsd0 libbz2-1.0 libc6 libcap-ng0 libcom-err2 libcurl4 libexpat1 libffi6 libfftw3-double3 libfontconfig1 libfreetype6 libgcc1 libgcrypt20 libglib2.0-0 libgmp10 libgnutls30 libgomp1 libgpg-error0 libgssapi-krb5-2 libhogweed4 libicu63 libidn2-0 libjemalloc2 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 liblcms2-2 libldap-2.4-2 liblqr-1-0 libltdl7 liblzma5 libmagickcore-6.q16-6 libmagickwand-6.q16-6 libmcrypt4 libmemcached11 libmemcachedutil2 libncurses6 libnettle6 libnghttp2-14 libonig5 libp11-kit0 libpam0g libpcre3 libpng16-16 libpq5 libpsl5 libreadline7 librtmp1 libsasl2-2 libsqlite3-0 libssh2-1 libssl1.1 libstdc++6 libsybdb5 libtasn1-6 libtidy5deb1 libtinfo6 libunistring2 libuuid1 libx11-6 libxau6 libxcb1 libxdmcp6 libxext6 libxml2 libxslt1.1 libzip4 procps sudo tar unzip zlib1g
RUN /build/bitnami-user.sh
RUN /build/install-nami.sh
RUN bitnami-pkg install php-7.4.7-0 --checksum aaf2231876b7ebd7c40451f1d312ab2c7c1bef4d258446cc81fbfc3df82e532d
RUN bitnami-pkg unpack apache-2.4.43-4 --checksum e6929d8619f48976f9206bec14cb9634ebe8590225818eea12c27840617f53aa
RUN bitnami-pkg install wp-cli-2.4.0-0 --checksum 8095bdd2f96a137cb3f54836ad9deb90510b0927472e532f41e1708345432230
RUN bitnami-pkg unpack mysql-client-10.3.23-0 --checksum 7af3cead7a38670bed924fbc99e20c67f6244bb5a92642adb4ab6cd307aa9a5e
RUN bitnami-pkg install libphp-7.4.7-0 --checksum dec2da3c1b3dc2ed45379dcea9c3bc32778608034e627fd0a9cde258090e0c56
RUN bitnami-pkg unpack wordpress-5.4.2-2 --checksum d29de2b384f01e7a9660fab1bc0b4ecd3394c8dbfb12a1829a994a90f9d36222
RUN bitnami-pkg install tini-0.19.0-0 --checksum 9a8ae20be31a518f042fcec359f2cf35bfdb4e2a56f2fa8ff9ef2ecaf45da80c
RUN bitnami-pkg install gosu-1.12.0-0 --checksum 582d501eeb6b338a24f417fededbf14295903d6be55c52d66c52e616c81bcd8c
RUN apt-get update && apt-get upgrade -y && \
    rm -r /var/lib/apt/lists /var/cache/apt/archives
RUN ln -sf /dev/stdout /opt/bitnami/apache/logs/access_log && \
    ln -sf /dev/stderr /opt/bitnami/apache/logs/error_log

COPY rootfs /
ENV ALLOW_EMPTY_PASSWORD="no" \
    APACHE_ENABLE_CUSTOM_PORTS="no" \
    APACHE_HTTPS_PORT_NUMBER="8443" \
    APACHE_HTTP_PORT_NUMBER="8080" \
    BITNAMI_APP_NAME="wordpress" \
    BITNAMI_IMAGE_VERSION="5.4.2-debian-10-r8" \
    MARIADB_HOST="mariadb" \
    MARIADB_PORT_NUMBER="3306" \
    MARIADB_ROOT_PASSWORD="" \
    MARIADB_ROOT_USER="root" \
    MYSQL_CLIENT_CREATE_DATABASE_NAME="" \
    MYSQL_CLIENT_CREATE_DATABASE_PASSWORD="" \
    MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES="ALL" \
    MYSQL_CLIENT_CREATE_DATABASE_USER="" \
    MYSQL_CLIENT_ENABLE_SSL="no" \
    MYSQL_CLIENT_SSL_CA_FILE="" \
    NAMI_PREFIX="/.nami" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-10" \
    OS_NAME="linux" \
    PHP_MEMORY_LIMIT="256M" \
    SMTP_HOST="" \
    SMTP_PASSWORD="" \
    SMTP_PORT="" \
    SMTP_PROTOCOL="" \
    SMTP_USER="" \
    SMTP_USERNAME="" \
    WORDPRESS_BLOG_NAME="User's Blog!" \
    WORDPRESS_DATABASE_NAME="bitnami_wordpress" \
    WORDPRESS_DATABASE_PASSWORD="" \
    WORDPRESS_DATABASE_SSL_CA_FILE="" \
    WORDPRESS_DATABASE_USER="bn_wordpress" \
    WORDPRESS_EMAIL="user@example.com" \
    WORDPRESS_EXTRA_WP_CONFIG_CONTENT="" \
    WORDPRESS_FIRST_NAME="FirstName" \
    WORDPRESS_HTACCESS_OVERRIDE_NONE="yes" \
    WORDPRESS_HTACCESS_PERSISTENCE_ENABLED="no" \
    WORDPRESS_HTTPS_PORT="8443" \
    WORDPRESS_HTTP_PORT="8080" \
    WORDPRESS_LAST_NAME="LastName" \
    WORDPRESS_PASSWORD="bitnami" \
    WORDPRESS_RESET_DATA_PERMISSIONS="no" \
    WORDPRESS_SCHEME="http" \
    WORDPRESS_SKIP_INSTALL="no" \
    WORDPRESS_TABLE_PREFIX="wp_" \
    WORDPRESS_USERNAME="user"

RUN rm -rf /opt/bitnami/wordpress/wp-content

COPY ./wp-content /opt/bitnami/wordpress/wp-content

EXPOSE 8080 8443

USER 1001
ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "httpd", "-f", "/opt/bitnami/apache/conf/httpd.conf", "-DFOREGROUND" ]

But now I'm getting the output below when running the image, by itself (not using the chart yet). I'm mainly trying to replace the default wp-content file with my own:

Error executing 'postInstallation': EACCES: permission denied, rename '/opt/bitnami/wordpress/wp-content/.DS_Store' -> '/bitnami/wordpress/wp-content/.DS_Store'

Below is the command I'm using to run the image:

docker run -d --name my container \
-p 8181:8080 -p 8443:8443 \
--env MARIADB_HOST=mydbhost \
--env MARIADB_PORT_NUMBER=3306 \
--env WORDPRESS_DATABASE_NAME=myddname \
--env WORDPRESS_DATABASE_USER=mydbuser \
--env WORDPRESS_DATABASE_PASSWORD=mydbpass \
--env WORDPRESS_SKIP_INSTALL=yes \
--env WORDPRESS_TABLE_PREFIX=wp_ \
my-bit-wordpress:latest

**Comment by jazzman809** [comment]
@juan131  Actually, I figured the .DS_Store error, that file is added by MacOS automatically to folders. I added it to the dockerignore file and that took care of that. But now I'm getting a similar error with the index.php file inside the wp-content, as below, though I've added USER 0 right before the COPY command that copies the wp-content folder. These permission denied messages are kind of a killer. Is there a better way to do this without having to delete the default wp-content folder? See below:

Error executing 'postInstallation': EACCES: permission denied, rename '/opt/bitnami/wordpress/wp-content/index.php' -> '/bitnami/wordpress/wp-content/index.php'

**Comment by juan131** [comment]
Hi @jazzman809 

Why are you rebuilding the whole container instead of reusing the existing WP container? I mean, doing sth like this:

```
FROM docker.io/bitnami/wordpress

USER 0
RUN rm -rf /opt/bitnami/wordpress/wp-content
COPY ./wp-content /opt/bitnami/wordpress/wp-content
USER 1001
```

Please note that you'll have to adapt the permissions in the `/opt/bitnami/wordpress/wp-content/` folder after the `COPY` command so the user `1001` can manage them.
