### ISSUE TITLE
Hardcoded SSL port in apache config

### ISSUE THREAD

**Issue by momon** [bitnami/bitnami-docker-wordpress#232]
I just spent half my day troubleshooting a bunch of issues that have resulted after the non-root environment that has affected us and one in particular which feels like a bug is the Apache SSL port that can be defined in the dockerfile as per the documentation.

To reproduce this, use:

```
ENV APACHE_HTTP_PORT_NUMBER=80
ENV APACHE_HTTPS_PORT_NUMBER=443
EXPOSE 80 443
```

After building, port 80 on http works fine but port 443 is NOT inherited in wordpress-https-vhost.conf file.  Instead, it keeps: 8443

To evidence this, here is the file that resulted after building the container with the above ports:

```
momon@DESKTOP-D8J28R5:~$ kubectl exec *** -it -- cat /opt/bitnami/apache/conf/vhosts/wordpress-https-vhost.conf
AddType application/x-httpd-php .php
<VirtualHost 127.0.0.1:8443 _default_:8443>
  ServerAlias *
  SSLEngine on
  SSLCertificateFile "/opt/bitnami/apache/conf/bitnami/certs/server.crt"
  SSLCertificateKeyFile "/opt/bitnami/apache/conf/bitnami/certs/server.key"
  DocumentRoot /opt/bitnami/wordpress
  <Directory /opt/bitnami/wordpress>
    Options -Indexes +FollowSymLinks -MultiViews
    AllowOverride All
    Require all granted
    DirectoryIndex index.html index.php
    RewriteEngine On
    RewriteBase /
    RewriteRule ^index.php$ - [S=1]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . index.php [L]
  </Directory>
</VirtualHost>
```

This prevented all my deployments from working correctly as I rely on HTTPS.  My workaround was to mount the custom wordpress-https-vhost.conf file with the correct port definition onto the dockerfile and that worked nicely.

However, I shouldn't need to do that.  The file SHOULD pick up the correct https port.

The apache log on the failing pods was what pointed me to the issue.  It was returning this:

```
INFO  ==> Custom commands completed
[Tue Apr 07 19:01:20.755443 2020] [ssl:warn] [pid 13881] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 19:01:20.756116 2020] [ssl:warn] [pid 13881] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 19:01:20.787290 2020] [ssl:warn] [pid 13881] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 19:01:20.787991 2020] [ssl:warn] [pid 13881] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 19:01:20.805136 2020] [mpm_prefork:notice] [pid 13881] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.4 configured -- resuming normal operations
[Tue Apr 07 19:01:20.805393 2020] [core:notice] [pid 13881] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
10.28.228.2 - - [07/Apr/2020:19:01:49 +0000] "GET / HTTP/1.1" 200 45
```

Whereas a "working" pod was returning this:

```
INFO  ==> Custom commands completed
[Tue Apr 07 18:25:35.126053 2020] [ssl:warn] [pid 12734] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 18:25:35.126763 2020] [ssl:warn] [pid 12734] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 18:25:35.155348 2020] [ssl:warn] [pid 12734] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 18:25:35.155941 2020] [ssl:warn] [pid 12734] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 07 18:25:35.173085 2020] [mpm_prefork:notice] [pid 12734] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.4 configured -- resuming normal operations
[Tue Apr 07 18:25:35.173306 2020] [core:notice] [pid 12734] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
```

To be clear and to make sure I didn't miss anything, I copied over the entire conf folder from the working pod in the dockerfile:

```
# Started copy apache config files ...
COPY conf /opt/bitnami/apache/conf/
# Finished copy apache config files
```

But considering I had never modified any apache config before on any deployment and seeing the difference in the https vhost files from the working and the non working deployments I have assumed that the issue relies there.

Cheers.

**Comment by javsalgar** [comment]
Hi,

Could you also set the WORDPRESS_HTTP_PORT and WORDPRESS_HTTPS_PORT env vars? This should change the WordPress apache configuration.

**Comment by momon** [comment]
Did you mean like this?

```
# Expose Service Ports
ENV APACHE_HTTP_PORT_NUMBER=80
ENV APACHE_HTTPS_PORT_NUMBER=443
ENV WORDPRESS_HTTP_PORT=80
ENV WORDPRESS_HTTPS_PORT=443
EXPOSE 80 443
```

I am not seeing those variables documented anywhere on the readme, it doesn't look very clean but I understand that's subjective.

**Comment by javsalgar** [comment]
Hi,

Yes, I believe that we should make the same env var change both the Apache port and the Apache vhost. This should be a small change. Thanks for the feedback!

**Comment by momon** [comment]
It seems to have worked.  I agree it would feel more native as that is the sole purpose of the image (to run wordpress) so it would make sense that only one env per port is needed.

Thanks!

**Comment by javsalgar** [comment]
Thanks for the feedback. I will update the ticket when this feature is added.

**Comment by marcosbc** [comment]
Hi all, just wanted to let you know that WordPress now supports the `APACHE_HTTP_PORT_NUMBER` and `APACHE_HTTPS_PORT_NUMBER` which will override at runtime to the proper value.

Closing this issue, but let us know if you continue finding problems.
