### ISSUE TITLE
.htaccess persistence

### ISSUE THREAD

**Issue by v-six** [bitnami/bitnami-docker-wordpress#235]
As I originally opened https://github.com/bitnami/charts/issues/2294 in `bitnami/wordpress` helm chart, I think it's related to this repo too. 

--------

**Description**

Since I would like to let users manage their own wordpress, they need a proper `.htaccess` file to work with some plugins. The `.htaccess` file is working like a charm, but when the container reboot, the wordpress folder is reset (`/opt/bitnami/wordpress`) so does my `.htaccess` file.

I am aware of performance and security reasons why the `.htaccess` file is disabled by default. But as it's a very common practice in wordpress, I think it should be supported or at least possible to work with a persisted `.htaccess` file.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tested some solutions :
- Custom image ✔️ :
The unique viable solution I found is to change the app endpoint to add a script executed each time the container starts. But I expect a more "official" solution.

- Post init script :x: :
I tried earlier to add a script in `/docker-entrypoint-init.d` in order to add my `.htaccess` (https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh#L5). I was hoping for it to run every time the container starts, but it's not, thoose scripts run only once after wordpress installation 😞.

Is there a way to have my `.htaccess` file persisted and restored like the wordpress sources ?

**Comment by dani8art** [comment]
Hi @v-six that sounds good, we are going to open an internal task in order to evaluate and handle it. Unfortunately, we can not give you an ETA but we will keep you updated. Thank you so much for your feedback.
