### ISSUE TITLE
Max_Upload

### ISSUE THREAD

**Issue by Berndinox** [bitnami/bitnami-docker-wordpress#241]
First of all, that might not be an issue, but after searching for 2 hourse a proper solution i think, ofc it is an issue. There are too many different links, docs, sources,.. very confusing.

I just would like to set the **max_upload filesize**. 
That should be a absolut default setting and might be linked so that user can acutally find it.

May someone got an solution, thanks!

**Comment by sebas932** [comment]
I´m here because I use to add a vhost file with the following parameters that worked properly, but this does not work anymore.
![image](https://user-images.githubusercontent.com/4406128/81127450-dafe6380-8f03-11ea-96be-6d2d50f51642.png)

Is there another way to set up these parameters?

**Comment by dani8art** [comment]
Hi, 

did you try using this https://github.com/bitnami/bitnami-docker-php-fpm#add-additional-ini-files?

**Comment by Berndinox** [comment]
After digging into, i found a "easy" solution for adding costum upload limits while installing bitnami/wordpress via helm:

1) Create **Configmap** ("_configmap.yaml_")

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini
  namespace: <NAMESPACE>
  labels:
    app: <WP-LABEL>
data:
  php-custom.ini: |
    max_file_uploads = 256M
    post_max_size = 256M
    max_execution_time = 120
    max_input_time = 120
```
2) **Modify values.yaml** and add:

```
extraVolumeMounts: 
  - name: php-ini
    subPath: conf.d
    mountPath: /opt/bitnami/php/etc/conf.d

extraVolumes:
  - name: php-ini
    configMap:
      name: php-ini
```

3) Bring it all together:
kubectl create ns <NAMESPACE>
kubectl apply -f configmap.yaml
helm install <WP-NAMEY> bitnami/wordpress --namespace <NAMESPACE>

4) Verify inside WP: e.g. PHP Info Plugins

**Comment by dani8art** [comment]
Nice, thank @Berndinox for the contribution!

**Comment by yelhouti** [comment]
@Berndinox with your exact example. subpath in configmap doesn't work please remove it for the next person
