### ISSUE TITLE
Impossible connecting to WP from a browser running on docker last version

### ISSUE THREAD

**Issue by plhmk** [bitnami/bitnami-docker-wordpress#243]
**Description**

<Can not connet to the WP running on docker, last version

**Steps to reproduce the issue:**
Generate from this .yml file

version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    image: 'bitnami/wordpress:latest'
    ports:
      - '8080:80'
    volumes:
      - 'wordpress_data:/bitnami'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=bitnami_wordpress
      - MYSQL_CLIENT_CREATE_DATABASE_USER=bn_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

**Describe the results you received:**
All run correctly as reported from Portainer, but impossible connect from browser

http://localhost:8080/
Error, unable to connect by the browser (on the same PC running docker)

**Describe the results you expected:**
The connection of WP Welcome page

**Additional information you deem important (e.g. issue happens only occasionally):**

issue everithing

**Version**

- Output of `docker version`:

 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 23:42:35 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 22:48:33 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

(paste your output here)
```

- Output of `docker info`:
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.844GiB
 Name: srvubuntu20
 ID: QKYK:4MY6:C4VF:ULWJ:DLSE:YS6S:ZU65:GM6G:NUF7:US35:FISD:ROP3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```
(paste your output here)
```
t
- Output of `docker-compose version` (if applicable):

docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

![Schermata del 2020-05-05 18-12-14](https://user-images.githubusercontent.com/49727957/81089099-388eb200-8efc-11ea-8219-ac3f22296aa7.png)
![Schermata del 2020-05-05 18-13-00](https://user-images.githubusercontent.com/49727957/81089103-39bfdf00-8efc-11ea-9b3f-7fb379923f16.png)

```t
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

This is due to WordPress being a non-root container. Could you try forwarding it to port 8080 in the container instead of 80?

**Comment by plhmk** [comment]
Hello,
Is ok, resolved now.
Thanks, regards

**Comment by javsalgar** [comment]
Awesome! Do not hesitate to open a new ticket if you find other issues
