### ISSUE TITLE
Urgent Help Needed ... wp-config.php ERROR

### ISSUE THREAD

**Issue by sam-dm** [bitnami/bitnami-docker-wordpress#245]
I have a helm wordpress installed on amazon eks cluster. I decided to run W3 cache plugin and everything went down since. My wp-config.php is corrupted and I cannot get the pod running again. I cannot access the files nor anything. Need a way to use the default wp-config.php to rescue my work.
There is nothing in helm that changes the wordpress wp-config.php even after trying to upgrade. The log file is as follows:
```
[0m
[0m[1mWelcome to the Bitnami wordpress container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-wordpress[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-wordpress/issues[0m
[0m
[0m[38;5;3mWARN [0m ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
wordpre INFO  WordPress has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at tamara-db-cluster.cluster-cl7lni22iufj.eu-central-1.rds.amazonaws.com:3306
mysql-c INFO  MySQL server listening and working at tamara-db-cluster.cluster-cl7lni22iufj.eu-central-1.rds.amazonaws.com:3306
wordpre INFO  Upgrading WordPress Database ...
Error executing 'postInstallation': PHP Parse error:  syntax error, unexpected '=', expecting end of file in /bitnami/wordpress/wp-config.php on line 66
```
I posted a support issue in the main thread of helm and I did not receive an answer.

Could anyone help me to resolve this issue.

**Comment by miguelaeh** [comment]
Hi @sam-dm ,
A way to change your configuration could be to exec into the pod and edit the file, it will be stored into the volume, as all pods should be using the same volume for configuration.
if you cannot edit the file because your pod is non-root and you get permission errors, try to mount the same volume that WordPress pods are mounting into a new pod, exec into it, and edit file, it should be stored then with your changes.
Once you edited the file restart the WordPress pods in other to take the changes.

**Comment by sam-dm** [comment]
Hi, This would be nice if the pod was ready. The idea is the pod is in crashloopbackoff and is inaccessible. The docker image is not mounted and is in pause status. The helm chart does not update the file nor clear it. Need to apply a configmap is it possible for wp-config.php?

**Comment by miguelaeh** [comment]
I am afraid you cannot override it using a configmap.
But you should be able to mount that volume into another temporary pod that you can create manually, it doesn't have to belong to the WordPress release, just use the same PVC that is using your release.

**Comment by sam-dm** [comment]
Ok let me check this solution. If you can support by sending some example commands to do the above that would be great.

**Comment by miguelaeh** [comment]
Create a file with the folowing content:
```
apiVersion: v1
kind: Pod
metadata:
  name: recover
spec:
  containers:
  - name: recover
    image: bitnami/minideb
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: my-volume
      mountPath: /tmp/wp-config
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: <your-pvc>
```

Find the PVC that is returning your WordPress volume and put the name at `<your-pvc>`. Then execute:
```
kubectl apply -f <filename>
```

The pod should be deployed, now exec into it:
```
kubectl exec -it recover bash
```

Then go to `/tmp/wp-config` and there should be the content of your WordPress volume. You can edit it there.
Once you edit it, restart the rest of the Pods.
I hope this will be useful for you

**Comment by sam-dm** [comment]
That is working fine. I was able to mount the pod and change the wp-config.php file. You made it sound simple. Others are looking at ways in which to work on their php files that are throwing errors and no one has mentioned they can mount the pod and update their php files. That is strange. This will be very helpful for others. Thank you so much.

**Comment by miguelaeh** [comment]
Hi @sam-dm ,
I am glad you solved it, don't hesitate in ask again if you find any issues.
Regards.
