### ISSUE TITLE
Extend bitnami/wordpress image

### ISSUE THREAD

**Issue by smace** [bitnami/bitnami-docker-wordpress#246]
Hello,

Following your example to extend bitnami/wordpress with vim package installation fails

**Steps to reproduce the issue:**

1. Create Dockerfile

FROM bitnami/wordpress
LABEL maintainer "Bitnami <containers@bitnami.com>"

USER 0 # Required to perform privileged actions
RUN install_packages vim
USER 1001 # Revert to the original non-root user

2. docker build .

**Describe the results you received:**

Sending build context to Docker daemon  49.66kB
Step 1/5 : FROM bitnami/wordpress
 ---> 772e44f0cf14
Step 2/5 : LABEL maintainer "Bitnami <containers@bitnami.com>"
 ---> Using cache
 ---> 9b86d00bfb0c
Step 3/5 : USER 0 # Required to perform privileged actions
 ---> Using cache
 ---> 3afbb97c8620
Step 4/5 : RUN install_packages vim
 ---> Running in 066fb029186e

linux spec user: unable to find user 0 # Required to perform privileged actions: no matching entries in passwd file

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.39 (downgraded from 1.40)
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018
```

**Comment by javsalgar** [comment]
Hi,

It seems that the comments are being added to the USER section. Could you just leave
```
USER 0
```

and
```
USER 1001
```

**Comment by smace** [comment]
Hi,

Thank you for you time, it's working without comments, I didn't see the trailing '#' after UID...

**Comment by javsalgar** [comment]
Awesome! Do not hesitate to open a new ticket if you find more issues
