### ISSUE TITLE
MySQL connection error after upgrading from 5.2.4 to 5.4.1

### ISSUE THREAD

**Issue by RationalAnimal** [bitnami/bitnami-docker-wordpress#247]
**Description**

Upgraded from bitnami wordpress image 5.2.4 to 5.4.1. Now getting this error when trying to connect to AWS RDS MySQL (this separate instance is unchanged):

```
ERROR 2026 (HY000): SSL connection error: unable to get issuer certificate
```

This error is happening both from the Wordpress itself, and also happens if I use a command in a script that runs in the docker image BEFORE Wordpress is launched. The same command worked in 5.2.4

**Steps to reproduce the issue:**

1. Start with a bitnami image that has "FROM bitnami/wordpress:5.2.4". Have a script in the script that runs before wordpress starts up that has a mysql command, e.g.:

```
mysql --user $ADMIN_WORDPRESS_DATABASE_USER -p$ADMIN_WORDPRESS_DATABASE_PASSWORD --host $ADMIN_MARIADB_HOST $WORDPRESS_DATABASE_NAME --port $MARIADB_PORT_NUMBER --ssl-ca /rds-ca-2019-us-east-1.pem < selectallusers.sql
```

2. Change the custom image to use "FROM bitnami/wordpress:5.4.1", rebuild, redeploy. Now get the error:

```
ERROR 2026 (HY000): SSL connection error: unable to get issuer certificate
```

**Describe the results you received:**

Got the error:
```
ERROR 2026 (HY000): SSL connection error: unable to get issuer certificate
```

Continued to work correctly as it did with version 5.2.4

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens EVERY TIME on 5.4.1 and NEVER on 5.2.4

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
MySQL: AWS RDS, Engine/Version: mysql - 5.7.25

**Comment by juan131** [comment]
Hi @RationalAnimal 

Did you set the `WORDPRESS_DATABASE_SSL_CA_FILE` environment variable as described [here](https://github.com/bitnami/bitnami-docker-wordpress#connect-wordpress-docker-container-to-an-existing-database)? Please note that would be mandatory for WordPress to configure the MySQL client correctly. 

Please also set the `MYSQL_CLIENT_ENABLE_SSL` and `MYSQL_CLIENT_SSL_CA_FILE` environment variables to configure the MySQL client correctly (see https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/mysql-client-inputs.json#L11)

I guess you're mounting the public key (`rds-ca-2019-us-east-1.pem`) on both containers (`5.2.4` and `5.4.`) the same way. It looks like with the key.

I can see similar issues on MariaDB connector, but they're pretty old: https://jira.mariadb.org/browse/CONC-190

It could be related to the MySQL client that's shipped in the WordPress image, and some incompatibility with the MySQL 5.7 server you're using. As you can see in the **docker-compose.yaml** below, we're testing this WP image with MySQL 8 at this very moment:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/docker-compose-mysql.yml

So I would recommend you to migrate your database to a MySQL 8 RDS server.

**Comment by RationalAnimal** [comment]
I've tried everything described above except for upgrading to MySQL 8 and it didn't work.  I can't easily use MySQL8 because it hasn't been cleared yet for use in my workplace (we have very strict  enterprise security). I have also tried the exact MySQL client included in the bitnami image and it can connect to the instance of MySQL 5.7 without any issues.
So, can you please check the configuration of the image to see if there are any parameters (possibly default ones) that have changed or been added from/to the previous version that may be using SSL differently?

**Comment by juan131** [comment]
Hi @RationalAnimal 

Could you share the command or the Docker Compose you're using to launch your WP container?

> So, can you please check the configuration of the image to see if there are any parameters (possibly default ones) that have changed or been added from/to the previous version that may be using SSL differently?

The parameter used to configure SSL hasn't been modified in two years. I don't it's related to that.

**Comment by juan131** [comment]
Hi @RationalAnimal 

As you can see, we're shipping different versions of the client between these WP versions:

```console
$ docker run --rm bitnami/wordpress:5.2.4 mysql --version

(...)

mysql  Ver 15.1 Distrib 10.3.20-MariaDB, for Linux (x86_64) using readline 5.1
```

```console
$ docker run --rm bitnami/wordpress:5.4.1 mysql --version

(...)

mysql  Ver 15.1 Distrib 10.3.23-MariaDB, for Linux (x86_64) using readline 5.1
```

You can try building the latest WP version using the previous MySQL client. You just need to substitute the line below:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/Dockerfile#L16

```diff
- RUN bitnami-pkg unpack mysql-client-10.3.23-0 --checksum 7af3cead7a38670bed924fbc99e20c67f6244bb5a92642adb4ab6cd307aa9a5e
+ RUN bitnami-pkg unpack mysql-client-10.3.20-0 --checksum 743aff4ba4858e3eb7d3e10ec9d7ae08b5ddbbb3257cfbbba73062991605e5e6
```

**Comment by RationalAnimal** [comment]
The problem turned out to be the permissions on the ssl cert file. In the old version, the root user was used and was able to access this file. The new non-root user couldn't. Changing the permissions on the file fixed the issue.

**Comment by juan131** [comment]
Yes that could be the reason since WP is not a root container anymore. I'm very glad you were able to identify the issue @RationalAnimal 

Thanks so much for sharing the solution. I will close this issue, but please feel free to reopen it if you requirer further help.

**Comment by RationalAnimal** [comment]
@juan131 Please reopen this issue. I was actually wrong - I was pointing to the older version of the Bitnami image, that's why it worked, not because I changed the permissions on the ssl file.
Looking at similar issues online, I can see that which ports are open may affect this. Specifically, people are saying to leave port 443 open. I believe that Bitnami has changed which ports it's using between these two versions. Can you please list which ports were open before and which ones have been changed to new ones?
Thank you

**Comment by juan131** [comment]
Hi @RationalAnimal 

This container uses the port **8443** instead of **443** by default since it's a non-root container and, therefore, it cannot use privileged ports.

**Comment by RationalAnimal** [comment]
@juan131 One problem that I see is that if I use 5.4.1 image as the base (and add a few things to it) then the user specified (i.e. 1001) does not exist!! When I log into the container, and do whoami I get "cannot find name for user ID 1001". When I look in /etc/passwd I can see that there is a bitnami user (with the ID 1000) but there is no 1001 user.

**Comment by juan131** [comment]
Hi @RationalAnimal 

That's something expected. This container is compatible with arbitrary UIDs, which means you can run the container using any UID you want, e.g.:

```
$ docker run --user 1234 bitnami/wordpress
```

This is very important to be compatible with some K8s platforms such as Openshift, since these platforms use random UIDs to deploy the containers by default. 

Since we cannot assume the UID of the user that will be running the container, we cannot add it to `/etc/passwd` but it doesn't affect WordPress nor Apache.

**Comment by Sfaraaah** [comment]
Can you explain to me what the user you’re talking about like that you ID because if you tell me is it username and password

**Comment by Sfaraaah** [comment]
$ docker run --user 1234 bitnami/wordpress

**Comment by RationalAnimal** [comment]
Hi @Sfaraaah 
I am referring to the user that is specified on line 76 of your own Dockerfile:
https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/Dockerfile#L76
When  my container starts, it's running as this user.

**Comment by juan131** [comment]
Correct, please do not confuse the system user (the Linux system user used to start the services) with the WP user used to login in the WP site.

**Comment by RationalAnimal** [comment]
@juan131 I am confused by your last comment - where did I confuse the two users? I have always been talking about the system user. The problem that I am describing occurs BEFORE WordPress even starts up.

**Comment by juan131** [comment]
@RationalAnimal my las comment was for @Sfaraaah due to this comment:

> Can you explain to me what the user you’re talking about like that you ID because if you tell me is it username and password

I know you're referring to the system user.

**Comment by RationalAnimal** [comment]
@juan131 I've been able to resolve the issue by using different cert files from Amazon. Rather than using us-east-1 specific pem files, I can connect using either "root" or "bundled" pem files. The puzzling part is that the "us-east-1" pem file works with 5.2.4 version but not 5.4.1. However, I've already spent many days debugging this and I don't have the time to figure out why that is so.

**Comment by juan131** [comment]
Hi @RationalAnimal 

I'm very glad you could finally solved the issue, and thanks so much for sharing your insights. It's weird that one certificate works with one version, while it fails with the other, but thanks anyway. Other users facing similar issues will benefit from your investigation.
