### ISSUE TITLE
livenessProbe and readinessProbe check for wp-login.php

### ISSUE THREAD

**Issue by sam-dm** [bitnami/bitnami-docker-wordpress#248]
Changing the path of wp-login and wp-admin using plugin results in failure of livenessprobe and readinessprobe with pod not running. 

The following is the error after wordpress initialization is sucessful:

[Tue May 19 21:21:50.696429 2020] [mpm_prefork:notice] [pid 71] AH00163: Apache/2.4.43 (Unix) OpenSSL/1.1.1d PHP/7.4.5 configured -- resuming normal operations
[Tue May 19 21:21:50.696457 2020] [core:notice] [pid 71] AH00094: Command line: 'httpd -f /opt/bitnami/apache/conf/httpd.conf -D FOREGROUND'
192.168.86.229 - - [19/May/2020:21:22:18 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:22:28 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:22:38 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:22:48 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.81.236 - - [19/May/2020:21:22:58 +0000] "\x16\x03\x01\x02" 400 226
192.168.86.229 - - [19/May/2020:21:22:58 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:08 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:18 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:28 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:38 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:47 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:48 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:57 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:23:58 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.81.236 - - [19/May/2020:21:24:07 +0000] "\x16\x03\x01\x02" 400 226
192.168.86.229 - - [19/May/2020:21:24:07 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:08 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:17 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:18 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:27 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:28 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
192.168.86.229 - - [19/May/2020:21:24:37 +0000] "GET /wp-login.php HTTP/1.1" 404 39008
[Tue May 19 21:24:37.546242 2020] [mpm_prefork:notice] [pid 71] AH00169: caught SIGTERM, shutting down

Is there a way to change the wp-login path and file without the liveness and readiness probes not failing?

**Comment by javsalgar** [comment]
Hi,

I think this can be fixed by allowing custom liveness and readiness probes in the chart, so you can change the path of the liveness probe without issues.

I will update the ticket when I have more details about this.

**Comment by javsalgar** [comment]
Hi, I created this PR https://github.com/bitnami/charts/pull/2625
