### ISSUE TITLE
Unable to customize base image

### ISSUE THREAD

**Issue by tnsholding** [bitnami/bitnami-docker-wordpress#251]
Trying to create Wordpress image with preloaded and activated plugins/themes, but can't seem to get this working in Azure AKS.
Downloading zip files as part of Docker file and then doing unzip+activation in ENTRYPOINT script.

The image seems to work fine locally with docker-compose, but I'm getting 'authentication failure' errors when running the image in Azure AKS cluster - logs from pod:
```
nami    INFO  wordpress successfully initialized
INFO  ==> Starting wordpress...
INFO  ==> Unzipping preloaded plugins and themes...
Done unzipping preloaded plugins and themes.
INFO  ==> Activating plugins...
Password: su: Authentication failure
```

**Steps to reproduce the issue:**

Docker file:
```
FROM bitnami/wordpress:5.4.1

USER 0 

COPY scripts /

# Adjust script permissions
RUN chown root:root /test-entrypoint.sh
RUN chmod a+x /test-entrypoint.sh

# here we download the plugins and themes we need to add to the image
RUN bash download-extra.sh

ENTRYPOINT [ "/test-entrypoint.sh" ]
CMD [ "httpd", "-f", "/opt/bitnami/apache/conf/httpd.conf", "-DFOREGROUND" ]
```

test-entrypoint.sh has the excact code from base image 'app-entrypoint.sh' and then code to unzip and activate plugins added at the end:

```
#!/bin/bash -e

. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "httpd" ]]; then
    . /apache-init.sh
    . /wordpress-init.sh
    nami_initialize apache mysql-client wordpress
    info "Starting wordpress... "
    . /post-init.sh
fi

# copy pre-loaded themes and plugins to wp-content
info "Unzipping preloaded plugins and themes... "
unzip -o -q /tmp/buddypress.6.0.0.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip -o -q /tmp/bulk.1.0.10.zip -d /opt/bitnami/wordpress/wp-content/themes
unzip -o -q /tmp/hello-elementor.2.3.0.zip -d /opt/bitnami/wordpress/wp-content/themes
echo "Done unzipping preloaded plugins and themes."

# activate plugins and themes here
info "Activating plugins... "
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bbpress'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate gambit'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate buddypress'
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp theme activate hello-elementor'
info "Done activating plugins."

exec tini -- "$@"
```

In AKS I'm using the standard Helm chart to deploy (https://github.com/bitnami/charts/tree/master/bitnami/wordpress/#installing-the-chart ) - just replacing the image with my own image.

Any idea why I get permission errors when running in AKS (but not locally in docker-compose)?

**Comment by juan131** [comment]
Hi @tnsholding 

```
Password: su: Authentication failure
```

You cannot use `su daemon -s ...` since there's no configuration defined for the user **daemon** in the `/etc/sudoers` file. Therefore, you need to download the plugins as `root`, and then do the corresponding chown/chmod to adapt the permissions for `daemon` user.

---

That said, I wouldn't download/unpack the plugins/themes during the initialization. Even if you solve the issue with sudo you're obtaining. The reason, every time the container is started it'll try to download them and that will make it very slow and error-prone. 

Instead, download them at "build time" so your image already packages them.

**Comment by tnsholding** [comment]
Thanks for replying. 

I already download the zip files during image build (in step "RUN bash download-extra.sh"). 
I only unzip and (try to) activate during initialization. 
I couldn't unzip to wp-content during image build, as I then got other errors in initialization - SYMLINK already existing (seems to be an error related to Azure that hasn't been solved yet - see https://github.com/bitnami/bitnami-docker-ghost/issues/79).
Is there any workaround for this on Azure?

Could you point out how exactly I would correctly activate the plugins in the initialization phase - what user and/or chown/chmod would be necessary? - haven't been able to figure this out yet.

**Comment by javsalgar** [comment]
Hi,

This is strange, if our container is working with AKS without any modification, I do not know what exact changes are happening to cause the issue you mention. Do you have a Dockerfile where you unpack the plugins at build time?

**Comment by tnsholding** [comment]
Just moved the unzip from initialization (test-entrypoint.sh) to build stage (download-extra.sh):

```
#!/bin/bash
echo "Downloading extra plugins and themes..."
curl -o /tmp/buddypress.6.0.0.zip https://downloads.wordpress.org/plugin/buddypress.6.0.0.zip
curl -o /tmp/bulk.1.0.10.zip https://downloads.wordpress.org/theme/bulk.1.0.10.zip
curl -o /tmp/hello-elementor.2.3.0.zip https://downloads.wordpress.org/theme/hello-elementor.2.3.0.zip

# MOVED FROM test-entrypoint.sh TO HERE - UNPACK AT IMAGE BUILD TIME
# copy pre-loaded themes and plugins to wp-content
echo "Unzipping preloaded plugins and themes... "
unzip -o -q /tmp/buddypress.6.0.0.zip -d /opt/bitnami/wordpress/wp-content/plugins
unzip -o -q /tmp/bulk.1.0.10.zip -d /opt/bitnami/wordpress/wp-content/themes
unzip -o -q /tmp/hello-elementor.2.3.0.zip -d /opt/bitnami/wordpress/wp-content/themes
echo "Done unzipping preloaded plugins and themes."
```

Docker file itself is the same as listed above in the first entry. 
When deploying this image to AKS I get the following error in logs:

```
Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing wordpress
wordpre INFO  ==> Preparing Varnish environment
wordpre INFO  ==> Preparing Apache environment
wordpre INFO  ==> Preparing PHP environment
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at wordpress001-mariadb:3306
mysql-c INFO  MySQL server listening and working at wordpress001-mariadb:3306
wordpre INFO  Preparing WordPress environment
Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'
```

**Comment by juan131** [comment]
Hi @tnsholding 

> Could you point out how exactly I would correctly activate the plugins in the initialization phase - what user and/or chown/chmod would be necessary?

The 1st thing I would do is to recover the original WP user (`1001`) that you changed in your Dockerfile so the container is executed as `1001:0`:

```diff
RUN bash download-extra.sh

+ USER 1001

ENTRYPOINT [ "/test-entrypoint.sh" ]
```

As you can check, by default that user has writing permissions in the `wp-content` folder since the root group has permissions on it. Therefore, it should be able to uncompress the plugins.

```
$ ls -la /bitnami/wordpress/wp-content/
total 20
drwxr-xr-x  4 1001 root 4096 Jun 15 07:28 .
drwxrwxr-x  3 root root 4096 Jun 15 07:28 ..
-rw-rw-r--  1 1001 root   28 Jun 15 07:28 index.php
drwxr-xr-x 12 1001 root 4096 Jun 15 07:28 plugins
drwxr-xr-x  5 1001 root 4096 Jun 15 07:28 themes
```

Regarding how to activate them, you can use the WP CLI:

```console
$ wp help plugin
NAME

  wp plugin

DESCRIPTION

  Manages plugins, including installs, activations, and updates.

SYNOPSIS

  wp plugin <command>

SUBCOMMANDS

  activate              Activates one or more plugins.
  deactivate            Deactivates one or more plugins.
  delete                Deletes plugin files without deactivating or uninstalling.
  get                   Gets details about an installed plugin.
  install               Installs one or more plugins.
  is-active             Checks if a given plugin is active.
  is-installed          Checks if a given plugin is installed.
  list                  Gets a list of plugins.
  path                  Gets the path to a plugin or to the plugin directory.
  search                Searches the WordPress.org plugin directory.
  status                Reveals the status of one or all plugins.
  toggle                Toggles a plugin's activation state.
  uninstall             Uninstalls one or more plugins.
  update                Updates one or more plugins.
  verify-checksums      Verifies plugin files against WordPress.org's checksums.
```

**Comment by tnsholding** [comment]
Thanks for the input. Using 'User 1001'. Everything works fine locally with Docker-compose, but still get error when deploying the image to Azure:

`Error executing 'postInstallation': EEXIST: file already exists, symlink '/bitnami/wordpress/wp-content' -> '/opt/bitnami/wordpress/wp-content'`

**Comment by tnsholding** [comment]
If I postpone the unzipping to initialization, I can get past the above error. But I would really like to be able to unzip at image build time, so I hope there is a solution to get this working on Azure AKS.

When unzipping in the initialization phase I still get errors trying to run 'wp plugin activate' as described in my original issue post. I'm struggling to figure out what user should be doing this. 
I have tried the following:

```
su daemon -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bbpress'
 or 
su 1001 -s /bin/bash -c '/opt/bitnami/wp-cli/bin/wp plugin activate bbpress'
```
but getting errors like:
`su: user bitnami:bitnami does not exist`

**Comment by juan131** [comment]
Hi @tnsholding  

You don't need to do use `su 1001 -s /bin/bash -c `, you're already the user `1001`. Therefore. execute the WP CLI directly:

```
/opt/bitnami/wp-cli/bin/wp plugin activate bbpress
```

**Comment by tnsholding** [comment]
Thanks. I got it working now. 
I still had to wait with the unzipping until the initialization phase. This seems to be an error on Azure still not resolved.

**Comment by juan131** [comment]
I saw you also commented at https://github.com/bitnami/bitnami-docker-wordpress/issues/230, please let's try to follow the conversation there to avoid confusion. Thanks in advance.
