### ISSUE TITLE
GD or Imagick library missing affecting the webp image conversion.

### ISSUE THREAD

**Issue by margach** [bitnami/bitnami-docker-wordpress#255]
**Description**

Plugins that are responsible for the conversion of images from png and other formats to webp are breaking because the container lacks the ```GD``` or ```Imagick`` library.

**Steps to reproduce the issue:**

1. Install the WebP Converter for Media plugin
 
**Describe the results you received:**

On your server is not installed GD or Imagick library, or installed extension does not support WebP format.

This is happening on the Wordpress bitnami image

**Comment by beltran-rubo** [comment]
Hi,

The current GD version enabled in PHP is:
```
GD Support => enabled
GD Version => bundled (2.1.0 compatible)
```
Could you please check if that version is compatible with the WebP Converter plugin?

If not, "imagick" PHP extension is also included but not enabled by default. It is possible to enable it with the following command:

```
sed -i 's/;extension = imagick/extension = imagick/' /opt/bitnami/php/etc/php.ini
```

```
$ php -i | grep magick
imagick
imagick module => enabled
imagick module version => 3.4.4
imagick classes => Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel
```

**Comment by margach** [comment]
Thank you, I will enable this
