### ISSUE TITLE
Adding ads.txt file and making it accessable

### ISSUE THREAD

**Issue by margach** [bitnami/bitnami-docker-wordpress#256]
**Description**

I want to add an ```ads.txt``` file at my root domain and access it at ```mysite.com/ads.txt```.
I added the file under  ```opts/bitnami/wordpress/ads.txt``` and when I try to access the file in the browser, tells me not found.

**Steps to reproduce the issue:**

1. Create ads.txt file and add it at root ```opts/bitnami/wordpress/ads.txt```
2. Access it on the browser
3. Redirects to not found

**Describe the results you received:**

Redirects to not found

**Describe the results you expected:**

 loading the file and its contents in the browser.

**Additional information you deem important (e.g. issue happens only occasionally):**

Using Helm chart of Wordpress bitnami image
Running in Kubernetes.

**Comment by marcosbc** [comment]
@margach It is possible to do that by mounting the `ads.txt` file to `/opt/bitnami/wordpress/ads.txt` by changing your `docker-compose.yml` in the following way:

```diff
@@ -14,6 +14,7 @@
       - '80:8080'
       - '443:8443'
     volumes:
+      - ./ads.txt:/opt/bitnami/wordpress/ads.txt
       - 'wordpress_data:/bitnami/wordpress'
     depends_on:
       - mariadb
```

I tested it locally and it worked. Maybe it failed for you because you were mounting to `opts/bitnami` instead of `/opt/bitnami`.

**Comment by marcosbc** [comment]
To mount the file in the chart, you would need to use the `extraVolumeMounts` or `extraVolumes` properties in [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/wordpress/values.yaml#L144).

**Comment by margach** [comment]
I am not using docker-compose, I am running the helm chart, I am running the image in Kubernetes and using a volume as well.
The volume is mounted in the pod at ```/bitnami/wordpress``` wordpress data and I added the file under ```/opt/bitnami/wordpress/ads.txt```. still says not found.

**Comment by marcosbc** [comment]
@margach In the case of a chart, you would need to set the `extraVolumeMounts` or `extraVolumes` like mentioned above, to mount the `/opt/bitnami/wordpress/ads.txt` file.

If it does not work for you, could you share you configuration? Specifically the changes performed to the `values.yaml` file so we can inspect if there's something wrong with it.
