### ISSUE TITLE
Missing slash on url causes 8080 redirect

### ISSUE THREAD

**Issue by momon** [bitnami/bitnami-docker-wordpress#263]
I am 90% sure this is an nginx-ingress issue more so than this specific image but since the behavior only started showing when we switched to the non root environment on port 8080 and 8443 instead of 80 and 443 I figured I could get some help in debugging it.

I've been through pretty much all related issues on nginx-ingress documentation and past issues and a few pointers they have but none seem to solve this, so I started looking at bitnami wordpress just in case something was missed.

Long story short, if you try to access:

https://domain.com/wp-admin it tries to redirect to http://domain.com:8080/wp-admin/

if instead you try to access: 

https://domain.com/wp-admin/ it works as expected (so the ending slash appears to be mandatory:

```
C:\Users\jlope\AppData\Local\Google\Cloud SDK>curl https://domain.com/wp-admin
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://domain.com:8080/wp-admin/">here</a>.</p>
</body></html>

C:\Users\jlope\AppData\Local\Google\Cloud SDK>curl https://domain.com/wp-admin/
```

The latter works as expected.  The former fails.

**Comment by joancafom** [comment]
Hi @momon 

Thanks for opening the issue! If I understood it right, your problem is that on a port mapping `80:8080`, the redirection does not seem to work. Am I right? The redirection when trying to access to the URL without the trailing slash seems to be the expected behaviour to me. When you were using the non-root container, the mapping more likely was `80:80`, so it should have worked without you noticing.

A workaround for this would be to change the mapping to `8080:8080` and I assume it would work again. However, I do not see this a big flaw, you can still access using the complete URL.

Let me know your thoughts about this, thanks!

**Comment by torgus** [comment]
+1, i have the same problem, any update?

**Comment by juan131** [comment]
Hi @torgus 

I have a some questions to understand the exact scenario you're using:

- Are you using the `bitnami/wordpress` or the `bitnami/wordpress-nginx` image?
- Are you using a NGINX Reverse Proxy to redirect your requests to the WordPress containers?
- Are you running the container with the default non-root user?
- Are you using Docker Compose locally using port-mapping or did you deploy the containers on a different server/machine?

**Comment by torgus** [comment]
> Hi @torgus
> 
> I have a some questions to understand the exact scenario you're using:
> 
> * Are you using the `bitnami/wordpress` or the `bitnami/wordpress-nginx` image?

I have the problem on both of them.

https://site/wp-admin causes redirect to http://site:8080/wp-admin/ and does not work.
> * Are you using a NGINX Reverse Proxy to redirect your requests to the WordPress containers?
Yes, im using nginx to do ssl termination, config like:

location / {
                    proxy_pass http://127.0.0.1:8081;
                    proxy_set_header Upgrade           $http_upgrade;
                    proxy_set_header Connection        "upgrade";
                    proxy_set_header Host              $host;
                    proxy_set_header X-Real-IP         $remote_addr;
                    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto $scheme;
                    proxy_set_header X-Forwarded-Host  $host;
                    proxy_set_header X-Forwarded-Port  $server_port;

        }

    listen 443 ssl; # managed by Certbot
> * Are you running the container with the default non-root user?

yes, 1001 uid.

> * Are you using Docker Compose locally using port-mapping or did you deploy the containers on a different server/machine?

I deployed manually:

docker run -d --name Wordpress \
  -p 127.0.0.1:8081:8080 \
  --env MARIADB_HOST=******* \
  --env WORDPRESS_DATABASE_USER=****** \
  --env WORDPRESS_DATABASE_NAME=******* \
  --env WORDPRESS_DATABASE_PASSWORD='************' \
  --env WORDPRESS_SCHEME=https \
  --env WORDPRESS_RESET_DATA_PERMISSIONS=yes \
  --network wordpress-network \
  --volume /home/docker/dockershared/wordpress:/bitnami/wordpress \
  --volume /home/docker/dockershared/wordpress-server-block.conf:/opt/bitnami/nginx/conf/server_blocks/wordpress-server-block.conf \
  bitnami/wordpress-nginx:latest


Thanks!

**Comment by juan131** [comment]
Hi @torgus 

It seems you're mounting a custom **wordpress-server-block.conf** in the `wordpress-nginx` container. Could you share it?
