### ISSUE TITLE
WORDPRESS_EXTRA_WP_CONFIG_CONTENT not working

### ISSUE THREAD

**Issue by deantheiceman** [bitnami/bitnami-docker-wordpress#264]
**Description**

My container has the variable $WORDPRESS_EXTRA_WP_CONFIG_CONTENT set but my wp-config.php is not updated

**Comment by javsalgar** [comment]
Hi,

Are you setting it after first boot? I'm afraid it currently works only at first boot, otherwise you'll need to manually edit it.

**Comment by deantheiceman** [comment]
@javsalgar yes I'm setting it after first boot using this helm chart https://github.com/bitnami/charts/issues/3466

In the docker container on kubernetes we're not able to modify the wp-config.php as the container does not run as root. Is there any other options?

**Comment by javsalgar** [comment]
It is non-root but AFAIK you could do a chmod +w to the file, edit it and then restore the permissions. Did you try that?
