### ISSUE TITLE
robots.txt persistence

### ISSUE THREAD

**Issue by lwj5** [bitnami/bitnami-docker-wordpress#268]
**Description**

Similar to .htaccess persistence in #235. robots.txt should be persisted, if not robots.txt will be empty on a new instance.

**Steps to reproduce the issue:**

1. Start instance, generate robots.txt
2. Restart instance

**Describe the results you received:**

No robots.txt.

**Describe the results you expected:**

robots.txt to be available to every instance and synced on every replica.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
-
```

- Output of `docker info`:

```
-
```

- Output of `docker-compose version` (if applicable):

```
-
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @lwj5 Thanks for the suggestion, we think it should be good to have an env var like `WORDPRESS_EXTRA_FILES_TO_PERSIST` so you can use it like:
```
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_EXTRA_FILES_TO_PERSIST=robots.txt
```

```
$ docker exec -ti container_wordpress_1 ls -la /bitnami/wordpress/
total 16
drwxrwxr-x 3 root root 4096 Oct  5 10:25 .
drwxrwxr-x 1 root root 4096 Oct  5 10:19 ..
-rw-r--r-- 1 1001 root    0 Oct  5 10:25 .initialized
-rw-r--r-- 1 1001 root    0 Oct  5 10:25 robots.txt
-r--r----- 1 1001 root 4033 Oct  5 10:25 wp-config.php
drwxr-xr-x 4 1001 root 4096 Oct  5 10:25 wp-content
```

Would it fit your requirements?

**Comment by lwj5** [comment]
Hey @dani8art,

Yes, absolutely. I think that’s a good idea as it offers a lot of flexibility. 

Thanks!

**Comment by webdz9r** [comment]
This is dumb no one is doing anything about this
