### ISSUE TITLE
How do I change php.ini config?

### ISSUE THREAD

**Issue by gauravarora** [bitnami/bitnami-docker-wordpress#27]
I am using a theme that requires certain changes to run correctly but I can't figure out how I can change the `php.ini` file. Is there a volume I can mount to change it?

**Comment by sameersbn** [comment]
The above referenced commit should allow you to mount the `/bitnami/php` directory, thereby allowing you to customize the `php.ini` configuration.

The changes have been submitted for and should be landing soon. Will keep this thread updated with the status.

Thanks for reporting.

**Comment by gauravarora** [comment]
Oh wow, thanks a ton @sameersbn. I don't need upstream changes, I just use your image. :)
