### ISSUE TITLE
How to force this image to recreate wp-config.php?

### ISSUE THREAD

**Issue by acim** [bitnami/bitnami-docker-wordpress#270]
I already have running Wordpress container in Kubernetes and I want to subsequently set SMTP parameters, but I don't know how to force the container to recreate wp-config.php from environment variables?

**Comment by rafariossaa** [comment]
Hi,
  If you are using the chart, you can upgrade the chart and set the SMTP parameters you need.

**Comment by acim** [comment]
Are you sure about this? The only thing I see is that environment variables get set, but neither wp-config.php nor funcions.php gets changed. So, Wordpress chart can just modify environment variables but then container should have code to reconfigure, but I don't see this happens.

**Comment by rafariossaa** [comment]
Hi,
 Sorry, yes you are right, it can't be done with upgrading. This kind of parameters are only set in the first boot, so in this case you will need to launch a new deployment and import your data there.

**Comment by acim** [comment]
This would be a nice feature if you can implement in the future, so I am closing this. Thank you.

**Comment by rafariossaa** [comment]
Hi,
  You are welcome.
