### ISSUE TITLE
error installing h2o - unable to write to any folders including /opt

### ISSUE THREAD

**Issue by rajabhathor** [bitnami/bitnami-docker-wordpress#272]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dani8art** [comment]
Hi @rajabhathor could you share a bit more context so we can try to reproduce it?

- How are you deploying wordpress? docker command, docker-compose, kubernetes?
- Which is your configuration? env vars and files
