### ISSUE TITLE
dirname() return relative path

### ISSUE THREAD

**Issue by nvthuong1996** [bitnami/bitnami-docker-wordpress#277]
**Description**

**Steps to reproduce the issue:**

1. setup wordpress
2. setup flatsome theme
3. Error load resource

flatsome code where issuse happend
```
$this->plugin_path = trailingslashit( $this->cleanFilePath( dirname( __FILE__ ) ) );
$relative_url = str_replace( $this->cleanFilePath( get_template_directory() ), '', $this->plugin_path );
$this->plugin_url = trailingslashit( get_template_directory_uri() . $relative_url );
```

log
```
plugin_path = /bitnami/wordpress/wp-content/themes/flatsome/inc/admin/envato_setup/
get_template_directory = /opt/bitnami/wordpress/wp-content/themes/flatsome/
relative_url = /bitnami/wordpress/wp-content/themes/flatsome/inc/admin/envato_setup/
plugin_url = /wp-content/themes/flatsome/bitnami/wordpress/wp-content/themes/flatsome/inc/admin/envato_setup/
```
expect
```
$this->plugin_path = /opt/bitnami/wordpress/wp-content/themes/flatsome/inc/admin/envato_setup/
```

if dirname(__FILE__) return absolute path instead relative path the problem will be solved

I think this is a matter of context when wordpress run. Could this cause conflict with wordpress plugins?

**Comment by FraPazGal** [comment]
Hello @nvthuong1996,

The folder `/opt/bitnami/wordpress/wp-content/` has a symlink to `/bitnami/wordpress/wp-content/`, so there shouldn't be any issue with the paths. From what I saw in the [theme's shop page](https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319?license=regular&open_purchase_for_item_id=5484319&purchasable=source&ref=UX-themes), the theme only has support for up to wordpress 5.5 and our latest image contains wordpress 5.6. Does the problem persist if you use an image with a previous version?

**Comment by nvthuong1996** [comment]
I will try setup flattsome theme in wordpress 5.5. Thank you

**Comment by marcosbc** [comment]
Hi @kalonya, is this causing any specific issue with a theme? Could you describe it?

If the issue is related to a failing `require`, you should be able to workaround that by setting the environment variable `WORDPRESS_DATA_TO_PERSIST=/opt/bitnami/wordpress` to a new deployment.

In any case, I'd suggest to check with the theme author, as they may be able to solve this in the plugin. Note that the WordPress application itself does not have any issue loading symlinks.
