### ISSUE TITLE
[Question] Customizing the Dockerfile to Install a WordPress Site via Composer

### ISSUE THREAD

**Issue by ChexWarrior** [bitnami/bitnami-docker-wordpress#279]
**Description**
Hello,  I have a question about some customizations I've made that enables me to install a [WP site via Composer](https://composer.rarst.net/).  However before I get to the question I'd like to give some background info: 

I've setup my own Dockerfile that uses Bitnami's WP Dockerfile as a base like so:

```Dockerfile
FROM composer:2 AS builder

WORKDIR /usr/src/app

COPY composer.* ./
COPY custom_wp_theme custom_wp_theme

RUN composer install --no-dev -o && \
  mv wp-content/plugins/* web/wp-content/plugins && \
  mv custom_wp_theme web/wp-content/themes

FROM bitnami/wordpress:5.6.1

COPY --from=builder /usr/src/app/web/ web/

USER root

RUN cp -a web/* /opt/bitnami/wordpress && \
  chown -R 1001 /opt/bitnami/wordpress

USER 1001
```

The Dockerfile installs my plugins and themes (as well as moves a custom theme) into a web directory, then copies this directory into Bitnami's image.  I then copy the contents of that directory to where the Bitnami image has already installed it's own WP core files.  I know that in the fully built and running Bitnami's WordPress image the wp-content directory is symlinked to `/bitnami/wordpress/wp-content`, and after my customized image builds all the plugins and themes I previously copied are symlinked as well, however I can't find any documentation that says this is intended. I'm assuming this operation occurs during the `nami initialize wordpress` step that gets started by this command `nami_initialize apache mysql-client wordpress` in the `app-entrypoint.sh` file.  I can't seem to find any details about how the nami wordpress package is initialized (maybe i missed it?)  **Can anyone verify that placing plugins and themes in the /opt/bitnami/wordpress directory before the container actually runs is intended and safe?**

Thank you

**Comment by marcosbc** [comment]
Hi @ChexWarrior, what you mention is correct and perfectly safe. We recommend [extending the image](https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image), like you did, for advanced customizations.

During the `nami_initialize` step, the initialization will persist the content in the `wp-content` directory by copying it to `/bitnami/wordpress/wp-content`, and replace the folder with a symlink to the persisted volume. When you recreate the container, only the last part will happen (replacing the folder with symlink). The intention behind this is that you don't lose plugins after recreating the container.

Let us know if you have any other questions!

**Comment by ChexWarrior** [comment]
Thanks for the quick reply!
