### ISSUE TITLE
Feature request: PHP 8 + openlitespeed

### ISSUE THREAD

**Issue by krakazyabra** [bitnami/bitnami-docker-wordpress#282]
Hello! Wordpress is working on litespeed webserver in 120 times faster. Also, wordpress supports php8.
Will be nice to see alternative to usual nginx/apache + php7.

**Comment by migruiz4** [comment]
Hi @krakazyabra ,

Thank you for your feature request, I will split my answer in two parts:

- Regarding PHP 8, according to this blogpost https://make.wordpress.org/core/2020/11/23/wordpress-and-php-8-0/ Wordpress 5.6 could be run using it, but it is still not fully stable with PHP 8 as plugins, themes and others could present issues.
  
  > It also should be acknowledged that WordPress is never used in isolation (without any theme or plugins), so WordPress itself being able to run on PHP 8 does not indicate “full” compatibility.
  >
  > The state of PHP 8 support within the broader ecosystem (plugins, themes, etc.) is impossible to know. For that reason, WordPress 5.6 should be considered “beta compatible” with PHP 8.

  At the moment, we will probably wait until it is fully stable to use PHP 8 + WordPress, whenever that happens we will consider upgrading it based on users' needs and improvements of PHP 8.

- I have created an internal task to evaluate adding a new image using [OpenLiteSpeed Web Server](https://github.com/litespeedtech/openlitespeed) similar to `bitnami/bitnami-docker-wordpress-nginx`. 
  Any information or links you could share regarding OpenLiteSpeed improvements versus the other solutions we already provide would be helpful.

**Comment by krakazyabra** [comment]
Hi @migruiz4 
I've already made some kind of application, using php8, ols, wordpress and your bitnami/wordpress charts, you can find it [here](https://github.com/krakazyabra/wordpress-ols-php8-helm)

**Comment by migruiz4** [comment]
Awesome, thank you for sharing!
