### ISSUE TITLE
Question: ioncube loader and source guardian extension

### ISSUE THREAD

**Issue by Ja7ad** [bitnami/bitnami-docker-wordpress#283]
hi

1. How to add extension **ioncube loader** and **source guardian**?
2. Mounted Wordpress files can writeable via FTP in Host and access via ftp?

**Comment by juan131** [comment]
Hi @Ja7ad 

> How to add extension ioncube loader and source guardian?

I guess you want to automat this process, right? You have two options to do so:

- Extend the WP image, see: https://github.com/bitnami/bitnami-docker-wordpress#extend-this-image
- Download/install the plugins during the initialization. To do so, mount your custom scripts at `/docker-entrypoint-init.d` and they will be executed during the 1st boot of the container, see https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh

> Mounted Wordpress files can writeable via FTP in Host and access via ftp?

The WordPress container image does not include a FTP server. Therefore, this method isn't allowed to install plugins.
