### ISSUE TITLE
How do you edit files like .htaccess once the chart is released?

### ISSUE THREAD

**Issue by PhilParisot** [bitnami/bitnami-docker-wordpress#288]
What is the conventional way to do this? I'd like to use a GUI if possible.

**Comment by miguelaeh** [comment]
Hi @PhilParisot ,
You can configure the htaccess using the following parameter https://github.com/bitnami/charts/blob/ca6416a749421e8b062ae09134d890d00299000c/bitnami/wordpress/values.yaml#L188

**Comment by PhilParisot** [comment]
Hey @miguelaeh thanks for the reply! Can I modify the file after the release of the helm chart or will it only work before?

**Comment by miguelaeh** [comment]
Hi @PhilParisot ,
It seems that you will need just to perform a Helm upgrade of the release with the new content and it should work
