### ISSUE TITLE
How to choose what to persist under /bitnami/wordpress?

### ISSUE THREAD

**Issue by gabbler97** [bitnami/bitnami-docker-wordpress#292]
Currently, the wp-content and wp-config.php are persistent under /bitnami/wordpress. What should I do if  I want all the files from the /opt/bitnami/wordpress to be persisted?

I've tried the this:
https://github.com/bitnami/bitnami-docker-wordpress/issues/204

I've also tried to modify the WORDPRESS_DATA_TO_PERSIST environment variable but doesn't work.

Please help me with this issue! 
Regards

**Comment by juan131** [comment]
Hi @gabbler97 

Why do you want to persist the whole application? You will break compatibility with updating WordPress by simply replacing the WordPress container image with the latest one.

> I've also tried to modify the WORDPRESS_DATA_TO_PERSIST environment variable but doesn't work.

Did you try that during the 1st boot of the container? Or did you add the environment variable after the volume attached to persist data was already populated?

**Comment by gabbler97** [comment]
Hi @juan131! Thank you for replying!

I tried to migrate a WordPress page from a virtual machine simply overwriting the wp-content directory and making an SQL restore to the database. After that, the plugins appeared in the wp-admin but the page showed only the basic theme and content:
![image](https://user-images.githubusercontent.com/58025292/118497112-104bad00-b725-11eb-8dae-b57a7c8bd73e.png)


I thought if I persist the wp-admin, wp-includes, etc. It solves everything.
 

I set it in Kubernetes after the volume was attached in the Rancher platform with RKE.
![image](https://user-images.githubusercontent.com/58025292/118498300-2b6aec80-b726-11eb-8f29-281e3b9e41d2.png)


I've also tried modifying the entrypoint.sh like this:

`if [[ -f "/bitnami/wordpress/.migrated" ]]; then
    echo Wordpress migration is detected.
    # remove files: wp-admin, wp-load.php, wp-settings.php, wp-login, wp-includes to create symlinks
    echo 'verystrongpasswd' | sudo -S rm -rf /opt/bitnami/wordpress/wp-admin/
    echo wp-admin is deleted
    echo 'verystrongpasswd' | sudo -S rm -f /opt/bitnami/wordpress/wp-load.php
    echo wp-load.php is deleted
    echo 'verystrongpasswd' | sudo -S rm -f /opt/bitnami/wordpress/wp-settings.php
    echo wp-settings.php is deleted
    echo 'verystrongpasswd' | sudo -S rm -f /opt/bitnami/wordpress/wp-login.php
    echo wp-login.php is deleted
    echo 'verystrongpasswd' | sudo -S rm -rf /opt/bitnami/wordpress/wp-includes/
    echo wp-includes is deleted
	echo 'verystrongpasswd' | sudo -S ln -sfn /bitnami/wordpress/wp-admin /opt/bitnami/wordpress/wp-admin
    echo 'verystrongpasswd' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-admin
    echo symlink is created for wp-admin
	echo 'verystrongpasswd' | sudo -S ln -sfn /bitnami/wordpress/wp-settings.php /opt/bitnami/wordpress/wp-settings.php
    echo 'verystrongpasswd' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-settings.php
    echo symlink is created for wp-settings.php
	echo 'verystrongpasswd' | sudo -S ln -sfn /bitnami/wordpress/wp-load.php /opt/bitnami/wordpress/wp-load.php
    echo 'verystrongpasswd' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-load.php
    echo symlink is created for wp-load.php
	echo 'verystrongpasswd' | sudo -S ln -sfn /bitnami/wordpress/wp-includes /opt/bitnami/wordpress/wp-includes
    echo 'verystrongpasswd' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-includes
    echo symlink is created for wp-includes
	echo 'verystrongpasswd' | sudo -S ln -sfn /bitnami/wordpress/wp-login.php /opt/bitnami/wordpress/wp-login.php
    echo 'verystrongpasswd' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-login.php
    echo symlink is created wp-login.php
fi`
But this resulted the following issue:
Success: WordPress database already at latest db version 49752.
wordpress 13:26:55.19 DEBUG ==> Not resetting file permissions in persisted volume
wordpress 13:26:55.20 INFO  ==> ** WordPress setup finished! **
Wordpress migration is detected.
/opt/bitnami/scripts/wordpress/entrypoint.sh: line 33: sudo: command not found

**Comment by gabbler97** [comment]
Hi @juan131 ! Thank you for replying!

I wanted to migrate a WordPress site from Virtual Machine to a Kubernetes deployment in Rancher. I overwrote the wp-content directory on the persistent volume with my own and made a MYSQL restore on the database. After that, the plugins of the original site appeared on mywebsite.com//wp-admin/plugins.php but that's all. The webpage only shows the default theme and content like: 
![image](https://user-images.githubusercontent.com/58025292/118522060-ef428680-b73b-11eb-833b-73e366087d20.png)


I've added the environment variable after attaching the volume by adding it to my YAML file in Kubernetes (Rancher Platform with RKE cluster):
![image](https://user-images.githubusercontent.com/58025292/118522153-0aad9180-b73c-11eb-9d55-77bc6e3e817d.png)
But my task failed succesfully.

I thought if I use the original wp-config.php , wp-includes , wp-login.php, wp-admin  , etc. files the problem will be solved.
I modified the /bitnami/5/debian-10/rootfs/opt/bitnami/scripts/wordpress/entrypoint.sh in the weekend and looks like this:

#!/bin/bash

# shellcheck disable=SC1091

set -o errexit
set -o nounset
set -o pipefail
# set -o xtrace # Uncomment this line for debugging purpose

# Load WordPress environment
. /opt/bitnami/scripts/wordpress-env.sh

# Load libraries
. /opt/bitnami/scripts/libbitnami.sh
. /opt/bitnami/scripts/liblog.sh
. /opt/bitnami/scripts/libwebserver.sh

print_welcome_page

if [[ "$1" = "/opt/bitnami/scripts/$(web_server_type)/run.sh" || "$1" = "/opt/bitnami/scripts/nginx-php-fpm/run.sh" ]]; then
    info "** Starting WordPress setup **"
    /opt/bitnami/scripts/"$(web_server_type)"/setup.sh
    /opt/bitnami/scripts/php/setup.sh
    /opt/bitnami/scripts/mysql-client/setup.sh
    /opt/bitnami/scripts/wordpress/setup.sh
    /post-init.sh
    info "** WordPress setup finished! **"
fi

echo ""
exec "$@"


if [[ -f "/bitnami/wordpress/.migrated" ]]; then
    echo Wordpress migration is detected.
    # remove files: wp-admin, wp-load.php, wp-settings.php, wp-login, wp-includes to create symlinks
    echo 'verystrongpassword' | sudo -S rm -rf /opt/bitnami/wordpress/wp-admin/
    echo wp-admin is deleted
    echo 'verystrongpassword' | sudo -S rm -f /opt/bitnami/wordpress/wp-load.php
    echo wp-load.php is deleted
    echo 'verystrongpassword' | sudo -S rm -f /opt/bitnami/wordpress/wp-settings.php
    echo wp-settings.php is deleted
    echo 'verystrongpassword' | sudo -S rm -f /opt/bitnami/wordpress/wp-login.php
    echo wp-login.php is deleted
    echo 'verystrongpassword' | sudo -S rm -rf /opt/bitnami/wordpress/wp-includes/
    echo wp-includes is deleted
	echo 'verystrongpassword' | sudo -S ln -sfn /bitnami/wordpress/wp-admin /opt/bitnami/wordpress/wp-admin
    echo 'verystrongpassword' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-admin
    echo symlink is created for wp-admin
	echo 'verystrongpassword' | sudo -S ln -sfn /bitnami/wordpress/wp-settings.php /opt/bitnami/wordpress/wp-settings.php
    echo 'verystrongpassword' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-settings.php
    echo symlink is created for wp-settings.php
	echo 'verystrongpassword' | sudo -S ln -sfn /bitnami/wordpress/wp-load.php /opt/bitnami/wordpress/wp-load.php
    echo 'verystrongpassword' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-load.php
    echo symlink is created for wp-load.php
	echo 'verystrongpassword' | sudo -S ln -sfn /bitnami/wordpress/wp-includes /opt/bitnami/wordpress/wp-includes
    echo 'verystrongpassword' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-includes
    echo symlink is created for wp-includes
	echo 'verystrongpassword' | sudo -S ln -sfn /bitnami/wordpress/wp-login.php /opt/bitnami/wordpress/wp-login.php
    echo 'verystrongpassword' | sudo -S chown -R 1001:1001 /opt/bitnami/wordpress/wp-login.php
    echo symlink is created wp-login.php
    echo 'verystrongpassword' | sudo -S chmod 755 /bitnami/wordpress/wp-content/
    echo 'verystrongpassword' | sudo -S chmod 755 /bitnami/wordpress/wp-config.php

fi

This works as I expected, and creates symlinks to my persistent files.

**Comment by juan131** [comment]
Hi @gabbler97 

The Bitnami container image for WordPress is, by default, a non-root container. Check the link below to obtain more information:

- https://github.com/bitnami/bitnami-docker-wordpress#why-use-a-non-root-container

Therefore, it's expected that you cannot run privileges actions such as running command as "sudo". Also, the [sudo Debian package](https://packages.debian.org/buster/sudo) is not included in the image.

--- 

Regarding the process you followed to migrate your site, I understand that performing the items below should be enough:

- Backup the database you have in the VM and restore it in some MariaDB database available in your K8s cluster.
- Create a PVC in your K8s cluster and place on the volume your `wp-config.php` and the `wp-content` directory.
- Install the [Bitnami WordPress chart](https://github.com/bitnami/charts/tree/master/bitnami/wordpress) setting `wordpressSkipInstall=true` and `persistence.existingClaim` with the name of the PVC you previously created.

Please let me know if you require extra guidance about how to perform each of these steps.

**Comment by gabbler97** [comment]
Hi @juan131!

Thank you for the tips!
