### ISSUE TITLE
Cannot connect to the DB when SSL is turned on

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [bitnami/bitnami-docker-wordpress#296]
**Description**

I am using the Wordpress Helm chart ver 11.0.11 to deploy WP on K8s. I have a Azure db for MariaDB with SSL enabled that was connected to WP. I have been using 5.6.2 and when I wanted to upgrade to 5.7.2, it is failing to connect to the DB.

**Steps to reproduce the issue:**

1. Create a DB in Azure DB for MariaDB and enable SSL
2. Deploy the ver 11.0.11 wordpress helm chart
3. See `ERROR ==> Could not connect to the database`

**Describe the results you received:**
```
** Starting WordPress setup **
Configuring PHP options
Validating settings in MYSQL_CLIENT_* env vars
Restoring persisted WordPress installation
Trying to connect to the database server
Could not connect to the database
```
**Describe the results you expected:**

Should be able to connect to a db over SSL without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

I have checked iteratively and have found that versions before `5.7.1-debian-10-r21` are able to connect to the DB but those above and including `5.7.1-debian-10-r21` are failing to connect. 

I know there were some major changes in that version. These are my env vars
```
KUBERNETES_SERVICE_PORT_HTTPS=443
MYSQL_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
KUBERNETES_SERVICE_PORT=443
WORDPRESS_EMAIL=redacted@redacted.com
WORDPRESS_BLOG_SERVICE_PORT_HTTPS=443
MARIADB_PORT_NUMBER=3306
MYSQL_CLIENT_ENABLE_SSL=no
HOSTNAME=redacted
WORDPRESS_BLOG_SERVICE_PORT=80
WORDPRESS_BLOG_SERVICE_HOST=10.0.85.198
WORDPRESS_BLOG_PORT_80_TCP=tcp://10.0.85.198:80
WORDPRESS_ENABLE_DATABASE_SSL=yes
WORDPRESS_SCHEME=https
WORDPRESS_HTACCESS_OVERRIDE_NONE=yes
APACHE_HTTPS_PORT_NUMBER=
PWD=/
OS_FLAVOUR=debian-10
WORDPRESS_BLOG_PORT_443_TCP_PROTO=tcp
WORDPRESS_PLUGINS=none
WORDPRESS_FIRST_NAME=redacted
MARIADB_HOST=redacted.mariadb.database.azure.com
WORDPRESS_EXTRA_WP_CONFIG_CONTENT=
WORDPRESS_DATABASE_USER=redacted@redacted
APACHE_ENABLE_CUSTOM_PORTS=no
WORDPRESS_BLOG_PORT_80_TCP_ADDR=10.0.85.198
MYSQL_CLIENT_SSL_CA_FILE=
HOME=/
WORDPRESS_BLOG_PORT_443_TCP=tcp://10.0.85.198:443
KUBERNETES_PORT_443_TCP=tcp://10.0.0.1:443
WORDPRESS_BLOG_PORT_80_TCP_PORT=80
WORDPRESS_TABLE_PREFIX=wp_
WORDPRESS_DATABASE_NAME=wp_blog
APACHE_HTTP_PORT_NUMBER=
MYSQL_CLIENT_CREATE_DATABASE_NAME=
WORDPRESS_AUTO_UPDATE_LEVEL=none
WORDPRESS_USERNAME=redacted
WORDPRESS_BLOG_PORT=tcp://10.0.85.198:80
WORDPRESS_BLOG_NAME=redacted
TERM=xterm-256color
BITNAMI_IMAGE_VERSION=5.7.2-debian-10-r10
WORDPRESS_BLOG_PORT_80_TCP_PROTO=tcp
WORDPRESS_LAST_NAME=User
WORDPRESS_SKIP_BOOTSTRAP=no
SHLVL=1
KUBERNETES_PORT_443_TCP_PROTO=tcp
MYSQL_CLIENT_CREATE_DATABASE_USER=
BITNAMI_APP_NAME=wordpress
WORDPRESS_DATABASE_PASSWORD=redacted
WORDPRESS_BLOG_SERVICE_PORT_HTTP=80
WORDPRESS_PASSWORD=redacted
KUBERNETES_PORT_443_TCP_ADDR=10.0.0.1
MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=
ALLOW_EMPTY_PASSWORD=no
KUBERNETES_SERVICE_HOST=10.0.0.1
MARIADB_ROOT_PASSWORD=
KUBERNETES_PORT=tcp://10.0.0.1:443
KUBERNETES_PORT_443_TCP_PORT=443
WORDPRESS_VERIFY_DATABASE_SSL=yes
OS_NAME=linux
MARIADB_ROOT_USER=root
PATH=/opt/bitnami/php/bin:/opt/bitnami/php/sbin:/opt/bitnami/apache/bin:/opt/bitnami/wp-cli/bin:/opt/bitnami/mysql/bin:/opt/bitnami/common/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
WORDPRESS_ENABLE_HTACCESS_PERSISTENCE=no
WORDPRESS_BLOG_PORT_443_TCP_PORT=443
WORDPRESS_BLOG_PORT_443_TCP_ADDR=10.0.85.198
WORDPRESS_DATABASE_SSL_CA_FILE=/etc/ssl/certs/db-certificate.crt.pem
OS_ARCH=amd64
_=/usr/bin/printenv
```

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
k8s version: 1.19.9

**Comment by marcosbc** [comment]
Hi @SayakMukhopadhyay, for SSL support on Azure Database for MySQL/MariaDB, the following options are needed:

- `WORDPRESS_ENABLE_DATABASE_SSL=yes`
- `WORDPRESS_VERIFY_DATABASE_SSL=no`
- `WORDPRESS_DATABASE_SSL_CA_FILE=/path/to/azure/ca.crt.pem`
- `MYSQL_CLIENT_ENABLE_SSL=yes`
- `MYSQL_CLIENT_SSL_CA_FILE=/path/to/azure/ca.crt.pem`

It seems like in your case, `WORDPRESS_VERIFY_DATABASE_SSL`, `MYSQL_CLIENT_ENABLE_SSL` and `MYSQL_CLIENT_SSL_CA_FILE` are using the wrong values.

**Comment by SayakMukhopadhyay** [comment]
Thanks a lot for the response! Any reason why `WORDPRESS_ENABLE_DATABASE_SSL` and `MYSQL_CLIENT_ENABLE_SSL` (same for the files) are needed? Also, I don't really get why I should set `WORDPRESS_VERIFY_DATABASE_SSL=no`. I am supplying the SSL cert right, so shouldn't it verify that.
Sorry for the questions, but I would like to know a bit about the internals to make it easier for me to maintain our deployment.

**Comment by marcosbc** [comment]
The main reason is because the SSL configuration is managed by different components (the `mysql` CLI on one hand, and the WordPress app on another), although I agree it is confusing and could be improved upon. I will create an internal task to improve this in the future.

**Comment by SayakMukhopadhyay** [comment]
Understood and thanks for the explanation. The above setup works so I will close the issue.
