### ISSUE TITLE
keep security in mind

### ISSUE THREAD

**Issue by devrob20** [bitnami/bitnami-docker-wordpress#312]
why does the standard tutorial uses less secure options ?

please setup wordpress and mariaDb with the docker secrets and never use allow empty password, just to make it clear how they can access the wp-admin user/wplogin

atleast include  DB and WP user and pass so new users wont learn bad habbits. even in a homelab localhost you want it secure.

and also keep in mind port 80 (8080) is not the best choice, esp if you want to setup multiple WP on your docker. 

in portainer i have set it to
2080:8080
20443:8443
  
but for some reason wp-login redirects to host 8080 

what am i missing ?

**Comment by alemorcuq** [comment]
Thanks for opening this issue, @devrob20. I have forwarded it to the engineering team for evaluation.

Regarding the redirect issue you have mentioned, I have not been able to reproduce it. Mapping the ports to 2080 ad 20443 I can successfully navigate the site and login with no redirects issues. Where are you finding this wrong redirection?

**Comment by lukasmrtvy** [comment]
> but for some reason wp-login redirects to host 8080

Both Apache and Nginx Wordpress images in latest version are affected.

Related:
https://github.com/bitnami/charts/issues/2111
https://github.com/bitnami/bitnami-docker-wordpress/issues/263
