### ISSUE TITLE
WORDPRESS_EXTRA_WP_CONFIG_CONTENT Doesn't Seem to Work Within a Dockerfile

### ISSUE THREAD

**Issue by Jyosua** [bitnami/bitnami-docker-wordpress#315]
I'm trying to set the WORDPRESS_EXTRA_WP_CONFIG_CONTENT environment variable within my Dockerfile in order to install the [Amazon S3 offload plugin](https://deliciousbrains.com/wp-offload-media/doc/amazon-s3-quick-start-guide/#save-access-keys) by Delicious Brains. The recommended way to set the keys for interacting with S3 is via the `wp-config.php` file, which brings me here.

The two main issues here are:

1. How to configure multiline environment variables within a Dockerfile
2. Failing that, how to get even a single-line `define()` working within a Dockerfile.

I could not find any resources for 1, so I attempted 2:

```
ENV WORDPRESS_EXTRA_WP_CONFIG_CONTENT=define( 'AS3CF_SETTINGS', serialize( array( 'provider' => 'aws', 'access-key-id' => '********************', 'secret-access-key' => '****************************************' ) ) );
```

However, upon trying to build the dockerfile, docker predictably returned this error:

```
Error response from daemon: failed to parse Dockerfile: Syntax error - can't find = in "'AS3CF_SETTINGS',". Must be of the form: name=value
```

I decided to then wrap this in quotes:
```
ENV WORDPRESS_EXTRA_WP_CONFIG_CONTENT="define( 'AS3CF_SETTINGS', serialize( array( 'provider' => 'aws', 'access-key-id' => '********************', 'secret-access-key' => '****************************************' ) ) );"
```

which got rid of the docker build error, but when I checked my `wp-config.php` in `/opt/bitnami/wordpress/` after rebuilding the container without cache, it did not contain the line I added.

I don't see anything in the documentation for this container on the recommended way to actually use this environment variable. Checking the other issues hasn't really helped, since I don't want nor need to use docker-compose -- I want to use a Dockerfile. Help on how to get this feature to work would be greatly appreciated, thanks.

**Comment by Jyosua** [comment]
For some reason this did not work the first time I rebuilt with `--no-cache`, but it seems to have worked the second time??

**Comment by carrodher** [comment]
I'm glad to see that the issue was solved. You can define env. variables in the Dockerfile to be taken into account during build time so the env. var is included in the image, but also you can pass the env. variable when deploying the container; when executing `docker run` you can use the `-e YOUR_ENV_VAR`, just in case it helps.

**Comment by Jyosua** [comment]
Ultimately, you either need to wrap in quotes or define a `.env` file and use that when doing docker run. I wasn't able to get multi-line definitions working in either case, which is kind of a pain if you need to define more than one thing or an array.
