### ISSUE TITLE
Operation not supported: AH00023: Couldn't create the mpm-accept mutex

### ISSUE THREAD

**Issue by bmartinezg** [bitnami/bitnami-docker-wordpress#316]
Every time I try to run the docker image in my m1 chip mac I got the following console error:

```
wordpress 10:19:00.96 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 10:19:00.98 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 10:19:01.00
wordpress 10:19:01.04 INFO ==> ** Starting WordPress setup **
wordpress 10:19:01.32 INFO ==> Configuring PHP options
wordpress 10:19:01.43 INFO ==> Validating settings in MYSQL_CLIENT_* env vars
wordpress 10:19:02.66 INFO ==> Restoring persisted WordPress installation
wordpress 10:19:02.86 INFO ==> Trying to connect to the database server
wordpress 10:19:12.55 INFO ==> ** WordPress setup finished! **
wordpress 10:19:12.64 INFO ==> ** Starting Apache **
[Sat Aug 07 10:19:12.796132 2021] [core:emerg] [pid 1] (95)Operation not supported: AH00023: Couldn't create the mpm-accept mutex
(95)Operation not supported: could not create accept mutex
AH00015: Unable to open logs
```

**Comment by migruiz4** [comment]
Hi @bmartinezg,

This issue is caused because the `bitnami/wordpress` image does not support ARM systems yet (including Apple Silicon M1).

It is in our roadmap to release ARM images of bitnami/wordpress and other applications in our catalog, but I can not give you an ETA on when they will be available.

As a workaround, you could run the Bitnami Wordpress image on Apple Silicon M1 using emulation (QEMU), but that could have some limitations as described in the docker documentation (https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues)

**Comment by malthejorgensen** [comment]
Using a Dockerfile with the contents:

```
FROM bitnami/moodle

# Some credit goes to: https://www.linode.com/community/questions/16977/server-fails-after-installing-certbot-mpm-run-failed-exiting#answer-66578
RUN echo 'Mutex posixsem' >>/opt/bitnami/apache2/conf/httpd.conf
```

worked for me on my Mac M1.

**Comment by cesdperez** [comment]
Can confirm the simple trick from @malthejorgensen worked for me on M1 too. Thanks!

**Comment by mmwebaze** [comment]
I can confirm too that @malthejorgensen work around worked for me on an M1. Thanks for saving me!!!

**Comment by kory-northrop** [comment]
@cesdperez @mmwebaze how did you get this to work? I added the `RUN echo 'Mutex posixsem' >>/opt/bitnami/apache2/conf/httpd.conf` line to my Bitnami Wordpress Dockerfile, but I still get the same error.

**Comment by mmwebaze** [comment]
@kory-northrop this fix worked for a bitnami-moodle image I was using and had to create a new image. https://github.com/mmwebaze/docker_moodle/blob/main/Dockerfile

**Comment by henriquemattos** [comment]
I wonder how `Mutex posixsem` fixed y'all problem. I don't see the error in the log but I keep loosing requests every now and then in the application.
