### ISSUE TITLE
Mixed Content Warnings when Deployed Behind AWS Load Balancer

### ISSUE THREAD

**Issue by Jyosua** [bitnami/bitnami-docker-wordpress#318]
I have essentially the same problem as what was reported [here](https://github.com/bitnami/bitnami-docker-wordpress/issues/101). I've tried setting `WORDPRESS_ENABLE_HTTPS=yes` and adding `WORDPRESS_EXTRA_WP_CONFIG_CONTENT="if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) $_SERVER['HTTPS']='on';"` but even with both enabled, I'm still seeing mixed content warnings. The application load balancer in AWS sends the x-forwarded-proto header by default, so I'm not sure how to fix this. It's blocking my deployment of this container, though.

If I run the container on EC2, I don't seem to have this issue. Only when deploying on ECS behind an application load balancer.

**Comment by Jyosua** [comment]
Well, I was just now able to fix it with automatic HTTPS rewrites in my Cloudflare config, but I feel like this isn't the most optimal way lol

Is there a better way to do this?

**Comment by pablogalegoc** [comment]
Hi @Jyosua, glad to hear you've managed to get it working. Take a look at https://docs.bitnami.com/aws/how-to/configure-elb-ssl-aws/ just in case there's something useful for you there.

**Comment by Jyosua** [comment]
I had actually taken a look at that page already. Doing the !== false thing with the config actually does not work. And based on the other closed issue I linked to, the SetEnvIf should not be required, though I could not find the change mentioned in that ticket in this container's configs when I looked.

**Comment by pablogalegoc** [comment]
Hopefully I'll get time soon to test the guide above to see if I face the same issues because indeed this should not have to take hours to get working.

**Comment by Jyosua** [comment]
I'd appreciate that, thanks! I like using bitnami containers, but this one was a bit harder to deploy than I expected lol

**Comment by randradas** [comment]
Hello Jyosua, I've deployed the container using the following architecture on AWS:

Chrome(92.0.4515.107)----HTTPS---->AWS Application Load Balancer----HTTP---->EC2(bitnami/wordpress:latest) and it worked by default without modifying neither apache nor wordpress files. It just worked. As you can see in the following image every URL generated by wordpress is using the https protocol as expected.

![image](https://user-images.githubusercontent.com/865380/129598717-240830c2-9df0-41c3-91e7-4272a2e2867b.png)

My ALB configuration is an internet-facing ALB, which terminates HTTPS session on itself, EC2 security group allows traffic from the ALB's security group to port 80, the ALB security group has a listener on port 443 (ACM certificate) which redirect the traffic to the HTTP1 Instance Target Group which contain one healthy instance running the container with '[docker-compose.yml](https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml)'.

Could you provide details on your AWS resource configurations and architecture? did you use ALB with EC2?

**Comment by Jyosua** [comment]
Does that also work with the /wp-admin/ login?

For my architecture, it's deployed on a Fargate cluster behind an application load balancer. I did not use the ALB with EC2, only ECS. I suspect the issue was actually the combination of Cloudflare and the ALB. I had initially set it up with flexible SSL rather than full SSL, and I've yet to test if disabling the container-related configs I've added with full SSL enabled also fixes this issue.

**Comment by randradas** [comment]
Yes it works even after loading into wp-admin, find below evidence:
![image](https://user-images.githubusercontent.com/865380/129932297-b966da07-1b89-47e2-9b92-e2bd5f03e7e0.png)

**Comment by Jyosua** [comment]
So after some further testing, I figured out the root cause. It was actually the combination of Cloudflare Flexible SSL and being behind the ALB. Using Cloudflare flexible SSL instead of full SSL caused the container to be confused because the X-Forward-Proto headers aren't sent to the container right, so you get mixed content warnings. You can fix that by using page rules in Cloudflare to force everything to HTTPS, but then the admin page gets stuck in a weird redirect loop going back and forth between HTTP and HTTPS, because it again doesn't have the right headers to know whether it needs to use HTTPS URLs or not.

It is fixable via some settings using other headers [mentioned here](https://wordpress.stackexchange.com/a/257354/178388), but the proper fix was just installing the Cloudflare SSL certificate on the load balancer, terminating SSL there, and forwarding to the container on HTTP. Done this way, the ALB sends the proper headers and everything works.

I admittedly always do this step last, usually testing with flexible SSL until I'm sure everything else is working, so I didn't know it would fix my problems and did it only after I had found a different workaround.

**Comment by pablogalegoc** [comment]
Thanks for sharing @Jyosua! I'm sure this is going to save time for someone in the future. Luckily @randradas had bandwidth to look into this so thank you also 🙂

**Comment by Jyosua** [comment]
Yep, thank you guys for also trying to help. I appreciate the responsiveness.

Anyhow, since it turned out to be more of a deployment configuration issue, I'm going to go ahead and close this.
