### ISSUE TITLE
Can't copy content when using Azure Files instead of Azure Disk

### ISSUE THREAD

**Issue by Matiasdall93** [bitnami/bitnami-docker-wordpress#321]
**Description**

We are trying to create new Wordpress sites in Azure Kubernetes using the Bitnami Wordpress Image. We are able to create the sites using Azure Disk, but if we change the PVC to Azure Files and make it ReadWriteMany so more pods can use the same PVC, the WP-content directory doesn't get moved to /bitnami/wordpress/ . However wp-config.php does get moved to /bitnami/wordpress/ directory so I have crossed off permission to storage account.

**Steps to reproduce the issue:**

1. Create a deployment using Azure Files PVC with standard Wordpress Bitnami image using the same configuration as with Azure Disks
2. Bash into the pod and notice the files are not moved. 

**Describe the results you received:**

Empty WP-content folder

**Describe the results you expected:**

Plugins and themes etc.  should be transferred to /bitnami/wordpress/wp-content

**Version**

Azure Kubernetes 1.19.13

**Comment by marcosbc** [comment]
Hi @Matiasdall93, could you share the logs of the deployment? Does it fail immediately or does it take some time to copy the files (until it fails)? 

Also, have you considered setting [`volumePermissions.enabled=true`](https://github.com/bitnami/charts/tree/master/bitnami/wordpress#persistence-parameters) to see if it workarounds the issue?
