### ISSUE TITLE
Feature request: Add Docker secrets support

### ISSUE THREAD

**Issue by SolitudeRA** [bitnami/bitnami-docker-wordpress#324]
It would be very helpful to add support with docker secrets in passing sensitive information via environment variables. Seem that Bitnami images(Wordpress, Owncloud etc.) are using same code in initializing database with mysql client. That would be very convince and safe if these env variables(MYSQL_CLIENT_DATABASE_ROOT_PASSWORD, MYSQL_CLIENT_CREATE_DATABASE_PASSWORD etc.) could be set by docker secret files.
Thanks

**Comment by rafariossaa** [comment]
Hi,
  I am sorry but is is not in our roadmap implement docker secrets right now, however PR are welcomed. We will be glad to review and merge them.
