### ISSUE TITLE
CI/CD Process Recommended Approaches

### ISSUE THREAD

**Issue by haithamshahin333** [bitnami/bitnami-docker-wordpress#326]
**Description**

Hi Team, any thoughts on how best to continuously update and deploy as changes are made to the custom wordpress site (i.e. any recommended path for CI/CD in the context of this image)? For example, if I've already migrated and now want to redeploy with a new plugin/theme that has been developed, what's the recommended path for doing that?

In a normal/non-cms containerized app, this would be solved by simply updating packages (npm install, for example) and by the fact that the app's source would be copied into a base image including the runtime. Given a system like wordpress and how the core site is already baked into this deployed image, I'm curious to get the team's take on what a good approach looks like for managing updates beyond the initial migration.

Appreciate the input!

**Comment by migruiz4** [comment]
Hi @haithamshahin333!

I would recommend having a look at our README.md where you can find useful information:
- [How to perform maintenance tasks](https://github.com/bitnami/bitnami-docker-wordpress#maintenance) (Including how to upgrade Wordpress)
- [How to persist your data](https://github.com/bitnami/bitnami-docker-wordpress#persisting-your-application)
- [How to use WP CLI](https://github.com/bitnami/bitnami-docker-wordpress#wp-cli-tool)
- [How to customize the bitnami/wordpress image](https://github.com/bitnami/bitnami-docker-wordpress#customize-this-image)
