### ISSUE TITLE
Feature request: Ability to change apache log format

### ISSUE THREAD

**Issue by ivanbarlog** [bitnami/bitnami-docker-wordpress#327]
Hi there!

Is there any easy way of changing the apache log format?

I am struggling with the Wordpress site behind AWS Load Balancer and I just want to add `X-Forwarded-For` to the logs as described here https://aws.amazon.com/premiumsupport/knowledge-center/elb-capture-client-ip-addresses/

Thanks for the help

**Comment by alemorcuq** [comment]
Hi! You will need to extend the image yourself or mount an external config file to achieve that.

**Comment by ivanbarlog** [comment]
Thanks @alemorcuq I think mounting an external config could do it but I wasn't sure.

So I guess I shall copy the current config from the container, change what I need and then mount it back.

Can you maybe help me with identifying the path of the config?

Many thanks!

**Comment by rafariossaa** [comment]
Could you take a look to this section: https://github.com/bitnami/bitnami-docker-wordpress#user-content-extend-this-image ?

**Comment by ivanbarlog** [comment]
@rafariossaa thanks, I have missed that one.

**Comment by juan131** [comment]
I will proceed to close this ticket as "solved". Please feel free to reopen it if you require further assistance.
