### ISSUE TITLE
Bitnami wp stack uses modsecurity 3.x which is not safe yet

### ISSUE THREAD

**Issue by mic345** [bitnami/bitnami-docker-wordpress#331]
Bitnami stack uses modsecurity 3.x which is connecting to apache via [ModSecurity-apache](https://github.com/SpiderLabs/ModSecurity-apache).

ModSecurity-apache is in a beta version and is not yet ready for production. Specifically, it's latest official release has security breaches.

We should use modsecurity 2.9.x as per mod security team instructions.

![SpiderLabs-ModSecurity-apache-ModSecurity-v3-Apache-Connector](https://user-images.githubusercontent.com/36601023/143027535-33061f28-d803-4f21-9ff7-7efa44ded66e.png)

**Comment by juan131** [comment]
Hi @mic345 

Thanks so much for reporting it! We're aware that we included recently modsecurity `3.x` which is no recommended for production yet. That's why we're currently working on reverting back to `2.x`.

We'll get you updated about our progress and notify you back in this thread once we release new containers that ship modsecurity `2.x`.

Thanks again!

**Comment by mic345** [comment]
👍

Take care and good luck!

**Comment by dgomezleon** [comment]
Hello @mic345,

We have released a new WordPress including both ModSecurity 2 and 3. Also, we have updated our documentation.
https://docs.bitnami.com/general/apps/wordpress/configuration/enable-modules/#mod_security

Regards

**Comment by mic345** [comment]
Hi guys a quick question -- is this fix released already? We couldn't find it yet on the change log.
https://bitnami.com/stack/wordpress/installer/changelog.txt

Take care and happy new year 😊
mic.

**Comment by carrodher** [comment]
Hi, please note this GH repo is for the bitnami/wordpress container, for questions regarding installer or virtual machines you should create a ticket in the [Bitnami Community forum](https://community.bitnami.com/).

Regarding the container, modsecurity should be part of it

**Comment by mic345** [comment]
👍
We'll check with them.
