### ISSUE TITLE
Could not connect to the database error with SSL

### ISSUE THREAD

**Issue by omobono-alex** [bitnami/bitnami-docker-wordpress#333]
Our external MySQL database now only accepts connections using SSL.

I'm having an issue whereby when I create my pods, I get the error 'Could not connect to the database'. (This was previously working correctly before the SSL enforcement).

I've traced the error back to the following line in **libwordpress.sh**
https://github.com/bitnami/bitnami-docker-wordpress/blob/3e8367b21ea60ca8cc819a91bad5f519a9bbd7ff/5/debian-10/rootfs/opt/bitnami/scripts/libwordpress.sh#L209

Of course, it will never connect because the MySQL server only accepts connections using SSL.

It seems that the **wordpress_wait_for_mysql_connection** function isn't written to support SSL connections, and I don't see a way of bypassing it.

I'm using WORDPRESS_ENABLE_DATABASE_SSL etc, but this doesn't seem to be taken into account during the initial connection test.

Am I missing something here?

**Comment by miguelaeh** [comment]
Hi @omobono-alex ,
did you configure the parameters explained [here](https://github.com/bitnami/bitnami-docker-wordpress#database-connection-configuration
)?

**Comment by omobono-alex** [comment]
I'd configured all of the WP ones, but these weren't enough:
- WORDPRESS_ENABLE_DATABASE_SSL
- WORDPRESS_VERIFY_DATABASE_SSL
- WORDPRESS_DATABASE_SSL_CERT_FILE
- WORDPRESS_DATABASE_SSL_KEY_FILE
- WORDPRESS_DATABASE_SSL_CA_FILE

I've since configured the corresponding MYSQL_CLIENT SSL vars and it appears to connect successfully now. This is what I was missing.

Unfortunately, it seems to be bailing out further down the line, so more debugging will be required my end. Very strange given this was working correctly before the SSL changes.

Thanks

**Comment by omobono-alex** [comment]
All working now.

First issue was solved by adding the MYSQL_CLIENT_* SSL config variables in.
Second issue was making sure the wp-cli commands the shell script runs would also use the SSL certs; just had to re-deploy.
