### ISSUE TITLE
Error email send SMPT Server in Stack: Docker => Wordpress NGINX SSL

### ISSUE THREAD

**Issue by NelsonScript** [bitnami/bitnami-docker-wordpress#336]
Good morning, I'm trying to send an email through the WP Mail SMPT plugin. I must say that I have experience in handling this plugin and I have already handled it with VM in GCE with the different Bitnami stacks, however at this moment I am managing the Bitnami stack with NGINX for wordpress with Docker and I have presented several problems .

This is the error that I present from the plugin
versions:

<img width="1276" alt="Captura de Pantalla 2022-01-25 a la(s) 5 32 37 p m" src="https://user-images.githubusercontent.com/2517635/151070892-66520c9c-01c9-4165-91e3-2bc0f951b9a7.png">

------------SOLUTIONS--------------
1.  I verified that the container is pointing and the correct certificates which I created from Cloudflare
2. In the container logs it shows me that I must publish the correct port, according to Google Cloud Platform for security I must enable port 2525 from the firewall, in my case I have published it from the docker-compose as follows:

 ports:
      - '80:8080'
      - '443:8443'
      - '2525:587'

3. Finally I have tried to update the OpenSSL but in this case in the container I have not been able to do it as suggested in this post
https://community.bitnami.com/t/wp-smtp-mail-error/99669

I still haven't solved the problem and I think I've come this far, so if you can help me, I'd really appreciate it.

**Comment by juan131** [comment]
Hi @NelsonScript 

It seems you're using WordPress with NGINX (this repository is about WordPress with Apache). Could you please open an issue in this [other repository](https://github.com/bitnami/bitnami-docker-wordpress-nginx) instead? Thanks in advance.

**Comment by NelsonScript** [comment]
Ok,  i do it right now, thanks!
