### ISSUE TITLE
using old version of image and facing non root user issue

### ISSUE THREAD

**Issue by bijancot** [bitnami/bitnami-docker-wordpress#337]
**Description**

So i have an urge to using old version of wordpress, i try using wordpress with docker tag 5.2.4-* something. And i facing issue with :
`nami    ERROR Cannot find any module matching the provided specification 'apache'` i think it happens because the name run as non root and the package installed with root user. Is There any way to make the user run as root?

**Steps to reproduce the issue:**

1. running docker image with 5.2.4-* tag and 7.5.4 helm chart version
2. facing error with nami like i mention before

**Describe the results you received:**
`nami ERROR Cannot find any module matching the provided specification 'apache'`

**Describe the results you expected:**

I want run the old version of docker

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**

**Comment by carrodher** [comment]
Unfortunately, we don't provide support for such an old version of Helm charts; being said that, using the latest available version you should be able to run the WordPress container as `root` by setting the `containerSecurityContext.runAsNonRoot=false` parameter.

In the same way, by setting `image.tag=5.2.4` (or any other tag) you should be able to use the latest version of the Helm chart but override the WordPress container image tag. Although this is not something tested by our automated test & release pipeline where just the versions that are being released are tested, other combinations should work but it is not guaranteed.

**Comment by bijancot** [comment]
So, that means in theory i can use latest chart with old tag. But need to do some changes or update refer to each respective version. Fair Enough. Thank you for the response!
