### ISSUE TITLE
bash script to fix file permissions

### ISSUE THREAD

**Issue by webdz9r** [bitnami/bitnami-docker-wordpress#341]
### Name and Version

Bitnami/wordpress:latest

### What is the problem this feature will solve?

Can we get a bash script we can run post docker build to insure the files copied over have the right non-rooted permissions? Maybe it already exists? 

### What is the feature you are proposing to solve the problem?

Fixing file permissions from files added via docker build

### What alternatives have you considered?

I have to change the files on my local machine to non-rooted permissions which makes them hard to edit locally

**Comment by juan131** [comment]
Hi @webdz9r 

The Bitnami WordPress is, by default, a non-root container. Therefore, you won't be able to run privileged actions such as changing permissions/ownership at runtime unless you force the container to be executed as root. Find more info about non-root containers in the link below:

- https://github.com/bitnami/bitnami-docker-wordpress#why-use-a-non-root-container

> Note: Running custom scripts during the container initialization is already supported, as you can check in the lines below:

- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/opt/bitnami/scripts/wordpress/entrypoint.sh#L26
- https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh
