### ISSUE TITLE
Set ServerTokens to Prod by default

### ISSUE THREAD

**Issue by BlockFund** [bitnami/bitnami-docker-wordpress#342]
### Name and Version

bitnami/bitnami-docker-wordpress:5.9.0-debian-10-r16

### What is the problem this feature will solve?

My PCI scans are coming back as failing. This is because of the ServerTokens directive is not set to prod. I was wondering if this could be set to prod by default.

### What is the feature you are proposing to solve the problem?

Set the ServerTokens directive to Prod in the Apache config.

**Comment by javsalgar** [comment]
Hi,

Could you provide more information about the ServerToken directive and the PCI checks you are performing? We would like to understand the issue bettere

**Comment by javsalgar** [comment]
I created  task for evaluating it. We cannot guarantee an ETA, but we will update the ticket as soon as there's news.

**Comment by fmulero** [comment]
Hi @BlockFund

As workaround you can mount a volume in `/vhosts` path with a file with this content:
```
ServerTokens ProductOnly
```

More information here [Adding custom virtual hosts|https://github.com/bitnami/bitnami-docker-apache#adding-custom-virtual-hosts]

**Comment by fmulero** [comment]
Hi @BlockFund New releases will come with `ServerTokens Prod` and `X-Powered-By` header disabled by default
