### ISSUE TITLE
MySQL not found (5.9.2-debian-10-r24 and later)

### ISSUE THREAD

**Issue by omobono-alex** [bitnami/bitnami-docker-wordpress#345]
### Name and Version

bitnami/wordpress:5.9.2

### What steps will reproduce the bug?

1. Use `wordpress:5.9.2-debian-10-r24` or anything after it, including `wordpress:5.9.2-latest`.
2. Deploy to GKE, as per usual.
3. Get an error during WP init relating to mysql-client:
`/opt/bitnami/mysql/bin/mysql: 2: exec: /opt/bitnami/mysql/.bin/mysql: not found`
4. Manually executing `mysql` inside the faulty container yields same error.

### What is the expected behavior?

I expect `mysql` to execute, returning something like:
`ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)`

### What do you see instead?

Instead, I get an error. WP fails to start up due to the same error:
`/opt/bitnami/mysql/bin/mysql: 2: exec: /opt/bitnami/mysql/.bin/mysql: not found`

### Additional information

The changes in the following commit seem to result in me no longer being able to execute mysql inside my container:
https://github.com/bitnami/bitnami-docker-wordpress/commit/f87ad57ca563748bc27f67264eb5d5ed6ffd4a69

It looks like it could be something to do with the symlinks to mariadb that are found at `/opt/bitnami/mysql/bin/` and `/opt/bitnami/mysql/.bin/` - although I am not sure what exactly.

Everything works fine for me with `wordpress:5.9.2-debian-10-r23`, so I have rolled back to this version for now.

**Comment by javsalgar** [comment]
Hi,

I've been unable to reproduce the issue:

```
 125 ❯ docker run --rm -ti bitnami/wordpress:5.9.2-debian-10-r24 bash
Unable to find image 'bitnami/wordpress:5.9.2-debian-10-r24' locally
5.9.2-debian-10-r24: Pulling from bitnami/wordpress
fea43f71b0b0: Already exists
654a44343f7f: Pulling fs layer
2fdf1da39ff1: Pulling fs layer
e0f1a9cf44b6: Pulling fs layer
430dde16c9e0: Pulling fs layer
c7cf85f10a89: Pulling fs layer
6557292de750: Pulling fs layer
cef197bb4e21: Pulling fs layer
5f0e0d89b7a1: Pulling fs layer
e39bf919f378: Pulling fs layer
48773f0c176c: Pulling fs layer
2dbf56ff4782: Pulling fs layer
239a7a93ad7d: Pull complete
8d562c04242c: Pull complete
cd783945d31f: Pull complete
6f8c726aa008: Pull complete
cd99d7f504ce: Pull complete
8715c544aa4b: Pull complete
ca8166bb66a8: Pull complete
d15a456559b7: Pull complete
Digest: sha256:e6e360521c1ec75965eea3ade76ac3c996b7101265895d60dfe62a8b0ab787fd
Status: Downloaded newer image for bitnami/wordpress:5.9.2-debian-10-r24
wordpress 08:25:07.64
wordpress 08:25:07.64 Welcome to the Bitnami wordpress container
wordpress 08:25:07.64 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress 08:25:07.65 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress 08:25:07.65

I have no name!@4ad692e49951:/$ mysql
ERROR 2002 (HY000): Can't connect to local server through socket '/opt/bitnami/mysql/tmp/mysql.sock' (2)
I have no name!@4ad692e49951:/$ which mysql
/opt/bitnami/mysql/bin/mysql
I have no name!@4ad692e49951:/$

I have no name!@4ad692e49951:/$ mysql --version
mysql  Ver 15.1 Distrib 10.6.7-MariaDB, for Linux (x86_64) using readline 5.1
```

Could you provide any details about the platform you are using? It is very weird to me this error.

**Comment by omobono-alex** [comment]
I checked the contents of `/opt/bitnami/mysql/bin/mysql` and saw that it is a shell script which appends SSL params to `/opt/bitnami/mysql/.bin/mysql`
```
#!/bin/sh
exec "/opt/bitnami/mysql/.bin/mysql" "$@" --ssl=TRUE [...]
```
Testing again this morning, it seems to be working correctly!
```
$ ls -la /opt/bitnami/mysql/.bin/
total 4328
drwxrwxr-x 1 root root    4096 Apr  7 10:05 .
drwxr-xr-x 1 root root    4096 Apr  7 00:20 ..
-rwxr-xr-x 1 root root 4414488 Mar  1 19:33 mysql
```
Previously this was a symlink to mariadb which clearly didn't exist
```
$ ls -la /opt/bitnami/mysql/.bin/
total 16
drwxrwxr-x 1 root root 4096 Apr  6 16:48 .
drwxr-xr-x 1 root root 4096 Apr  6 00:55 ..
lrwxrwxrwx 1 root root    7 Mar  1 19:31 mysql -> mariadb
```
Checking through the commit history, it seems that this was the fix which solved my issue:
https://github.com/bitnami/bitnami-docker-wordpress/commit/8e51ffe0d109407bfcdc4b3472f3996d2df6e472#diff-6849442c64377aa5fae827761db00597a26b97dc2749a88bf2e59aaf6c8f6562

**Comment by javsalgar** [comment]
Hi! Thank you for confirming!
