### ISSUE TITLE
An environment variable for site url 

### ISSUE THREAD

**Issue by zeeside** [bitnami/bitnami-docker-wordpress#349]
### Name and Version

bitname/wordpress:latest

### What is the problem this feature will solve?

allow specifying a URI for the wordpress isntallation

### What is the feature you are proposing to solve the problem?

A new environment variable

### What alternatives have you considered?

logging into the site and updating the domain

**Comment by rafariossaa** [comment]
Hi,
  I am not sure what you mean with this. Could you elaborate a bit more on your use case ?
