### ISSUE TITLE
Unable to reset the WordPress password

### ISSUE THREAD

**Issue by itsmemidhuz123** [bitnami/bitnami-docker-wordpress#353]
### Name and Version

bitnami/wordpress6

### What steps will reproduce the bug?

WordPress password changed or unable to reset the password, it says couldn't able to reset using email as the email provider is not setup properly. kindly help how do I able to reset the password using CLI to create a new password on Bitnami WordPress
set up

### What is the expected behavior?

unable to access wp-admin
Email setup incomplete for outgoing emails

### What do you see instead?

unable to reset password

**Comment by dgomezleon** [comment]
Hi @itsmemidhuz123 ,

Use the documented commands from your container in order to reset WP password in the DB:
https://docs.bitnami.com/general/apps/wordpress/administration/reset-wp-admin-password/

I hope it helps
