### ISSUE TITLE
default install from kitematic fail to install with err mariadb:3306 

### ISSUE THREAD

**Issue by thomasmodeneis** [bitnami/bitnami-docker-wordpress#40]
```
nami    INFO  Initializing apache
apache  INFO  ==> Patching httpoxy...
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
nami    INFO  php successfully initialized
nami    INFO  Initializing wordpress
mysqlCo INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
nami    INFO  Initializing wordpress
mysqlCo INFO  Trying to connect to MySQL server
nami    INFO  Initializing wordpress
mysqlCo INFO  Trying to connect to MySQL server
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
```

Any ideas what maybe wrong ? I've tried to install this via kitematic but it won't start.

**Comment by prydonius** [comment]
This WordPress image needs to connect to a database container to store data. The recommended way to run it is using [Docker Compose](https://docs.docker.com/compose/) as described [here](https://github.com/bitnami/bitnami-docker-wordpress#using-docker-compose). Unfortunately, Kitematic does not support networking/linking containers, so there is no easy way to run WordPress using it.

**Comment by thomasmodeneis** [comment]
Oh right, thanks for the tip.
I will do the recommended way, hope it works now :)
Cheers.
