### ISSUE TITLE
Got a bitnami prestashop for virtualbox but port forwarding isnt yet working

### ISSUE THREAD

**Issue by nipgrnc104** [bitnami/bitnami-docker-wordpress#50]
I download BITNAMI vm for VirtualBox for Prestashop.

It said the inner site is running on 10.0.2.15 which is accessible through ping on commandline in bitnami OS.
My main OS is windows and I tried port forwarding in bitnami vm by converting network connection type to NAT instead of default Bridge type, as port forwarding in virtualbox only enables in NAT type network adapter.

I still cannot access the server from outside windows. 
WHile there are other VMs and apache running on my system; I am pretty sure that port forwarding is valid process and my virtualbox installation isnt a corrupt one. I have all ports with me and checked many times so that I am not using same ports for duplicate VMs.

I thought getting a vm readymade will make process easier. But its too tough to solve it.

**Comment by prydonius** [comment]
Hi @nipgrnc104, the [Bitnami Helpdesk](http://helpdesk.bitnami.com/home) can be used for support with our VM/Cloud based solutions. You can submit your ticket [here](http://helpdesk.bitnami.com/anonymous_requests/new). This GitHub repo is for development and support of our WordPress container image.

**Comment by nipgrnc104** [comment]
Thank you
