### ISSUE TITLE
Can't install certain themes 

### ISSUE THREAD

**Issue by lbendat** [bitnami/bitnami-docker-wordpress#57]
I've tried to install some themes that work though a traditional LAMP stack on a VM but won't do so locally if being run through the container.  I get a "Are you sure you want to do this?" on the screen and notice that the logs display a 403 on the post for the upload.  I initially thought that this may be due to the php memory limit, but I updated that to be large enough.  I'm at a loss.  Any help would be appreciated.

**Comment by sameersbn** [comment]
@lbendat could you share the details of the theme that you are having trouble installing?

**Comment by lbendat** [comment]
Hi.  It’s the Ratio theme from themeforest.  If you send me a private message, I can give you the files for testing.  Thank you.

-- 
Lior Bendat
Sent with Airmail

On December 20, 2016 at 07:34:29, Sameer Naik (notifications@github.com) wrote:

@lbendat could you share the details of the theme that you are having trouble installing?

**Comment by sameersbn** [comment]
@lbendat I tested the installation the theme under various configurations and I did not face any issues installing the theme.

Following are the steps I performed to setup the wordpress and install the theme:
 
```bash
$ mkdir wordpress
$ curl -O https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml
$ docker-compose up
```

Visit http://localhost/wp-admin/theme-install.php and upload the ratio.zip file.

![upload theme user s blog wordpress](https://cloud.githubusercontent.com/assets/410147/21799084/c2271112-d73d-11e6-861d-f4ebc250bbae.png)

From this point you can activate the theme and install and activate the plugins required by the theme.

Like I mentioned, in an effort to reproduce the issue I tried these steps on various docker setup's which includes:

 - Docker on Ubuntu
 - Docker for Mac
 - Kubernetes on GKE

I was unable to reproduce the issue on any of these setup's.

Can you please retry and let us know? If you continue to see the issue I would suggest removing any existing `bitnami/wordpress` images and re-pulling from docker hub and retrying. If you continue to see the issue, please provide us more information about your docker setup and instructions to reproduce the issue. The https://github.com/bitnami/bitnami-docker-wordpress#issues section of the README provides information about the details to attach. 

Do let us know...

**Comment by lbendat** [comment]
Very strange! Docker updated recently; I’m wondering if something may have
contributed to this starting to work all of a sudden.  Thank you for
testing; all seems fine now!! :)

-- 
Lior Bendat
Sent with Airmail

On January 10, 2017 at 00:43:06, Sameer Naik (notifications@github.com)
wrote:

curl -O https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml

**Comment by sameersbn** [comment]
Awesome!
