### ISSUE TITLE
Forbidden  You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by Nhoui** [bitnami/bitnami-docker-wordpress#65]
I'm using docker-compose for mac and setup wordpress site from bitnami/wordpress container, it seems everything done good, after stop and start container again, I cannot access my site it shows message: Forbidden You don't have permission to access / on this server

**Comment by sameersbn** [comment]
I tested using Docker for Mac using the following steps and was not able to reproduce the issue:

Launch wordpress application using the sample `docker-compose.yml` spec:

```bash
$ curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml
$ docker-compose up -d 
```

Access page http://localhost/hello-world to load the sample post.

Next, stop and restart the wordpress application.

```bash
$ docker-compose down
$ docker-compose up -d
```

Reload above link. 

No issues were encountered after following the above procedure. @Nhoui can you please provide additional information to allow us to reproduce this issue?

Environment information:

Operating System: MacOS El Capitan
Docker for Mac: `1.12.5 (stable)`

```bash
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: FTHR:HBGB:2KWU:GNGA:HKIP:LORL:PS4I:RIQD:OOJY:QIUV:CAYT:YGH2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 46
 Goroutines: 54
 System Time: 2017-01-02T07:57:14.23805485Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by sameersbn** [comment]
@Nhoui do you have any updates?

**Comment by Nhoui** [comment]
First I run wordpress from command line docker-compose up -d and try to add phpmyadmin to use php, apache and mariadb from the same volumes of wordpress. After that when I access wordpress site it shows that message.
