### ISSUE TITLE
3rd party php apps

### ISSUE THREAD

**Issue by unlaudable** [bitnami/bitnami-docker-wordpress#72]
Hi,

Is it possible to run a 3rd party php app alongside wordpress in this container? if so how?

I've tried exposing htdocs with --volume /var/www/html/htdocs:/opt/bitnami/apache/htdocs and copying a php script in there, but the logs just say 404.

Thanks

**Comment by prydonius** [comment]
Hey @unlaudable, what kind of 3rd party php app are you trying to run? You may find it easier to run the 3rd party app using the more general-purpose PHP-FPM container: https://github.com/bitnami/bitnami-docker-php-fpm

**Comment by unlaudable** [comment]
Hi, 

Was trying to run a php script which needed to be placed in the Wordpress home directory which I could not get right using volumes, but turned out that the same provider of the script had a Wordpress plugin anyway. 
It was a utility to migrate a site from Drupal to WP.

Thanks for the reply, apologies for the delayed response.

**Comment by prydonius** [comment]
No problem @unlaudable, glad the WP plugin worked for you 👍
