### ISSUE TITLE
Incompatibility with WP-Encrypt plugin (Let's Encrypt)

### ISSUE THREAD

**Issue by adumont** [bitnami/bitnami-docker-wordpress#75]
I have installed the WP Encrypt, activated, done the setup, but when I click on the "Register Account" button of the WP Encrypt setup page (which says will do: By clicking on this button, you will register an account for the above organization with Let’s Encrypt), it gives this error:

Could not create directory /opt/bitnami/letsencrypt/live. Please check your filesystem permissions.

Any idea how we can work that issue around? Thanks in advance, I'd be happy to help with what I can.

**Comment by adumont** [comment]
Found a way to make it work, if other have the same issue:

From WP Encrypt documentation:

To change the directories where the certificates are being stored, please define a constant called WP_ENCRYPT_SSL_CERTIFICATES_DIR_PATH containing the desired path in your wp-config.php

I created the constant, with this value: /opt/bitnami/apache/conf/letsencrypt/live

I created the /opt/bitnami/apache/conf/letsencrypt/live manually from within the container, and chowned to daemon. Now the setup proceeds further and it worked fine :)

**Comment by chipironcin** [comment]
Maybe we should document this? cc/ @juan131

**Comment by juan131** [comment]
@chipironcin I totally agree on that. This is not trivial and should be documented.

**Comment by marcosbc** [comment]
Hi all, we now support init scripts which you can mount to `/docker-entrypoint-init.d` and perform any post-installation actions. Refer to [`post-init.sh`](https://github.com/bitnami/bitnami-docker-wordpress/blob/master/5/debian-10/rootfs/post-init.sh) for more info.

**Comment by ishaqx** [comment]
Hi. Is it possible that you provide an example of how to use/create an init script to replace the example.com digital certs in /opt/bitnami/apache/conf/bitnami/certs/ with digital certs of your own? I'm using your docker-compose.yaml with persistent volumes and can't think of an easy way to do this. Any help or pointers to the best/easiest way to do this without having to rebuild/extend the image would be appreciated.

**Comment by juan131** [comment]
Hi @ishaqx 

Actually, you don't need to use a custom script for that. You just need to follow the steps described in the link below:

- https://github.com/bitnami/bitnami-docker-apache#using-custom-ssl-certificates

> Note: The steps assume you're using the `bitnami/apache` image but they're applicable to the `/bitnami/wordpress` images, just use a Docker Compose like the one below.

```
version: '2'

services:
  wordpress:
    image: 'bitnami/wordpress'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /path/to/wordpress-certs:/certs
 ```

**Comment by ishaqx** [comment]
Hi @Juan131, that worked great, thank you so much!
