### ISSUE TITLE
mod_status

### ISSUE THREAD

**Issue by BrianHicks** [bitnami/bitnami-docker-wordpress#93]
I'm trying to add [mod_status](https://httpd.apache.org/docs/2.2/mod/mod_status.html) so I can put this container in my monitoring system. It looks like there are tons of places I can stick configuration files in this image, but I just need to add something like the following:

```
<Location /server-status>
    SetHandler server-status

    Order Deny,Allow
    Deny from all
    Allow from localhost
</Location>
```

What would be the best place to do this?

**Comment by juan131** [comment]
`mod_status` is already included in the WordPress Docker Image (you can find it at `/opt/bitnami/apache/modules/mod_status.so`) and it is included in the Apache main configuration file `/opt/bitnami/apache/conf/httpd.conf`:

```
LoadModule status_module modules/mod_status.so
```

On the other hand if you take a look at `/opt/bitnami/apache2/conf/extra/httpd-info.conf` you will find the section:

```
<Location /server-info>
    SetHandler server-info
    Require host .example.com
    Require ip 127
</Location>
```

You can modify it and the uncomment the line below at `/opt/bitnami/apache/conf/httpd.conf`:

```
#Include conf/extra/httpd-info.conf
```

Once you modify the Apache configuration, restart the Apache server by running:

```
nami restart apache
```
