### ISSUE TITLE
new wordpress does not run

### ISSUE THREAD

**Issue by sebgoa** [bitnami/bitnami-docker-wordpress#94]
I am running this docker-compose file, and the wordpress container fails to start:

```
docker logs ddda1e59cae5

Welcome to the Bitnami wordpress container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
Send us your feedback at containers@bitnami.com

ERROR ==> The WORDPRESS_DATABASE_PASSWORD environment variable is empty or not set. Set the environment variable ALLOW_EMPTY_PASSWORD=yes to allow the container to be started with blank passwords. This is recommended only for development.
```

**Comment by sebgoa** [comment]
this file:

https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml

is different than the `docker-compose.yml` file in the README.md

**Comment by carrodher** [comment]
Hi @sebgoa,

@tompizmor just merge PR #95 where the README is corrected to avoid this error.

Thank you very much for reporting it. If you encounter another problem do not hesitate to reopen the issue.

Best regards

**Comment by sebgoa** [comment]
thanks, I tested it an indeed it works.
