### ISSUE TITLE
Running the container as a non-https server

### ISSUE THREAD

**Issue by n3rio** [bitnami/bitnami-docker-wordpress#98]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by n3rio** [comment]
I am sorry, i make a mistake opening this issue.

**Comment by carrodher** [comment]
No problem!
